# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/metrics/messages/provider_status.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gcommon/v1/metrics/messages/provider_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gcommon.v1.metrics.enums import provider_state_pb2 as gcommon_dot_v1_dot_metrics_dot_enums_dot_provider__state__pb2
from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1gcommon/v1/metrics/messages/provider_status.proto\x12\x12gcommon.v1.metrics\x1a-gcommon/v1/metrics/enums/provider_state.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n\x0eProviderStatus\x12\x37\n\x05state\x18\x01 \x01(\x0e\x32!.gcommon.v1.metrics.ProviderStateR\x05state\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12\x16\n\x06health\x18\x03 \x01(\tR\x06health\x12=\n\x0clast_updated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0blastUpdated\x12\x18\n\x07version\x18\x05 \x01(\tR\x07versionB\x14Z\nv1/metrics\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcommon.v1.metrics.messages.provider_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\nv1/metrics\222\003\005\322>\002\020\003'
  _globals['_PROVIDERSTATUS']._serialized_start=189
  _globals['_PROVIDERSTATUS']._serialized_end=401
# @@protoc_insertion_point(module_scope)
