# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/metrics/messages/record_counter_request.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gcommon/v1/metrics/messages/record_counter_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gcommon.v1.common.messages import request_metadata_pb2 as gcommon_dot_v1_dot_common_dot_messages_dot_request__metadata__pb2
from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8gcommon/v1/metrics/messages/record_counter_request.proto\x12\x12gcommon.v1.metrics\x1a\x31gcommon/v1/common/messages/request_metadata.proto\x1a!google/protobuf/go_features.proto\"\xd2\x02\n\x14RecordCounterRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n\x05value\x18\x02 \x01(\x01R\x05value\x12L\n\x06labels\x18\x03 \x03(\x0b\x32\x34.gcommon.v1.metrics.RecordCounterRequest.LabelsEntryR\x06labels\x12\x12\n\x04help\x18\x04 \x01(\tR\x04help\x12\x12\n\x04unit\x18\x05 \x01(\tR\x04unit\x12\x1f\n\x0bsample_rate\x18\x06 \x01(\x01R\nsampleRate\x12>\n\x08metadata\x18\x07 \x01(\x0b\x32\".gcommon.v1.common.RequestMetadataR\x08metadata\x1a\x39\n\x0bLabelsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\xd0\x01\n\x16\x63om.gcommon.v1.metricsB\x19RecordCounterRequestProtoP\x01Z)github.com/jdfalk/gcommon/sdks/go/metrics\xa2\x02\x03GVM\xaa\x02\x12Gcommon.V1.Metrics\xca\x02\x12Gcommon\\V1\\Metrics\xe2\x02\x1eGcommon\\V1\\Metrics\\GPBMetadata\xea\x02\x14Gcommon::V1::Metrics\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcommon.v1.metrics.messages.record_counter_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.gcommon.v1.metricsB\031RecordCounterRequestProtoP\001Z)github.com/jdfalk/gcommon/sdks/go/metrics\242\002\003GVM\252\002\022Gcommon.V1.Metrics\312\002\022Gcommon\\V1\\Metrics\342\002\036Gcommon\\V1\\Metrics\\GPBMetadata\352\002\024Gcommon::V1::Metrics\222\003\005\322>\002\020\003'
  _globals['_RECORDCOUNTERREQUEST_LABELSENTRY']._loaded_options = None
  _globals['_RECORDCOUNTERREQUEST_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_RECORDCOUNTERREQUEST']._serialized_start=167
  _globals['_RECORDCOUNTERREQUEST']._serialized_end=505
  _globals['_RECORDCOUNTERREQUEST_LABELSENTRY']._serialized_start=448
  _globals['_RECORDCOUNTERREQUEST_LABELSENTRY']._serialized_end=505
# @@protoc_insertion_point(module_scope)
