// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/db/proto/consistency_level.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// ConsistencyLevel defines the data consistency requirements for database operations.
// Controls the trade-off between consistency, availability, and partition tolerance.
type ConsistencyLevel int32

const (
	// Default unspecified consistency level
	ConsistencyLevel_CONSISTENCY_LEVEL_UNSPECIFIED ConsistencyLevel = 0
	// Eventual consistency - may read stale data but eventually consistent
	ConsistencyLevel_CONSISTENCY_LEVEL_EVENTUAL ConsistencyLevel = 1
	// Strong consistency - always reads most recent committed data
	ConsistencyLevel_CONSISTENCY_LEVEL_STRONG ConsistencyLevel = 2
	// Bounded staleness - reads data within specified time bounds
	ConsistencyLevel_CONSISTENCY_LEVEL_BOUNDED_STALENESS ConsistencyLevel = 3
)

// Enum value maps for ConsistencyLevel.
var (
	ConsistencyLevel_name = map[int32]string{
		0: "CONSISTENCY_LEVEL_UNSPECIFIED",
		1: "CONSISTENCY_LEVEL_EVENTUAL",
		2: "CONSISTENCY_LEVEL_STRONG",
		3: "CONSISTENCY_LEVEL_BOUNDED_STALENESS",
	}
	ConsistencyLevel_value = map[string]int32{
		"CONSISTENCY_LEVEL_UNSPECIFIED":       0,
		"CONSISTENCY_LEVEL_EVENTUAL":          1,
		"CONSISTENCY_LEVEL_STRONG":            2,
		"CONSISTENCY_LEVEL_BOUNDED_STALENESS": 3,
	}
)

func (x ConsistencyLevel) Enum() *ConsistencyLevel {
	p := new(ConsistencyLevel)
	*p = x
	return p
}

func (x ConsistencyLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistencyLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_db_proto_consistency_level_proto_enumTypes[0].Descriptor()
}

func (ConsistencyLevel) Type() protoreflect.EnumType {
	return &file_pkg_db_proto_consistency_level_proto_enumTypes[0]
}

func (x ConsistencyLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistencyLevel.Descriptor instead.
func (ConsistencyLevel) EnumDescriptor() ([]byte, []int) {
	return file_pkg_db_proto_consistency_level_proto_rawDescGZIP(), []int{0}
}

var File_pkg_db_proto_consistency_level_proto protoreflect.FileDescriptor

const file_pkg_db_proto_consistency_level_proto_rawDesc = "" +
	"\n" +
	"$pkg/db/proto/consistency_level.proto\x12\x13gcommon.v1.database*\x9c\x01\n" +
	"\x10ConsistencyLevel\x12!\n" +
	"\x1dCONSISTENCY_LEVEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONSISTENCY_LEVEL_EVENTUAL\x10\x01\x12\x1c\n" +
	"\x18CONSISTENCY_LEVEL_STRONG\x10\x02\x12'\n" +
	"#CONSISTENCY_LEVEL_BOUNDED_STALENESS\x10\x03B\xc6\x01\n" +
	"\x17com.gcommon.v1.databaseB\x15ConsistencyLevelProtoP\x01Z&github.com/jdfalk/gcommon/pkg/db/proto\xa2\x02\x03GVD\xaa\x02\x13Gcommon.V1.Database\xca\x02\x13Gcommon\\V1\\Database\xe2\x02\x1fGcommon\\V1\\Database\\GPBMetadata\xea\x02\x15Gcommon::V1::Databaseb\beditionsp\xe8\a"

var (
	file_pkg_db_proto_consistency_level_proto_rawDescOnce sync.Once
	file_pkg_db_proto_consistency_level_proto_rawDescData []byte
)

func file_pkg_db_proto_consistency_level_proto_rawDescGZIP() []byte {
	file_pkg_db_proto_consistency_level_proto_rawDescOnce.Do(func() {
		file_pkg_db_proto_consistency_level_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_db_proto_consistency_level_proto_rawDesc), len(file_pkg_db_proto_consistency_level_proto_rawDesc)))
	})
	return file_pkg_db_proto_consistency_level_proto_rawDescData
}

var file_pkg_db_proto_consistency_level_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_db_proto_consistency_level_proto_goTypes = []any{
	(ConsistencyLevel)(0), // 0: gcommon.v1.database.ConsistencyLevel
}
var file_pkg_db_proto_consistency_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_db_proto_consistency_level_proto_init() }
func file_pkg_db_proto_consistency_level_proto_init() {
	if File_pkg_db_proto_consistency_level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_db_proto_consistency_level_proto_rawDesc), len(file_pkg_db_proto_consistency_level_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_db_proto_consistency_level_proto_goTypes,
		DependencyIndexes: file_pkg_db_proto_consistency_level_proto_depIdxs,
		EnumInfos:         file_pkg_db_proto_consistency_level_proto_enumTypes,
	}.Build()
	File_pkg_db_proto_consistency_level_proto = out.File
	file_pkg_db_proto_consistency_level_proto_goTypes = nil
	file_pkg_db_proto_consistency_level_proto_depIdxs = nil
}
