# file: deploy/helm/gcommon-app/values.yaml
# version: 1.0.0
# guid: 9b745489-a895-4886-a4aa-771f457615bb

# Default values for gcommon-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gcommon/app
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80
  annotations: {}

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: gcommon.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

config:
  APP_ENV: production
  LOG_LEVEL: info

secret:
  create: true
  data:
    DATABASE_URL: ""

monitoring:
  prometheus:
    enabled: true
    scrapeInterval: 15s
  logging:
    fluentBit:
      enabled: true
  tracing:
    jaeger:
      enabled: true

nodeSelector: {}

tolerations: []

affinity: {}

# Additional environment variables
extraEnv: []

# Extra volumes and mounts
extraVolumes: []
extraVolumeMounts: []

# Liveness and readiness probe settings
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# Sidecars
sidecars: []

# Metrics service for Prometheus
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels: {}

# HPA Metrics
hpaMetrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

# Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Extra labels
labels: {}

# Volume claim template for stateful workloads
persistence:
  enabled: false
  size: 1Gi
  storageClass: ""
