# file: templates/basic-api-service/deploy/service.yaml
# version: 1.0.0
# guid: c410c9dd-cfbe-42af-a089-0a31a59603db

apiVersion: v1
kind: Service
metadata:
  name: basic-api-service
spec:
  selector:
    app: basic-api-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
  type: ClusterIP
