# file: deploy/kubernetes/monitoring/jaeger.yaml
# version: 1.0.0
# guid: af5bb18e-3ee9-4f87-a200-b8263297e776

apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: allInOne
  allInOne:
    options:
      query:
        base-path: /
  storage:
    type: memory
