from gcommon.v1.organization.messages import add_member_request_pb2 as _add_member_request_pb2
from gcommon.v1.organization.messages import add_member_response_pb2 as _add_member_response_pb2
from gcommon.v1.organization.messages import create_organization_request_pb2 as _create_organization_request_pb2
from gcommon.v1.organization.messages import create_organization_response_pb2 as _create_organization_response_pb2
from gcommon.v1.organization.messages import delete_organization_request_pb2 as _delete_organization_request_pb2
from gcommon.v1.organization.messages import delete_organization_response_pb2 as _delete_organization_response_pb2
from gcommon.v1.organization.messages import get_organization_request_pb2 as _get_organization_request_pb2
from gcommon.v1.organization.messages import get_organization_response_pb2 as _get_organization_response_pb2
from gcommon.v1.organization.messages import get_organization_settings_request_pb2 as _get_organization_settings_request_pb2
from gcommon.v1.organization.messages import get_organization_settings_response_pb2 as _get_organization_settings_response_pb2
from gcommon.v1.organization.messages import list_members_request_pb2 as _list_members_request_pb2
from gcommon.v1.organization.messages import list_members_response_pb2 as _list_members_response_pb2
from gcommon.v1.organization.messages import list_organizations_request_pb2 as _list_organizations_request_pb2
from gcommon.v1.organization.messages import list_organizations_response_pb2 as _list_organizations_response_pb2
from gcommon.v1.organization.messages import remove_member_request_pb2 as _remove_member_request_pb2
from gcommon.v1.organization.messages import remove_member_response_pb2 as _remove_member_response_pb2
from gcommon.v1.organization.messages import update_member_request_pb2 as _update_member_request_pb2
from gcommon.v1.organization.messages import update_member_response_pb2 as _update_member_response_pb2
from gcommon.v1.organization.messages import update_organization_request_pb2 as _update_organization_request_pb2
from gcommon.v1.organization.messages import update_organization_response_pb2 as _update_organization_response_pb2
from gcommon.v1.organization.messages import update_organization_settings_request_pb2 as _update_organization_settings_request_pb2
from gcommon.v1.organization.messages import update_organization_settings_response_pb2 as _update_organization_settings_response_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
