// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gcommon/v1/common/subscription_info.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Subscription information for streaming and event-driven operations.
// Manages long-lived subscriptions with filtering, time ranges,
// and client-specific configuration for real-time data streaming.
type CommonSubscriptionInfo struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SubscriptionId *string                `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId"`
	xxx_hidden_Filter         *FilterOptions         `protobuf:"bytes,2,opt,name=filter"`
	xxx_hidden_StartTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime"`
	xxx_hidden_EndTime        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime"`
	xxx_hidden_Subscriber     *ClientInfo            `protobuf:"bytes,5,opt,name=subscriber"`
	xxx_hidden_Options        *SubscriptionOptions   `protobuf:"bytes,6,opt,name=options"`
	xxx_hidden_Status         SubscriptionStatus     `protobuf:"varint,7,opt,name=status,enum=gcommon.v1.common.SubscriptionStatus"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CommonSubscriptionInfo) Reset() {
	*x = CommonSubscriptionInfo{}
	mi := &file_gcommon_v1_common_subscription_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonSubscriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSubscriptionInfo) ProtoMessage() {}

func (x *CommonSubscriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_common_subscription_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommonSubscriptionInfo) GetSubscriptionId() string {
	if x != nil {
		if x.xxx_hidden_SubscriptionId != nil {
			return *x.xxx_hidden_SubscriptionId
		}
		return ""
	}
	return ""
}

func (x *CommonSubscriptionInfo) GetFilter() *FilterOptions {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *CommonSubscriptionInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartTime
	}
	return nil
}

func (x *CommonSubscriptionInfo) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndTime
	}
	return nil
}

func (x *CommonSubscriptionInfo) GetSubscriber() *ClientInfo {
	if x != nil {
		return x.xxx_hidden_Subscriber
	}
	return nil
}

func (x *CommonSubscriptionInfo) GetOptions() *SubscriptionOptions {
	if x != nil {
		return x.xxx_hidden_Options
	}
	return nil
}

func (x *CommonSubscriptionInfo) GetStatus() SubscriptionStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 6) {
			return x.xxx_hidden_Status
		}
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *CommonSubscriptionInfo) SetSubscriptionId(v string) {
	x.xxx_hidden_SubscriptionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *CommonSubscriptionInfo) SetFilter(v *FilterOptions) {
	x.xxx_hidden_Filter = v
}

func (x *CommonSubscriptionInfo) SetStartTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartTime = v
}

func (x *CommonSubscriptionInfo) SetEndTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndTime = v
}

func (x *CommonSubscriptionInfo) SetSubscriber(v *ClientInfo) {
	x.xxx_hidden_Subscriber = v
}

func (x *CommonSubscriptionInfo) SetOptions(v *SubscriptionOptions) {
	x.xxx_hidden_Options = v
}

func (x *CommonSubscriptionInfo) SetStatus(v SubscriptionStatus) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *CommonSubscriptionInfo) HasSubscriptionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CommonSubscriptionInfo) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *CommonSubscriptionInfo) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartTime != nil
}

func (x *CommonSubscriptionInfo) HasEndTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndTime != nil
}

func (x *CommonSubscriptionInfo) HasSubscriber() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Subscriber != nil
}

func (x *CommonSubscriptionInfo) HasOptions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Options != nil
}

func (x *CommonSubscriptionInfo) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *CommonSubscriptionInfo) ClearSubscriptionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SubscriptionId = nil
}

func (x *CommonSubscriptionInfo) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

func (x *CommonSubscriptionInfo) ClearStartTime() {
	x.xxx_hidden_StartTime = nil
}

func (x *CommonSubscriptionInfo) ClearEndTime() {
	x.xxx_hidden_EndTime = nil
}

func (x *CommonSubscriptionInfo) ClearSubscriber() {
	x.xxx_hidden_Subscriber = nil
}

func (x *CommonSubscriptionInfo) ClearOptions() {
	x.xxx_hidden_Options = nil
}

func (x *CommonSubscriptionInfo) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Status = SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

type CommonSubscriptionInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier for this subscription
	SubscriptionId *string
	// Filter criteria for subscription events
	Filter *FilterOptions
	// When the subscription started
	StartTime *timestamppb.Timestamp
	// Optional end time for the subscription (null for indefinite)
	EndTime *timestamppb.Timestamp
	// Information about the subscribing client
	Subscriber *ClientInfo
	// Subscription configuration options
	Options *SubscriptionOptions
	// Current status of the subscription
	Status *SubscriptionStatus
}

func (b0 CommonSubscriptionInfo_builder) Build() *CommonSubscriptionInfo {
	m0 := &CommonSubscriptionInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SubscriptionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_SubscriptionId = b.SubscriptionId
	}
	x.xxx_hidden_Filter = b.Filter
	x.xxx_hidden_StartTime = b.StartTime
	x.xxx_hidden_EndTime = b.EndTime
	x.xxx_hidden_Subscriber = b.Subscriber
	x.xxx_hidden_Options = b.Options
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_Status = *b.Status
	}
	return m0
}

var File_gcommon_v1_common_subscription_info_proto protoreflect.FileDescriptor

const file_gcommon_v1_common_subscription_info_proto_rawDesc = "" +
	"\n" +
	")gcommon/v1/common/subscription_info.proto\x12\x11gcommon.v1.common\x1a+gcommon/v1/common/subscription_status.proto\x1a#gcommon/v1/common/client_info.proto\x1a&gcommon/v1/common/filter_options.proto\x1a,gcommon/v1/common/subscription_options.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x03\n" +
	"\x16CommonSubscriptionInfo\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x128\n" +
	"\x06filter\x18\x02 \x01(\v2 .gcommon.v1.common.FilterOptionsR\x06filter\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12=\n" +
	"\n" +
	"subscriber\x18\x05 \x01(\v2\x1d.gcommon.v1.common.ClientInfoR\n" +
	"subscriber\x12@\n" +
	"\aoptions\x18\x06 \x01(\v2&.gcommon.v1.common.SubscriptionOptionsR\aoptions\x12=\n" +
	"\x06status\x18\a \x01(\x0e2%.gcommon.v1.common.SubscriptionStatusR\x06statusB5Z+github.com/jdfalk/gcommon/sdks/go/v1/common\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_common_subscription_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gcommon_v1_common_subscription_info_proto_goTypes = []any{
	(*CommonSubscriptionInfo)(nil), // 0: gcommon.v1.common.CommonSubscriptionInfo
	(*FilterOptions)(nil),          // 1: gcommon.v1.common.FilterOptions
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
	(*ClientInfo)(nil),             // 3: gcommon.v1.common.ClientInfo
	(*SubscriptionOptions)(nil),    // 4: gcommon.v1.common.SubscriptionOptions
	(SubscriptionStatus)(0),        // 5: gcommon.v1.common.SubscriptionStatus
}
var file_gcommon_v1_common_subscription_info_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.common.CommonSubscriptionInfo.filter:type_name -> gcommon.v1.common.FilterOptions
	2, // 1: gcommon.v1.common.CommonSubscriptionInfo.start_time:type_name -> google.protobuf.Timestamp
	2, // 2: gcommon.v1.common.CommonSubscriptionInfo.end_time:type_name -> google.protobuf.Timestamp
	3, // 3: gcommon.v1.common.CommonSubscriptionInfo.subscriber:type_name -> gcommon.v1.common.ClientInfo
	4, // 4: gcommon.v1.common.CommonSubscriptionInfo.options:type_name -> gcommon.v1.common.SubscriptionOptions
	5, // 5: gcommon.v1.common.CommonSubscriptionInfo.status:type_name -> gcommon.v1.common.SubscriptionStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gcommon_v1_common_subscription_info_proto_init() }
func file_gcommon_v1_common_subscription_info_proto_init() {
	if File_gcommon_v1_common_subscription_info_proto != nil {
		return
	}
	file_gcommon_v1_common_subscription_status_proto_init()
	file_gcommon_v1_common_client_info_proto_init()
	file_gcommon_v1_common_filter_options_proto_init()
	file_gcommon_v1_common_subscription_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_common_subscription_info_proto_rawDesc), len(file_gcommon_v1_common_subscription_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_common_subscription_info_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_common_subscription_info_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_common_subscription_info_proto_msgTypes,
	}.Build()
	File_gcommon_v1_common_subscription_info_proto = out.File
	file_gcommon_v1_common_subscription_info_proto_goTypes = nil
	file_gcommon_v1_common_subscription_info_proto_depIdxs = nil
}
