# Mockery v3 configuration for generating mocks from gRPC proto interfaces

# Global configuration
template: testify
formatter: goimports
log-level: info

packages:
  github.com/jdfalk/gcommon/pkg/auth/proto:
    config:
      dir: pkg/auth/mock
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: mock
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      AuthServiceClient:
      AuthServiceServer:
      AuthorizationServiceClient:
      AuthorizationServiceServer:
      SessionServiceClient:
      SessionServiceServer:

  github.com/jdfalk/gcommon/pkg/cache/proto:
    config:
      dir: pkg/cache/mock
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: mock
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      CacheServiceClient:
      CacheServiceServer:
      CacheAdminServiceClient:
      CacheAdminServiceServer:

  github.com/jdfalk/gcommon/pkg/config/proto:
    config:
      dir: pkg/config/mock
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: mock
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      ConfigServiceClient:
      ConfigServiceServer:
      # ConfigAdminServiceClient:  # TODO: Uncomment when service is implemented
      # ConfigAdminServiceServer:  # TODO: Uncomment when service is implemented

  github.com/jdfalk/gcommon/pkg/db/proto:
    config:
      dir: pkg/db/mock
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: mock
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      DatabaseServiceClient:
      DatabaseServiceServer:
      DatabaseAdminServiceClient:
      DatabaseAdminServiceServer:

  github.com/jdfalk/gcommon/pkg/health/proto:
    config:
      dir: pkg/health/mock
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: mock
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      HealthServiceClient:
      HealthServiceServer:
      # HealthCheckServiceClient:  # TODO: Uncomment when service is implemented
      # HealthCheckServiceServer:  # TODO: Uncomment when service is implemented
      # HealthAdminServiceClient:  # TODO: Uncomment when service is implemented
      # HealthAdminServiceServer:  # TODO: Uncomment when service is implemented

  github.com/jdfalk/gcommon/pkg/log/proto:
    config:
      dir: pkg/log/mock
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: mock
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      # LogServiceClient:          # TODO: Uncomment when service is implemented
      # LogServiceServer:          # TODO: Uncomment when service is implemented
      # LogAdminServiceClient:     # TODO: Uncomment when service is implemented
      # LogAdminServiceServer:     # TODO: Uncomment when service is implemented

  github.com/jdfalk/gcommon/pkg/metrics/proto:
    config:
      dir: pkg/metrics/mock
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: mock
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      MetricsServiceClient:
      MetricsServiceServer:
      MetricsAdminServiceClient:
      MetricsAdminServiceServer:

  github.com/jdfalk/gcommon/pkg/queue/proto:
    config:
      dir: pkg/queue/mock
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: mock
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      # QueueServiceClient:        # TODO: Uncomment when service is implemented
      # QueueServiceServer:        # TODO: Uncomment when service is implemented
      # QueueAdminServiceClient:   # TODO: Uncomment when service is implemented
      # QueueAdminServiceServer:   # TODO: Uncomment when service is implemented

  github.com/jdfalk/gcommon/pkg/web/proto:
    config:
      dir: pkg/web/mock
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: mock
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      WebServiceClient:
      WebServiceServer:
      WebAdminServiceClient:
      WebAdminServiceServer:
