# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/media/sync_subtitles_response.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'gcommon/v1/media/sync_subtitles_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.gcommon/v1/media/sync_subtitles_response.proto\x12\x10gcommon.v1.media\x1a!google/protobuf/go_features.proto\x1a\x1b\x62uf/validate/validate.proto\"\xd6\x01\n\x15SyncSubtitlesResponse\x12J\n\x1dsynchronized_subtitle_file_id\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x1asynchronizedSubtitleFileId\x12\x18\n\x07success\x18\x02 \x01(\x08R\x07success\x12,\n\rerror_message\x18\x03 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x0c\x65rrorMessage\x12)\n\x10\x61\x64justments_made\x18\x04 \x01(\x05R\x0f\x61\x64justmentsMadeB4Z*github.com/jdfalk/gcommon/sdks/go/v1/media\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcommon.v1.media.sync_subtitles_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/jdfalk/gcommon/sdks/go/v1/media\222\003\005\322>\002\020\003'
  _globals['_SYNCSUBTITLESRESPONSE'].fields_by_name['synchronized_subtitle_file_id']._loaded_options = None
  _globals['_SYNCSUBTITLESRESPONSE'].fields_by_name['synchronized_subtitle_file_id']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_SYNCSUBTITLESRESPONSE'].fields_by_name['error_message']._loaded_options = None
  _globals['_SYNCSUBTITLESRESPONSE'].fields_by_name['error_message']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_SYNCSUBTITLESRESPONSE']._serialized_start=133
  _globals['_SYNCSUBTITLESRESPONSE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
