# file: deploy/docker/docker-compose.yaml
# version: 1.0.0
# guid: 7f83576f-4c6b-41fa-ba0c-e853a07c9674

version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: gcommon/app:dev
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
    depends_on:
      - db
      - cache
    volumes:
      - ../:/workspace

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=gcommon
      - POSTGRES_PASSWORD=gcommon
      - POSTGRES_DB=gcommon
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - "16686:16686"
      - "14250:14250"

  fluent-bit:
    image: fluent/fluent-bit:3.0
    volumes:
      - ./monitoring/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - app

volumes:
  db-data:
  cache-data:
  grafana-data:
