# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/common/enums/alert_severity.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gcommon/v1/common/enums/alert_severity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,gcommon/v1/common/enums/alert_severity.proto\x12\x11gcommon.v1.common\x1a!google/protobuf/go_features.proto*\xed\x01\n\x13\x43ommonAlertSeverity\x12\x1e\n\x1a\x41LERT_SEVERITY_UNSPECIFIED\x10\x00\x12\x16\n\x12\x41LERT_SEVERITY_LOW\x10\x01\x12\x19\n\x15\x41LERT_SEVERITY_MEDIUM\x10\x02\x12\x17\n\x13\x41LERT_SEVERITY_HIGH\x10\x03\x12\x1b\n\x17\x41LERT_SEVERITY_CRITICAL\x10\x04\x12\x17\n\x13\x41LERT_SEVERITY_INFO\x10\x05\x12\x1a\n\x16\x41LERT_SEVERITY_WARNING\x10\x06\x12\x18\n\x14\x41LERT_SEVERITY_ERROR\x10\x07\x42\xd0\x01\n\x15\x63om.gcommon.v1.commonB\x12\x41lertSeverityProtoP\x01Z5github.com/jdfalk/gcommon/pkg/gcommon/v1/common/enums\xa2\x02\x03GVC\xaa\x02\x11Gcommon.V1.Common\xca\x02\x11Gcommon\\V1\\Common\xe2\x02\x1dGcommon\\V1\\Common\\GPBMetadata\xea\x02\x13Gcommon::V1::Common\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcommon.v1.common.enums.alert_severity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.gcommon.v1.commonB\022AlertSeverityProtoP\001Z5github.com/jdfalk/gcommon/pkg/gcommon/v1/common/enums\242\002\003GVC\252\002\021Gcommon.V1.Common\312\002\021Gcommon\\V1\\Common\342\002\035Gcommon\\V1\\Common\\GPBMetadata\352\002\023Gcommon::V1::Common\222\003\005\322>\002\020\003'
  _globals['_COMMONALERTSEVERITY']._serialized_start=103
  _globals['_COMMONALERTSEVERITY']._serialized_end=340
# @@protoc_insertion_point(module_scope)
