// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/notification/proto/messages/subscription_preferences.proto

//go:build !protoopaque

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// User subscription preferences for event notifications.
type SubscriptionPreferences struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// User or entity identifier
	UserId *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// Enabled delivery channels
	Channels []DeliveryChannelType `protobuf:"varint,2,rep,packed,name=channels,enum=gcommon.v1.notification.DeliveryChannelType" json:"channels,omitempty"`
	// Subscribed event types
	Events []string `protobuf:"bytes,3,rep,name=events" json:"events,omitempty"`
	// Additional arbitrary preferences
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionPreferences) Reset() {
	*x = SubscriptionPreferences{}
	mi := &file_pkg_notification_proto_messages_subscription_preferences_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionPreferences) ProtoMessage() {}

func (x *SubscriptionPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_notification_proto_messages_subscription_preferences_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SubscriptionPreferences) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *SubscriptionPreferences) GetChannels() []DeliveryChannelType {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *SubscriptionPreferences) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SubscriptionPreferences) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SubscriptionPreferences) SetUserId(v string) {
	x.UserId = &v
}

func (x *SubscriptionPreferences) SetChannels(v []DeliveryChannelType) {
	x.Channels = v
}

func (x *SubscriptionPreferences) SetEvents(v []string) {
	x.Events = v
}

func (x *SubscriptionPreferences) SetMetadata(v map[string]string) {
	x.Metadata = v
}

func (x *SubscriptionPreferences) HasUserId() bool {
	if x == nil {
		return false
	}
	return x.UserId != nil
}

func (x *SubscriptionPreferences) ClearUserId() {
	x.UserId = nil
}

type SubscriptionPreferences_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// User or entity identifier
	UserId *string
	// Enabled delivery channels
	Channels []DeliveryChannelType
	// Subscribed event types
	Events []string
	// Additional arbitrary preferences
	Metadata map[string]string
}

func (b0 SubscriptionPreferences_builder) Build() *SubscriptionPreferences {
	m0 := &SubscriptionPreferences{}
	b, x := &b0, m0
	_, _ = b, x
	x.UserId = b.UserId
	x.Channels = b.Channels
	x.Events = b.Events
	x.Metadata = b.Metadata
	return m0
}

var File_pkg_notification_proto_messages_subscription_preferences_proto protoreflect.FileDescriptor

const file_pkg_notification_proto_messages_subscription_preferences_proto_rawDesc = "" +
	"\n" +
	">pkg/notification/proto/messages/subscription_preferences.proto\x12\x17gcommon.v1.notification\x1a!google/protobuf/go_features.proto\x1a6pkg/notification/proto/messages/delivery_channel.proto\"\xb1\x02\n" +
	"\x17SubscriptionPreferences\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12H\n" +
	"\bchannels\x18\x02 \x03(\x0e2,.gcommon.v1.notification.DeliveryChannelTypeR\bchannels\x12\x16\n" +
	"\x06events\x18\x03 \x03(\tR\x06events\x12^\n" +
	"\bmetadata\x18\x04 \x03(\v2>.gcommon.v1.notification.SubscriptionPreferences.MetadataEntryB\x02(\x01R\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x82\x02\n" +
	"\x1bcom.gcommon.v1.notificationB\x1cSubscriptionPreferencesProtoP\x01Z?github.com/jdfalk/gcommon/pkg/notification/proto;notificationpb\xa2\x02\x03GVN\xaa\x02\x17Gcommon.V1.Notification\xca\x02\x17Gcommon\\V1\\Notification\xe2\x02#Gcommon\\V1\\Notification\\GPBMetadata\xea\x02\x19Gcommon::V1::Notification\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_pkg_notification_proto_messages_subscription_preferences_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_notification_proto_messages_subscription_preferences_proto_goTypes = []any{
	(*SubscriptionPreferences)(nil), // 0: gcommon.v1.notification.SubscriptionPreferences
	nil,                             // 1: gcommon.v1.notification.SubscriptionPreferences.MetadataEntry
	(DeliveryChannelType)(0),        // 2: gcommon.v1.notification.DeliveryChannelType
}
var file_pkg_notification_proto_messages_subscription_preferences_proto_depIdxs = []int32{
	2, // 0: gcommon.v1.notification.SubscriptionPreferences.channels:type_name -> gcommon.v1.notification.DeliveryChannelType
	1, // 1: gcommon.v1.notification.SubscriptionPreferences.metadata:type_name -> gcommon.v1.notification.SubscriptionPreferences.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_notification_proto_messages_subscription_preferences_proto_init() }
func file_pkg_notification_proto_messages_subscription_preferences_proto_init() {
	if File_pkg_notification_proto_messages_subscription_preferences_proto != nil {
		return
	}
	file_pkg_notification_proto_messages_delivery_channel_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_notification_proto_messages_subscription_preferences_proto_rawDesc), len(file_pkg_notification_proto_messages_subscription_preferences_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_notification_proto_messages_subscription_preferences_proto_goTypes,
		DependencyIndexes: file_pkg_notification_proto_messages_subscription_preferences_proto_depIdxs,
		MessageInfos:      file_pkg_notification_proto_messages_subscription_preferences_proto_msgTypes,
	}.Build()
	File_pkg_notification_proto_messages_subscription_preferences_proto = out.File
	file_pkg_notification_proto_messages_subscription_preferences_proto_goTypes = nil
	file_pkg_notification_proto_messages_subscription_preferences_proto_depIdxs = nil
}
