// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/auth/proto/requests/get_role_request.proto

//go:build protoopaque

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pkg_auth_proto_requests_get_role_request_proto protoreflect.FileDescriptor

const file_pkg_auth_proto_requests_get_role_request_proto_rawDesc = "" +
	"\n" +
	".pkg/auth/proto/requests/get_role_request.proto\x12\x0fgcommon.v1.auth\x1a!google/protobuf/go_features.protoB\xc1\x01\n" +
	"\x13com.gcommon.v1.authB\x13GetRoleRequestProtoP\x01Z/github.com/jdfalk/gcommon/pkg/auth/proto;authpb\xa2\x02\x03GVA\xaa\x02\x0fGcommon.V1.Auth\xca\x02\x0fGcommon\\V1\\Auth\xe2\x02\x1bGcommon\\V1\\Auth\\GPBMetadata\xea\x02\x11Gcommon::V1::Auth\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_pkg_auth_proto_requests_get_role_request_proto_goTypes = []any{}
var file_pkg_auth_proto_requests_get_role_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_auth_proto_requests_get_role_request_proto_init() }
func file_pkg_auth_proto_requests_get_role_request_proto_init() {
	if File_pkg_auth_proto_requests_get_role_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_auth_proto_requests_get_role_request_proto_rawDesc), len(file_pkg_auth_proto_requests_get_role_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_auth_proto_requests_get_role_request_proto_goTypes,
		DependencyIndexes: file_pkg_auth_proto_requests_get_role_request_proto_depIdxs,
	}.Build()
	File_pkg_auth_proto_requests_get_role_request_proto = out.File
	file_pkg_auth_proto_requests_get_role_request_proto_goTypes = nil
	file_pkg_auth_proto_requests_get_role_request_proto_depIdxs = nil
}
