// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/auth/proto/requests/revoke_token_request.proto

//go:build !protoopaque

package authpb

import (
	pb "../../../../pkg/common/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request to revoke a token (access or refresh).
// Invalidates the specified token and prevents further use.
// Used for logout operations and security revocation.
type RevokeTokenRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Token to revoke (access or refresh token)
	Token *string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	// Token type hint ("access_token" or "refresh_token")
	TokenTypeHint *string `protobuf:"bytes,2,opt,name=token_type_hint,json=tokenTypeHint" json:"token_type_hint,omitempty"`
	// Request metadata for tracing and correlation
	Metadata      *pb.RequestMetadata `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_pkg_auth_proto_requests_revoke_token_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_auth_proto_requests_revoke_token_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RevokeTokenRequest) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *RevokeTokenRequest) GetTokenTypeHint() string {
	if x != nil && x.TokenTypeHint != nil {
		return *x.TokenTypeHint
	}
	return ""
}

func (x *RevokeTokenRequest) GetMetadata() *pb.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RevokeTokenRequest) SetToken(v string) {
	x.Token = &v
}

func (x *RevokeTokenRequest) SetTokenTypeHint(v string) {
	x.TokenTypeHint = &v
}

func (x *RevokeTokenRequest) SetMetadata(v *pb.RequestMetadata) {
	x.Metadata = v
}

func (x *RevokeTokenRequest) HasToken() bool {
	if x == nil {
		return false
	}
	return x.Token != nil
}

func (x *RevokeTokenRequest) HasTokenTypeHint() bool {
	if x == nil {
		return false
	}
	return x.TokenTypeHint != nil
}

func (x *RevokeTokenRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *RevokeTokenRequest) ClearToken() {
	x.Token = nil
}

func (x *RevokeTokenRequest) ClearTokenTypeHint() {
	x.TokenTypeHint = nil
}

func (x *RevokeTokenRequest) ClearMetadata() {
	x.Metadata = nil
}

type RevokeTokenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Token to revoke (access or refresh token)
	Token *string
	// Token type hint ("access_token" or "refresh_token")
	TokenTypeHint *string
	// Request metadata for tracing and correlation
	Metadata *pb.RequestMetadata
}

func (b0 RevokeTokenRequest_builder) Build() *RevokeTokenRequest {
	m0 := &RevokeTokenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Token = b.Token
	x.TokenTypeHint = b.TokenTypeHint
	x.Metadata = b.Metadata
	return m0
}

var File_pkg_auth_proto_requests_revoke_token_request_proto protoreflect.FileDescriptor

const file_pkg_auth_proto_requests_revoke_token_request_proto_rawDesc = "" +
	"\n" +
	"2pkg/auth/proto/requests/revoke_token_request.proto\x12\x0fgcommon.v1.auth\x1a!google/protobuf/go_features.proto\x1a0pkg/common/proto/messages/request_metadata.proto\"\x92\x01\n" +
	"\x12RevokeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12&\n" +
	"\x0ftoken_type_hint\x18\x02 \x01(\tR\rtokenTypeHint\x12>\n" +
	"\bmetadata\x18\x03 \x01(\v2\".gcommon.v1.common.RequestMetadataR\bmetadataB\xb4\x01\n" +
	"\x13com.gcommon.v1.authB\x17RevokeTokenRequestProtoP\x01Z\x1e../../../../pkg/auth/pb;authpb\xa2\x02\x03GVA\xaa\x02\x0fGcommon.V1.Auth\xca\x02\x0fGcommon\\V1\\Auth\xe2\x02\x1bGcommon\\V1\\Auth\\GPBMetadata\xea\x02\x11Gcommon::V1::Auth\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_pkg_auth_proto_requests_revoke_token_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_auth_proto_requests_revoke_token_request_proto_goTypes = []any{
	(*RevokeTokenRequest)(nil), // 0: gcommon.v1.auth.RevokeTokenRequest
	(*pb.RequestMetadata)(nil), // 1: gcommon.v1.common.RequestMetadata
}
var file_pkg_auth_proto_requests_revoke_token_request_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.auth.RevokeTokenRequest.metadata:type_name -> gcommon.v1.common.RequestMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_auth_proto_requests_revoke_token_request_proto_init() }
func file_pkg_auth_proto_requests_revoke_token_request_proto_init() {
	if File_pkg_auth_proto_requests_revoke_token_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_auth_proto_requests_revoke_token_request_proto_rawDesc), len(file_pkg_auth_proto_requests_revoke_token_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_auth_proto_requests_revoke_token_request_proto_goTypes,
		DependencyIndexes: file_pkg_auth_proto_requests_revoke_token_request_proto_depIdxs,
		MessageInfos:      file_pkg_auth_proto_requests_revoke_token_request_proto_msgTypes,
	}.Build()
	File_pkg_auth_proto_requests_revoke_token_request_proto = out.File
	file_pkg_auth_proto_requests_revoke_token_request_proto_goTypes = nil
	file_pkg_auth_proto_requests_revoke_token_request_proto_depIdxs = nil
}
