# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/queue/messages/backup_source.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gcommon/v1/queue/messages/backup_source.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gcommon.v1.queue.messages import encryption_info_pb2 as gcommon_dot_v1_dot_queue_dot_messages_dot_encryption__info__pb2
from gcommon.v1.queue.messages import original_queue_info_pb2 as gcommon_dot_v1_dot_queue_dot_messages_dot_original__queue__info__pb2
from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-gcommon/v1/queue/messages/backup_source.proto\x12\x10gcommon.v1.queue\x1a/gcommon/v1/queue/messages/encryption_info.proto\x1a\x33gcommon/v1/queue/messages/original_queue_info.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x04\n\x0c\x42\x61\x63kupSource\x12\x1b\n\tbackup_id\x18\x01 \x01(\tR\x08\x62\x61\x63kupId\x12\x1f\n\x0b\x62\x61\x63kup_path\x18\x02 \x01(\tR\nbackupPath\x12!\n\x0cstorage_type\x18\x03 \x01(\tR\x0bstorageType\x12Q\n\x0b\x63redentials\x18\x04 \x03(\x0b\x32/.gcommon.v1.queue.BackupSource.CredentialsEntryR\x0b\x63redentials\x12\x45\n\x10\x62\x61\x63kup_timestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0f\x62\x61\x63kupTimestamp\x12J\n\x0eoriginal_queue\x18\x06 \x01(\x0b\x32#.gcommon.v1.queue.OriginalQueueInfoR\roriginalQueue\x12%\n\x0e\x62\x61\x63kup_version\x18\x07 \x01(\tR\rbackupVersion\x12-\n\x12\x63ompression_format\x18\x08 \x01(\tR\x11\x63ompressionFormat\x12@\n\nencryption\x18\t \x01(\x0b\x32 .gcommon.v1.queue.EncryptionInfoR\nencryption\x1a>\n\x10\x43redentialsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42-Z#github.com/jdfalk/gcommon/pkg/queue\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcommon.v1.queue.messages.backup_source_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/jdfalk/gcommon/pkg/queue\222\003\005\322>\002\020\003'
  _globals['_BACKUPSOURCE_CREDENTIALSENTRY']._loaded_options = None
  _globals['_BACKUPSOURCE_CREDENTIALSENTRY']._serialized_options = b'8\001'
  _globals['_BACKUPSOURCE']._serialized_start=238
  _globals['_BACKUPSOURCE']._serialized_end=795
  _globals['_BACKUPSOURCE_CREDENTIALSENTRY']._serialized_start=733
  _globals['_BACKUPSOURCE_CREDENTIALSENTRY']._serialized_end=795
# @@protoc_insertion_point(module_scope)
