// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/config/proto/approval_status.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// ApprovalStatus represents the approval status.
// Specifies the current state of configuration change approval.
type ApprovalStatus int32

const (
	// Unspecified approval status
	ApprovalStatus_APPROVAL_STATUS_UNSPECIFIED ApprovalStatus = 0
	// Approval is pending
	ApprovalStatus_APPROVAL_STATUS_PENDING ApprovalStatus = 1
	// Change has been approved
	ApprovalStatus_APPROVAL_STATUS_APPROVED ApprovalStatus = 2
	// Change has been rejected
	ApprovalStatus_APPROVAL_STATUS_REJECTED ApprovalStatus = 3
	// Approval was cancelled
	ApprovalStatus_APPROVAL_STATUS_CANCELLED ApprovalStatus = 4
	// Approval request expired
	ApprovalStatus_APPROVAL_STATUS_EXPIRED ApprovalStatus = 5
)

// Enum value maps for ApprovalStatus.
var (
	ApprovalStatus_name = map[int32]string{
		0: "APPROVAL_STATUS_UNSPECIFIED",
		1: "APPROVAL_STATUS_PENDING",
		2: "APPROVAL_STATUS_APPROVED",
		3: "APPROVAL_STATUS_REJECTED",
		4: "APPROVAL_STATUS_CANCELLED",
		5: "APPROVAL_STATUS_EXPIRED",
	}
	ApprovalStatus_value = map[string]int32{
		"APPROVAL_STATUS_UNSPECIFIED": 0,
		"APPROVAL_STATUS_PENDING":     1,
		"APPROVAL_STATUS_APPROVED":    2,
		"APPROVAL_STATUS_REJECTED":    3,
		"APPROVAL_STATUS_CANCELLED":   4,
		"APPROVAL_STATUS_EXPIRED":     5,
	}
)

func (x ApprovalStatus) Enum() *ApprovalStatus {
	p := new(ApprovalStatus)
	*p = x
	return p
}

func (x ApprovalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_config_proto_approval_status_proto_enumTypes[0].Descriptor()
}

func (ApprovalStatus) Type() protoreflect.EnumType {
	return &file_pkg_config_proto_approval_status_proto_enumTypes[0]
}

func (x ApprovalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalStatus.Descriptor instead.
func (ApprovalStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_config_proto_approval_status_proto_rawDescGZIP(), []int{0}
}

var File_pkg_config_proto_approval_status_proto protoreflect.FileDescriptor

const file_pkg_config_proto_approval_status_proto_rawDesc = "" +
	"\n" +
	"&pkg/config/proto/approval_status.proto\x12\x11gcommon.v1.config*\xc6\x01\n" +
	"\x0eApprovalStatus\x12\x1f\n" +
	"\x1bAPPROVAL_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17APPROVAL_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18APPROVAL_STATUS_APPROVED\x10\x02\x12\x1c\n" +
	"\x18APPROVAL_STATUS_REJECTED\x10\x03\x12\x1d\n" +
	"\x19APPROVAL_STATUS_CANCELLED\x10\x04\x12\x1b\n" +
	"\x17APPROVAL_STATUS_EXPIRED\x10\x05B\xbe\x01\n" +
	"\x15com.gcommon.v1.configB\x13ApprovalStatusProtoP\x01Z*github.com/jdfalk/gcommon/pkg/config/proto\xa2\x02\x03GVC\xaa\x02\x11Gcommon.V1.Config\xca\x02\x11Gcommon\\V1\\Config\xe2\x02\x1dGcommon\\V1\\Config\\GPBMetadata\xea\x02\x13Gcommon::V1::Configb\beditionsp\xe8\a"

var (
	file_pkg_config_proto_approval_status_proto_rawDescOnce sync.Once
	file_pkg_config_proto_approval_status_proto_rawDescData []byte
)

func file_pkg_config_proto_approval_status_proto_rawDescGZIP() []byte {
	file_pkg_config_proto_approval_status_proto_rawDescOnce.Do(func() {
		file_pkg_config_proto_approval_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_config_proto_approval_status_proto_rawDesc), len(file_pkg_config_proto_approval_status_proto_rawDesc)))
	})
	return file_pkg_config_proto_approval_status_proto_rawDescData
}

var file_pkg_config_proto_approval_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_config_proto_approval_status_proto_goTypes = []any{
	(ApprovalStatus)(0), // 0: gcommon.v1.config.ApprovalStatus
}
var file_pkg_config_proto_approval_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_config_proto_approval_status_proto_init() }
func file_pkg_config_proto_approval_status_proto_init() {
	if File_pkg_config_proto_approval_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_config_proto_approval_status_proto_rawDesc), len(file_pkg_config_proto_approval_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_config_proto_approval_status_proto_goTypes,
		DependencyIndexes: file_pkg_config_proto_approval_status_proto_depIdxs,
		EnumInfos:         file_pkg_config_proto_approval_status_proto_enumTypes,
	}.Build()
	File_pkg_config_proto_approval_status_proto = out.File
	file_pkg_config_proto_approval_status_proto_goTypes = nil
	file_pkg_config_proto_approval_status_proto_depIdxs = nil
}
