// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/config/proto/monitoring_alert.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonitoringAlert struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Condition   *string                `protobuf:"bytes,3,opt,name=condition"`
	xxx_hidden_Threshold   float64                `protobuf:"fixed64,4,opt,name=threshold"`
	xxx_hidden_Enabled     bool                   `protobuf:"varint,5,opt,name=enabled"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MonitoringAlert) Reset() {
	*x = MonitoringAlert{}
	mi := &file_pkg_config_proto_monitoring_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringAlert) ProtoMessage() {}

func (x *MonitoringAlert) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_config_proto_monitoring_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MonitoringAlert) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *MonitoringAlert) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *MonitoringAlert) GetCondition() string {
	if x != nil {
		if x.xxx_hidden_Condition != nil {
			return *x.xxx_hidden_Condition
		}
		return ""
	}
	return ""
}

func (x *MonitoringAlert) GetThreshold() float64 {
	if x != nil {
		return x.xxx_hidden_Threshold
	}
	return 0
}

func (x *MonitoringAlert) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *MonitoringAlert) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *MonitoringAlert) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *MonitoringAlert) SetCondition(v string) {
	x.xxx_hidden_Condition = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *MonitoringAlert) SetThreshold(v float64) {
	x.xxx_hidden_Threshold = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *MonitoringAlert) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *MonitoringAlert) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MonitoringAlert) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MonitoringAlert) HasCondition() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MonitoringAlert) HasThreshold() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *MonitoringAlert) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *MonitoringAlert) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *MonitoringAlert) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *MonitoringAlert) ClearCondition() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Condition = nil
}

func (x *MonitoringAlert) ClearThreshold() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Threshold = 0
}

func (x *MonitoringAlert) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Enabled = false
}

type MonitoringAlert_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Alert ID
	Id *string
	// Alert name
	Name *string
	// Alert condition
	Condition *string
	// Alert threshold
	Threshold *float64
	// Alert enabled status
	Enabled *bool
}

func (b0 MonitoringAlert_builder) Build() *MonitoringAlert {
	m0 := &MonitoringAlert{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Condition != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Condition = b.Condition
	}
	if b.Threshold != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Threshold = *b.Threshold
	}
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	return m0
}

var File_pkg_config_proto_monitoring_alert_proto protoreflect.FileDescriptor

const file_pkg_config_proto_monitoring_alert_proto_rawDesc = "" +
	"\n" +
	"'pkg/config/proto/monitoring_alert.proto\x12\x11gcommon.v1.config\x1a!google/protobuf/go_features.proto\"\x8b\x01\n" +
	"\x0fMonitoringAlert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcondition\x18\x03 \x01(\tR\tcondition\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x01R\tthreshold\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabledB\xc7\x01\n" +
	"\x15com.gcommon.v1.configB\x14MonitoringAlertProtoP\x01Z*github.com/jdfalk/gcommon/pkg/config/proto\xa2\x02\x03GVC\xaa\x02\x11Gcommon.V1.Config\xca\x02\x11Gcommon\\V1\\Config\xe2\x02\x1dGcommon\\V1\\Config\\GPBMetadata\xea\x02\x13Gcommon::V1::Config\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_pkg_config_proto_monitoring_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_config_proto_monitoring_alert_proto_goTypes = []any{
	(*MonitoringAlert)(nil), // 0: gcommon.v1.config.MonitoringAlert
}
var file_pkg_config_proto_monitoring_alert_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_config_proto_monitoring_alert_proto_init() }
func file_pkg_config_proto_monitoring_alert_proto_init() {
	if File_pkg_config_proto_monitoring_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_config_proto_monitoring_alert_proto_rawDesc), len(file_pkg_config_proto_monitoring_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_config_proto_monitoring_alert_proto_goTypes,
		DependencyIndexes: file_pkg_config_proto_monitoring_alert_proto_depIdxs,
		MessageInfos:      file_pkg_config_proto_monitoring_alert_proto_msgTypes,
	}.Build()
	File_pkg_config_proto_monitoring_alert_proto = out.File
	file_pkg_config_proto_monitoring_alert_proto_goTypes = nil
	file_pkg_config_proto_monitoring_alert_proto_depIdxs = nil
}
