// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/config/proto/validation_rule_severity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationRuleSeverity int32

const (
	ValidationRuleSeverity_VALIDATION_RULE_SEVERITY_UNSPECIFIED ValidationRuleSeverity = 0
	ValidationRuleSeverity_VALIDATION_RULE_SEVERITY_INFO        ValidationRuleSeverity = 1
	ValidationRuleSeverity_VALIDATION_RULE_SEVERITY_WARNING     ValidationRuleSeverity = 2
	ValidationRuleSeverity_VALIDATION_RULE_SEVERITY_ERROR       ValidationRuleSeverity = 3
	ValidationRuleSeverity_VALIDATION_RULE_SEVERITY_CRITICAL    ValidationRuleSeverity = 4
)

// Enum value maps for ValidationRuleSeverity.
var (
	ValidationRuleSeverity_name = map[int32]string{
		0: "VALIDATION_RULE_SEVERITY_UNSPECIFIED",
		1: "VALIDATION_RULE_SEVERITY_INFO",
		2: "VALIDATION_RULE_SEVERITY_WARNING",
		3: "VALIDATION_RULE_SEVERITY_ERROR",
		4: "VALIDATION_RULE_SEVERITY_CRITICAL",
	}
	ValidationRuleSeverity_value = map[string]int32{
		"VALIDATION_RULE_SEVERITY_UNSPECIFIED": 0,
		"VALIDATION_RULE_SEVERITY_INFO":        1,
		"VALIDATION_RULE_SEVERITY_WARNING":     2,
		"VALIDATION_RULE_SEVERITY_ERROR":       3,
		"VALIDATION_RULE_SEVERITY_CRITICAL":    4,
	}
)

func (x ValidationRuleSeverity) Enum() *ValidationRuleSeverity {
	p := new(ValidationRuleSeverity)
	*p = x
	return p
}

func (x ValidationRuleSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationRuleSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_config_proto_validation_rule_severity_proto_enumTypes[0].Descriptor()
}

func (ValidationRuleSeverity) Type() protoreflect.EnumType {
	return &file_pkg_config_proto_validation_rule_severity_proto_enumTypes[0]
}

func (x ValidationRuleSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationRuleSeverity.Descriptor instead.
func (ValidationRuleSeverity) EnumDescriptor() ([]byte, []int) {
	return file_pkg_config_proto_validation_rule_severity_proto_rawDescGZIP(), []int{0}
}

var File_pkg_config_proto_validation_rule_severity_proto protoreflect.FileDescriptor

const file_pkg_config_proto_validation_rule_severity_proto_rawDesc = "" +
	"\n" +
	"/pkg/config/proto/validation_rule_severity.proto\x12\x11gcommon.v1.config\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto*\xd6\x01\n" +
	"\x16ValidationRuleSeverity\x12(\n" +
	"$VALIDATION_RULE_SEVERITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dVALIDATION_RULE_SEVERITY_INFO\x10\x01\x12$\n" +
	" VALIDATION_RULE_SEVERITY_WARNING\x10\x02\x12\"\n" +
	"\x1eVALIDATION_RULE_SEVERITY_ERROR\x10\x03\x12%\n" +
	"!VALIDATION_RULE_SEVERITY_CRITICAL\x10\x04B\xc6\x01\n" +
	"\x15com.gcommon.v1.configB\x1bValidationRuleSeverityProtoP\x01Z*github.com/jdfalk/gcommon/pkg/config/proto\xa2\x02\x03GVC\xaa\x02\x11Gcommon.V1.Config\xca\x02\x11Gcommon\\V1\\Config\xe2\x02\x1dGcommon\\V1\\Config\\GPBMetadata\xea\x02\x13Gcommon::V1::Configb\beditionsp\xe8\a"

var (
	file_pkg_config_proto_validation_rule_severity_proto_rawDescOnce sync.Once
	file_pkg_config_proto_validation_rule_severity_proto_rawDescData []byte
)

func file_pkg_config_proto_validation_rule_severity_proto_rawDescGZIP() []byte {
	file_pkg_config_proto_validation_rule_severity_proto_rawDescOnce.Do(func() {
		file_pkg_config_proto_validation_rule_severity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_config_proto_validation_rule_severity_proto_rawDesc), len(file_pkg_config_proto_validation_rule_severity_proto_rawDesc)))
	})
	return file_pkg_config_proto_validation_rule_severity_proto_rawDescData
}

var file_pkg_config_proto_validation_rule_severity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_config_proto_validation_rule_severity_proto_goTypes = []any{
	(ValidationRuleSeverity)(0), // 0: gcommon.v1.config.ValidationRuleSeverity
}
var file_pkg_config_proto_validation_rule_severity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_config_proto_validation_rule_severity_proto_init() }
func file_pkg_config_proto_validation_rule_severity_proto_init() {
	if File_pkg_config_proto_validation_rule_severity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_config_proto_validation_rule_severity_proto_rawDesc), len(file_pkg_config_proto_validation_rule_severity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_config_proto_validation_rule_severity_proto_goTypes,
		DependencyIndexes: file_pkg_config_proto_validation_rule_severity_proto_depIdxs,
		EnumInfos:         file_pkg_config_proto_validation_rule_severity_proto_enumTypes,
	}.Build()
	File_pkg_config_proto_validation_rule_severity_proto = out.File
	file_pkg_config_proto_validation_rule_severity_proto_goTypes = nil
	file_pkg_config_proto_validation_rule_severity_proto_depIdxs = nil
}
