// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/config/proto/version_artifact.proto

package proto

import (
	_ "github.com/jdfalk/gcommon/pkg/common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionArtifact struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Type        *string                `protobuf:"bytes,2,opt,name=type"`
	xxx_hidden_Path        *string                `protobuf:"bytes,3,opt,name=path"`
	xxx_hidden_Size        int64                  `protobuf:"varint,4,opt,name=size"`
	xxx_hidden_Checksum    *string                `protobuf:"bytes,5,opt,name=checksum"`
	xxx_hidden_Metadata    map[string]string      `protobuf:"bytes,6,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Timestamp   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VersionArtifact) Reset() {
	*x = VersionArtifact{}
	mi := &file_pkg_config_proto_version_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionArtifact) ProtoMessage() {}

func (x *VersionArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_config_proto_version_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VersionArtifact) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *VersionArtifact) GetType() string {
	if x != nil {
		if x.xxx_hidden_Type != nil {
			return *x.xxx_hidden_Type
		}
		return ""
	}
	return ""
}

func (x *VersionArtifact) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *VersionArtifact) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *VersionArtifact) GetChecksum() string {
	if x != nil {
		if x.xxx_hidden_Checksum != nil {
			return *x.xxx_hidden_Checksum
		}
		return ""
	}
	return ""
}

func (x *VersionArtifact) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *VersionArtifact) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *VersionArtifact) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *VersionArtifact) SetType(v string) {
	x.xxx_hidden_Type = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *VersionArtifact) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *VersionArtifact) SetSize(v int64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *VersionArtifact) SetChecksum(v string) {
	x.xxx_hidden_Checksum = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *VersionArtifact) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *VersionArtifact) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *VersionArtifact) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *VersionArtifact) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *VersionArtifact) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *VersionArtifact) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *VersionArtifact) HasChecksum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *VersionArtifact) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *VersionArtifact) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *VersionArtifact) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = nil
}

func (x *VersionArtifact) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Path = nil
}

func (x *VersionArtifact) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Size = 0
}

func (x *VersionArtifact) ClearChecksum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Checksum = nil
}

func (x *VersionArtifact) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

type VersionArtifact_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Artifact name
	Name *string
	// Artifact type
	Type *string
	// Artifact path
	Path *string
	// Artifact size
	Size *int64
	// Artifact checksum
	Checksum *string
	// Artifact metadata
	Metadata map[string]string
	// Artifact timestamp
	Timestamp *timestamppb.Timestamp
}

func (b0 VersionArtifact_builder) Build() *VersionArtifact {
	m0 := &VersionArtifact{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Name = b.Name
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Type = b.Type
	}
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Path = b.Path
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Size = *b.Size
	}
	if b.Checksum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Checksum = b.Checksum
	}
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Timestamp = b.Timestamp
	return m0
}

var File_pkg_config_proto_version_artifact_proto protoreflect.FileDescriptor

const file_pkg_config_proto_version_artifact_proto_rawDesc = "" +
	"\n" +
	"'pkg/config/proto/version_artifact.proto\x12\x11gcommon.v1.config\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a pkg/common/proto/audit_log.proto\"\xc2\x02\n" +
	"\x0fVersionArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12L\n" +
	"\bmetadata\x18\x06 \x03(\v20.gcommon.v1.config.VersionArtifact.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xc7\x01\n" +
	"\x15com.gcommon.v1.configB\x14VersionArtifactProtoP\x01Z*github.com/jdfalk/gcommon/pkg/config/proto\xa2\x02\x03GVC\xaa\x02\x11Gcommon.V1.Config\xca\x02\x11Gcommon\\V1\\Config\xe2\x02\x1dGcommon\\V1\\Config\\GPBMetadata\xea\x02\x13Gcommon::V1::Config\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_pkg_config_proto_version_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_config_proto_version_artifact_proto_goTypes = []any{
	(*VersionArtifact)(nil),       // 0: gcommon.v1.config.VersionArtifact
	nil,                           // 1: gcommon.v1.config.VersionArtifact.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_config_proto_version_artifact_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.config.VersionArtifact.metadata:type_name -> gcommon.v1.config.VersionArtifact.MetadataEntry
	2, // 1: gcommon.v1.config.VersionArtifact.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_config_proto_version_artifact_proto_init() }
func file_pkg_config_proto_version_artifact_proto_init() {
	if File_pkg_config_proto_version_artifact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_config_proto_version_artifact_proto_rawDesc), len(file_pkg_config_proto_version_artifact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_config_proto_version_artifact_proto_goTypes,
		DependencyIndexes: file_pkg_config_proto_version_artifact_proto_depIdxs,
		MessageInfos:      file_pkg_config_proto_version_artifact_proto_msgTypes,
	}.Build()
	File_pkg_config_proto_version_artifact_proto = out.File
	file_pkg_config_proto_version_artifact_proto_goTypes = nil
	file_pkg_config_proto_version_artifact_proto_depIdxs = nil
}
