// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gcommon/v1/queue/messages/delivery_retry_config.proto

package queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryRetryConfig struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled           bool                   `protobuf:"varint,1,opt,name=enabled"`
	xxx_hidden_MaxRetries        int32                  `protobuf:"varint,2,opt,name=max_retries,json=maxRetries"`
	xxx_hidden_InitialDelayMs    int32                  `protobuf:"varint,3,opt,name=initial_delay_ms,json=initialDelayMs"`
	xxx_hidden_MaxDelayMs        int32                  `protobuf:"varint,4,opt,name=max_delay_ms,json=maxDelayMs"`
	xxx_hidden_BackoffMultiplier float64                `protobuf:"fixed64,5,opt,name=backoff_multiplier,json=backoffMultiplier"`
	xxx_hidden_RetryErrorCodes   []string               `protobuf:"bytes,6,rep,name=retry_error_codes,json=retryErrorCodes"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DeliveryRetryConfig) Reset() {
	*x = DeliveryRetryConfig{}
	mi := &file_gcommon_v1_queue_messages_delivery_retry_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryRetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryRetryConfig) ProtoMessage() {}

func (x *DeliveryRetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_queue_messages_delivery_retry_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeliveryRetryConfig) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *DeliveryRetryConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.xxx_hidden_MaxRetries
	}
	return 0
}

func (x *DeliveryRetryConfig) GetInitialDelayMs() int32 {
	if x != nil {
		return x.xxx_hidden_InitialDelayMs
	}
	return 0
}

func (x *DeliveryRetryConfig) GetMaxDelayMs() int32 {
	if x != nil {
		return x.xxx_hidden_MaxDelayMs
	}
	return 0
}

func (x *DeliveryRetryConfig) GetBackoffMultiplier() float64 {
	if x != nil {
		return x.xxx_hidden_BackoffMultiplier
	}
	return 0
}

func (x *DeliveryRetryConfig) GetRetryErrorCodes() []string {
	if x != nil {
		return x.xxx_hidden_RetryErrorCodes
	}
	return nil
}

func (x *DeliveryRetryConfig) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *DeliveryRetryConfig) SetMaxRetries(v int32) {
	x.xxx_hidden_MaxRetries = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *DeliveryRetryConfig) SetInitialDelayMs(v int32) {
	x.xxx_hidden_InitialDelayMs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *DeliveryRetryConfig) SetMaxDelayMs(v int32) {
	x.xxx_hidden_MaxDelayMs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *DeliveryRetryConfig) SetBackoffMultiplier(v float64) {
	x.xxx_hidden_BackoffMultiplier = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *DeliveryRetryConfig) SetRetryErrorCodes(v []string) {
	x.xxx_hidden_RetryErrorCodes = v
}

func (x *DeliveryRetryConfig) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeliveryRetryConfig) HasMaxRetries() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeliveryRetryConfig) HasInitialDelayMs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DeliveryRetryConfig) HasMaxDelayMs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DeliveryRetryConfig) HasBackoffMultiplier() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *DeliveryRetryConfig) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Enabled = false
}

func (x *DeliveryRetryConfig) ClearMaxRetries() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MaxRetries = 0
}

func (x *DeliveryRetryConfig) ClearInitialDelayMs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_InitialDelayMs = 0
}

func (x *DeliveryRetryConfig) ClearMaxDelayMs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MaxDelayMs = 0
}

func (x *DeliveryRetryConfig) ClearBackoffMultiplier() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_BackoffMultiplier = 0
}

type DeliveryRetryConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Enable retry on delivery failures
	Enabled *bool
	// Maximum retry attempts
	MaxRetries *int32
	// Initial retry delay (milliseconds)
	InitialDelayMs *int32
	// Maximum retry delay (milliseconds)
	MaxDelayMs *int32
	// Backoff multiplier
	BackoffMultiplier *float64
	// Retry only for specific error codes
	RetryErrorCodes []string
}

func (b0 DeliveryRetryConfig_builder) Build() *DeliveryRetryConfig {
	m0 := &DeliveryRetryConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.MaxRetries != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_MaxRetries = *b.MaxRetries
	}
	if b.InitialDelayMs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_InitialDelayMs = *b.InitialDelayMs
	}
	if b.MaxDelayMs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_MaxDelayMs = *b.MaxDelayMs
	}
	if b.BackoffMultiplier != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_BackoffMultiplier = *b.BackoffMultiplier
	}
	x.xxx_hidden_RetryErrorCodes = b.RetryErrorCodes
	return m0
}

var File_gcommon_v1_queue_messages_delivery_retry_config_proto protoreflect.FileDescriptor

const file_gcommon_v1_queue_messages_delivery_retry_config_proto_rawDesc = "" +
	"\n" +
	"5gcommon/v1/queue/messages/delivery_retry_config.proto\x12\x10gcommon.v1.queue\x1a!google/protobuf/go_features.proto\"\xf7\x01\n" +
	"\x13DeliveryRetryConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vmax_retries\x18\x02 \x01(\x05R\n" +
	"maxRetries\x12(\n" +
	"\x10initial_delay_ms\x18\x03 \x01(\x05R\x0einitialDelayMs\x12 \n" +
	"\fmax_delay_ms\x18\x04 \x01(\x05R\n" +
	"maxDelayMs\x12-\n" +
	"\x12backoff_multiplier\x18\x05 \x01(\x01R\x11backoffMultiplier\x12*\n" +
	"\x11retry_error_codes\x18\x06 \x03(\tR\x0fretryErrorCodesB1Z'github.com/jdfalk/gcommon/sdks/go/queue\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_queue_messages_delivery_retry_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gcommon_v1_queue_messages_delivery_retry_config_proto_goTypes = []any{
	(*DeliveryRetryConfig)(nil), // 0: gcommon.v1.queue.DeliveryRetryConfig
}
var file_gcommon_v1_queue_messages_delivery_retry_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gcommon_v1_queue_messages_delivery_retry_config_proto_init() }
func file_gcommon_v1_queue_messages_delivery_retry_config_proto_init() {
	if File_gcommon_v1_queue_messages_delivery_retry_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_queue_messages_delivery_retry_config_proto_rawDesc), len(file_gcommon_v1_queue_messages_delivery_retry_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_queue_messages_delivery_retry_config_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_queue_messages_delivery_retry_config_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_queue_messages_delivery_retry_config_proto_msgTypes,
	}.Build()
	File_gcommon_v1_queue_messages_delivery_retry_config_proto = out.File
	file_gcommon_v1_queue_messages_delivery_retry_config_proto_goTypes = nil
	file_gcommon_v1_queue_messages_delivery_retry_config_proto_depIdxs = nil
}
