// file: proto/gcommon/v2/config/api/reload_config_request.proto
// version: 1.0.1
// guid: 5d1ecbb6-f500-42a2-85a1-ee831ecb1936
// file: proto/gcommon/v2/config/reload_config_request.proto
//
// Request definitions for config module
// Generated as part of protobuf implementation
//

edition = "2023";

package config.v2;

import "buf/validate/validate.proto";
import "commonpb/v2/request_metadata.proto";
import "google/protobuf/go_features.proto";

option features.(pb.go).api_level = API_OPAQUE;
option go_package = "github.com/falkcorp/gcommon/v2/pkg/configpb/v2";

message ReloadConfigRequest {
  // Namespace to reload
  string namespace = 1 [(buf.validate.field).string.min_len = 1];

  // Request metadata
  common.v2.RequestMetadata metadata = 2;
}
