// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: gcommon/v1/config/health_status.proto

package config

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/jdfalk/gcommon/sdks/go/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigHealthStatus struct {
	state                   protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Overall      common.HealthState            `protobuf:"varint,1,opt,name=overall,enum=gcommon.v1.common.HealthState"`
	xxx_hidden_Components   map[string]common.HealthState `protobuf:"bytes,2,rep,name=components" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=gcommon.v1.common.HealthState"`
	xxx_hidden_HealthChecks *[]*ConfigHealthCheckResult   `protobuf:"bytes,3,rep,name=health_checks,json=healthChecks"`
	xxx_hidden_LastCheck    *timestamppb.Timestamp        `protobuf:"bytes,4,opt,name=last_check,json=lastCheck"`
	xxx_hidden_Metrics      map[string]float64            `protobuf:"bytes,5,rep,name=metrics" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConfigHealthStatus) Reset() {
	*x = ConfigHealthStatus{}
	mi := &file_gcommon_v1_config_health_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigHealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigHealthStatus) ProtoMessage() {}

func (x *ConfigHealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_config_health_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigHealthStatus) GetOverall() common.HealthState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Overall
		}
	}
	return common.HealthState(0)
}

func (x *ConfigHealthStatus) GetComponents() map[string]common.HealthState {
	if x != nil {
		return x.xxx_hidden_Components
	}
	return nil
}

func (x *ConfigHealthStatus) GetHealthChecks() []*ConfigHealthCheckResult {
	if x != nil {
		if x.xxx_hidden_HealthChecks != nil {
			return *x.xxx_hidden_HealthChecks
		}
	}
	return nil
}

func (x *ConfigHealthStatus) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastCheck
	}
	return nil
}

func (x *ConfigHealthStatus) GetMetrics() map[string]float64 {
	if x != nil {
		return x.xxx_hidden_Metrics
	}
	return nil
}

func (x *ConfigHealthStatus) SetOverall(v common.HealthState) {
	x.xxx_hidden_Overall = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *ConfigHealthStatus) SetComponents(v map[string]common.HealthState) {
	x.xxx_hidden_Components = v
}

func (x *ConfigHealthStatus) SetHealthChecks(v []*ConfigHealthCheckResult) {
	x.xxx_hidden_HealthChecks = &v
}

func (x *ConfigHealthStatus) SetLastCheck(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastCheck = v
}

func (x *ConfigHealthStatus) SetMetrics(v map[string]float64) {
	x.xxx_hidden_Metrics = v
}

func (x *ConfigHealthStatus) HasOverall() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigHealthStatus) HasLastCheck() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastCheck != nil
}

func (x *ConfigHealthStatus) ClearOverall() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Overall = common.HealthState_HEALTH_STATE_UNSPECIFIED
}

func (x *ConfigHealthStatus) ClearLastCheck() {
	x.xxx_hidden_LastCheck = nil
}

type ConfigHealthStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Overall health
	Overall *common.HealthState
	// Component health
	Components map[string]common.HealthState
	// Health checks
	HealthChecks []*ConfigHealthCheckResult
	// Last health check
	LastCheck *timestamppb.Timestamp
	// Health metrics
	Metrics map[string]float64
}

func (b0 ConfigHealthStatus_builder) Build() *ConfigHealthStatus {
	m0 := &ConfigHealthStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Overall != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Overall = *b.Overall
	}
	x.xxx_hidden_Components = b.Components
	x.xxx_hidden_HealthChecks = &b.HealthChecks
	x.xxx_hidden_LastCheck = b.LastCheck
	x.xxx_hidden_Metrics = b.Metrics
	return m0
}

var File_gcommon_v1_config_health_status_proto protoreflect.FileDescriptor

const file_gcommon_v1_config_health_status_proto_rawDesc = "" +
	"\n" +
	"%gcommon/v1/config/health_status.proto\x12\x11gcommon.v1.config\x1a$gcommon/v1/common/health_state.proto\x1a+gcommon/v1/config/health_check_result.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xa4\x04\n" +
	"\x12ConfigHealthStatus\x128\n" +
	"\aoverall\x18\x01 \x01(\x0e2\x1e.gcommon.v1.common.HealthStateR\aoverall\x12U\n" +
	"\n" +
	"components\x18\x02 \x03(\v25.gcommon.v1.config.ConfigHealthStatus.ComponentsEntryR\n" +
	"components\x12Y\n" +
	"\rhealth_checks\x18\x03 \x03(\v2*.gcommon.v1.config.ConfigHealthCheckResultB\b\xbaH\x05\x92\x01\x02\b\x01R\fhealthChecks\x129\n" +
	"\n" +
	"last_check\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\x12L\n" +
	"\ametrics\x18\x05 \x03(\v22.gcommon.v1.config.ConfigHealthStatus.MetricsEntryR\ametrics\x1a]\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\x0e2\x1e.gcommon.v1.common.HealthStateR\x05value:\x028\x01\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B5Z+github.com/jdfalk/gcommon/sdks/go/v1/config\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_config_health_status_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gcommon_v1_config_health_status_proto_goTypes = []any{
	(*ConfigHealthStatus)(nil),      // 0: gcommon.v1.config.ConfigHealthStatus
	nil,                             // 1: gcommon.v1.config.ConfigHealthStatus.ComponentsEntry
	nil,                             // 2: gcommon.v1.config.ConfigHealthStatus.MetricsEntry
	(common.HealthState)(0),         // 3: gcommon.v1.common.HealthState
	(*ConfigHealthCheckResult)(nil), // 4: gcommon.v1.config.ConfigHealthCheckResult
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_gcommon_v1_config_health_status_proto_depIdxs = []int32{
	3, // 0: gcommon.v1.config.ConfigHealthStatus.overall:type_name -> gcommon.v1.common.HealthState
	1, // 1: gcommon.v1.config.ConfigHealthStatus.components:type_name -> gcommon.v1.config.ConfigHealthStatus.ComponentsEntry
	4, // 2: gcommon.v1.config.ConfigHealthStatus.health_checks:type_name -> gcommon.v1.config.ConfigHealthCheckResult
	5, // 3: gcommon.v1.config.ConfigHealthStatus.last_check:type_name -> google.protobuf.Timestamp
	2, // 4: gcommon.v1.config.ConfigHealthStatus.metrics:type_name -> gcommon.v1.config.ConfigHealthStatus.MetricsEntry
	3, // 5: gcommon.v1.config.ConfigHealthStatus.ComponentsEntry.value:type_name -> gcommon.v1.common.HealthState
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gcommon_v1_config_health_status_proto_init() }
func file_gcommon_v1_config_health_status_proto_init() {
	if File_gcommon_v1_config_health_status_proto != nil {
		return
	}
	file_gcommon_v1_config_health_check_result_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_config_health_status_proto_rawDesc), len(file_gcommon_v1_config_health_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_config_health_status_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_config_health_status_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_config_health_status_proto_msgTypes,
	}.Build()
	File_gcommon_v1_config_health_status_proto = out.File
	file_gcommon_v1_config_health_status_proto_goTypes = nil
	file_gcommon_v1_config_health_status_proto_depIdxs = nil
}
