// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gcommon/v1/config/value_history_entry.proto

package config

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/jdfalk/gcommon/sdks/go/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueHistoryEntry struct {
	state                    protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_EntryId       *string                   `protobuf:"bytes,1,opt,name=entry_id,json=entryId"`
	xxx_hidden_PreviousValue *string                   `protobuf:"bytes,2,opt,name=previous_value,json=previousValue"`
	xxx_hidden_NewValue      *string                   `protobuf:"bytes,3,opt,name=new_value,json=newValue"`
	xxx_hidden_Timestamp     *timestamppb.Timestamp    `protobuf:"bytes,4,opt,name=timestamp"`
	xxx_hidden_ChangedBy     *string                   `protobuf:"bytes,5,opt,name=changed_by,json=changedBy"`
	xxx_hidden_Reason        *string                   `protobuf:"bytes,6,opt,name=reason"`
	xxx_hidden_ChangeType    common.TemplateChangeType `protobuf:"varint,7,opt,name=change_type,json=changeType,enum=gcommon.v1.common.TemplateChangeType"`
	xxx_hidden_Metadata      map[string]string         `protobuf:"bytes,8,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ValueHistoryEntry) Reset() {
	*x = ValueHistoryEntry{}
	mi := &file_gcommon_v1_config_value_history_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueHistoryEntry) ProtoMessage() {}

func (x *ValueHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_config_value_history_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValueHistoryEntry) GetEntryId() string {
	if x != nil {
		if x.xxx_hidden_EntryId != nil {
			return *x.xxx_hidden_EntryId
		}
		return ""
	}
	return ""
}

func (x *ValueHistoryEntry) GetPreviousValue() string {
	if x != nil {
		if x.xxx_hidden_PreviousValue != nil {
			return *x.xxx_hidden_PreviousValue
		}
		return ""
	}
	return ""
}

func (x *ValueHistoryEntry) GetNewValue() string {
	if x != nil {
		if x.xxx_hidden_NewValue != nil {
			return *x.xxx_hidden_NewValue
		}
		return ""
	}
	return ""
}

func (x *ValueHistoryEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *ValueHistoryEntry) GetChangedBy() string {
	if x != nil {
		if x.xxx_hidden_ChangedBy != nil {
			return *x.xxx_hidden_ChangedBy
		}
		return ""
	}
	return ""
}

func (x *ValueHistoryEntry) GetReason() string {
	if x != nil {
		if x.xxx_hidden_Reason != nil {
			return *x.xxx_hidden_Reason
		}
		return ""
	}
	return ""
}

func (x *ValueHistoryEntry) GetChangeType() common.TemplateChangeType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 6) {
			return x.xxx_hidden_ChangeType
		}
	}
	return common.TemplateChangeType(0)
}

func (x *ValueHistoryEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ValueHistoryEntry) SetEntryId(v string) {
	x.xxx_hidden_EntryId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *ValueHistoryEntry) SetPreviousValue(v string) {
	x.xxx_hidden_PreviousValue = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *ValueHistoryEntry) SetNewValue(v string) {
	x.xxx_hidden_NewValue = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *ValueHistoryEntry) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *ValueHistoryEntry) SetChangedBy(v string) {
	x.xxx_hidden_ChangedBy = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *ValueHistoryEntry) SetReason(v string) {
	x.xxx_hidden_Reason = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *ValueHistoryEntry) SetChangeType(v common.TemplateChangeType) {
	x.xxx_hidden_ChangeType = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *ValueHistoryEntry) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *ValueHistoryEntry) HasEntryId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ValueHistoryEntry) HasPreviousValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ValueHistoryEntry) HasNewValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ValueHistoryEntry) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *ValueHistoryEntry) HasChangedBy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ValueHistoryEntry) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ValueHistoryEntry) HasChangeType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ValueHistoryEntry) ClearEntryId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EntryId = nil
}

func (x *ValueHistoryEntry) ClearPreviousValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PreviousValue = nil
}

func (x *ValueHistoryEntry) ClearNewValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_NewValue = nil
}

func (x *ValueHistoryEntry) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *ValueHistoryEntry) ClearChangedBy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ChangedBy = nil
}

func (x *ValueHistoryEntry) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Reason = nil
}

func (x *ValueHistoryEntry) ClearChangeType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ChangeType = common.TemplateChangeType_TEMPLATE_CHANGE_TYPE_UNSPECIFIED
}

type ValueHistoryEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Entry ID
	EntryId *string
	// Previous value
	PreviousValue *string
	// New value
	NewValue *string
	// Change timestamp
	Timestamp *timestamppb.Timestamp
	// User who made the change
	ChangedBy *string
	// Change reason
	Reason *string
	// Change type (using ChangeType from config_template.proto)
	ChangeType *common.TemplateChangeType
	// Change metadata
	Metadata map[string]string
}

func (b0 ValueHistoryEntry_builder) Build() *ValueHistoryEntry {
	m0 := &ValueHistoryEntry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EntryId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_EntryId = b.EntryId
	}
	if b.PreviousValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_PreviousValue = b.PreviousValue
	}
	if b.NewValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_NewValue = b.NewValue
	}
	x.xxx_hidden_Timestamp = b.Timestamp
	if b.ChangedBy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_ChangedBy = b.ChangedBy
	}
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Reason = b.Reason
	}
	if b.ChangeType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_ChangeType = *b.ChangeType
	}
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

var File_gcommon_v1_config_value_history_entry_proto protoreflect.FileDescriptor

const file_gcommon_v1_config_value_history_entry_proto_rawDesc = "" +
	"\n" +
	"+gcommon/v1/config/value_history_entry.proto\x12\x11gcommon.v1.config\x1a*gcommon/v1/common/config_change_type.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xe5\x03\n" +
	"\x11ValueHistoryEntry\x12\"\n" +
	"\bentry_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aentryId\x12.\n" +
	"\x0eprevious_value\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\rpreviousValue\x12$\n" +
	"\tnew_value\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bnewValue\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12&\n" +
	"\n" +
	"changed_by\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tchangedBy\x12\x1f\n" +
	"\x06reason\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06reason\x12F\n" +
	"\vchange_type\x18\a \x01(\x0e2%.gcommon.v1.common.TemplateChangeTypeR\n" +
	"changeType\x12N\n" +
	"\bmetadata\x18\b \x03(\v22.gcommon.v1.config.ValueHistoryEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B5Z+github.com/jdfalk/gcommon/sdks/go/v1/config\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_config_value_history_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gcommon_v1_config_value_history_entry_proto_goTypes = []any{
	(*ValueHistoryEntry)(nil),      // 0: gcommon.v1.config.ValueHistoryEntry
	nil,                            // 1: gcommon.v1.config.ValueHistoryEntry.MetadataEntry
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
	(common.TemplateChangeType)(0), // 3: gcommon.v1.common.TemplateChangeType
}
var file_gcommon_v1_config_value_history_entry_proto_depIdxs = []int32{
	2, // 0: gcommon.v1.config.ValueHistoryEntry.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: gcommon.v1.config.ValueHistoryEntry.change_type:type_name -> gcommon.v1.common.TemplateChangeType
	1, // 2: gcommon.v1.config.ValueHistoryEntry.metadata:type_name -> gcommon.v1.config.ValueHistoryEntry.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gcommon_v1_config_value_history_entry_proto_init() }
func file_gcommon_v1_config_value_history_entry_proto_init() {
	if File_gcommon_v1_config_value_history_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_config_value_history_entry_proto_rawDesc), len(file_gcommon_v1_config_value_history_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_config_value_history_entry_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_config_value_history_entry_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_config_value_history_entry_proto_msgTypes,
	}.Build()
	File_gcommon_v1_config_value_history_entry_proto = out.File
	file_gcommon_v1_config_value_history_entry_proto_goTypes = nil
	file_gcommon_v1_config_value_history_entry_proto_depIdxs = nil
}
