# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pkg/auth/proto/list_user_sessions_response.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'pkg/auth/proto/list_user_sessions_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from pkg.auth.proto import session_info_pb2 as pkg_dot_auth_dot_proto_dot_session__info__pb2
from pkg.common.proto import error_pb2 as pkg_dot_common_dot_proto_dot_error__pb2
from pkg.common.proto import paginated_response_pb2 as pkg_dot_common_dot_proto_dot_paginated__response__pb2
from pkg.common.proto import request_metadata_pb2 as pkg_dot_common_dot_proto_dot_request__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0pkg/auth/proto/list_user_sessions_response.proto\x12\x0fgcommon.v1.auth\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!pkg/auth/proto/session_info.proto\x1a\x1cpkg/common/proto/error.proto\x1a)pkg/common/proto/paginated_response.proto\x1a\'pkg/common/proto/request_metadata.proto\"\xc6\x04\n\x18ListUserSessionsResponse\x12\x38\n\x08sessions\x18\x01 \x03(\x0b\x32\x1c.gcommon.v1.auth.SessionInfoR\x08sessions\x12\x1f\n\x0btotal_count\x18\x02 \x01(\x05R\ntotalCount\x12\x44\n\npagination\x18\x0b \x01(\x0b\x32$.gcommon.v1.common.PaginatedResponseR\npagination\x12M\n\x10request_metadata\x18\x0c \x01(\x0b\x32\".gcommon.v1.common.RequestMetadataR\x0frequestMetadata\x12\x38\n\x18includes_current_session\x18\r \x01(\x08R\x16includesCurrentSession\x12\x30\n\x14\x61\x63tive_session_count\x18\x0e \x01(\x05R\x12\x61\x63tiveSessionCount\x12\x17\n\x07user_id\x18\x0f \x01(\tR\x06userId\x12.\n\x05\x65rror\x18= \x01(\x0b\x32\x18.gcommon.v1.common.ErrorR\x05\x65rror\x12=\n\x0cgenerated_at\x18\x33 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bgeneratedAt\x12\x46\n\x11\x64\x61ta_refreshed_at\x18\x34 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0f\x64\x61taRefreshedAtB\xc4\x01\n\x13\x63om.gcommon.v1.authB\x1dListUserSessionsResponseProtoP\x01Z(github.com/jdfalk/gcommon/pkg/auth/proto\xa2\x02\x03GVA\xaa\x02\x0fGcommon.V1.Auth\xca\x02\x0fGcommon\\V1\\Auth\xe2\x02\x1bGcommon\\V1\\Auth\\GPBMetadata\xea\x02\x11Gcommon::V1::Auth\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.auth.proto.list_user_sessions_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.gcommon.v1.authB\035ListUserSessionsResponseProtoP\001Z(github.com/jdfalk/gcommon/pkg/auth/proto\242\002\003GVA\252\002\017Gcommon.V1.Auth\312\002\017Gcommon\\V1\\Auth\342\002\033Gcommon\\V1\\Auth\\GPBMetadata\352\002\021Gcommon::V1::Auth\222\003\005\322>\002\020\003'
  _globals['_LISTUSERSESSIONSRESPONSE']._serialized_start=287
  _globals['_LISTUSERSESSIONSRESPONSE']._serialized_end=869
# @@protoc_insertion_point(module_scope)
