// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/organization/proto/requests/get_hierarchy_request.proto

//go:build !protoopaque

package organizationpb

import (
	proto "../../../../pkg/common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHierarchyRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Request metadata for tracing and context
	Metadata *proto.RequestMetadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	// Organization identifier
	OrganizationId *string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
	// Hierarchy identifier
	HierarchyId   *string `protobuf:"bytes,3,opt,name=hierarchy_id,json=hierarchyId" json:"hierarchy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHierarchyRequest) Reset() {
	*x = GetHierarchyRequest{}
	mi := &file_pkg_organization_proto_requests_get_hierarchy_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHierarchyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHierarchyRequest) ProtoMessage() {}

func (x *GetHierarchyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_organization_proto_requests_get_hierarchy_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetHierarchyRequest) GetMetadata() *proto.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetHierarchyRequest) GetOrganizationId() string {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return ""
}

func (x *GetHierarchyRequest) GetHierarchyId() string {
	if x != nil && x.HierarchyId != nil {
		return *x.HierarchyId
	}
	return ""
}

func (x *GetHierarchyRequest) SetMetadata(v *proto.RequestMetadata) {
	x.Metadata = v
}

func (x *GetHierarchyRequest) SetOrganizationId(v string) {
	x.OrganizationId = &v
}

func (x *GetHierarchyRequest) SetHierarchyId(v string) {
	x.HierarchyId = &v
}

func (x *GetHierarchyRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *GetHierarchyRequest) HasOrganizationId() bool {
	if x == nil {
		return false
	}
	return x.OrganizationId != nil
}

func (x *GetHierarchyRequest) HasHierarchyId() bool {
	if x == nil {
		return false
	}
	return x.HierarchyId != nil
}

func (x *GetHierarchyRequest) ClearMetadata() {
	x.Metadata = nil
}

func (x *GetHierarchyRequest) ClearOrganizationId() {
	x.OrganizationId = nil
}

func (x *GetHierarchyRequest) ClearHierarchyId() {
	x.HierarchyId = nil
}

type GetHierarchyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Request metadata for tracing and context
	Metadata *proto.RequestMetadata
	// Organization identifier
	OrganizationId *string
	// Hierarchy identifier
	HierarchyId *string
}

func (b0 GetHierarchyRequest_builder) Build() *GetHierarchyRequest {
	m0 := &GetHierarchyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Metadata = b.Metadata
	x.OrganizationId = b.OrganizationId
	x.HierarchyId = b.HierarchyId
	return m0
}

var File_pkg_organization_proto_requests_get_hierarchy_request_proto protoreflect.FileDescriptor

const file_pkg_organization_proto_requests_get_hierarchy_request_proto_rawDesc = "" +
	"\n" +
	";pkg/organization/proto/requests/get_hierarchy_request.proto\x12\x17gcommon.v1.organization\x1a!google/protobuf/go_features.proto\x1a0pkg/common/proto/messages/request_metadata.proto\"\xa1\x01\n" +
	"\x13GetHierarchyRequest\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".gcommon.v1.common.RequestMetadataR\bmetadata\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fhierarchy_id\x18\x03 \x01(\tR\vhierarchyIdB\xf0\x01\n" +
	"\x1bcom.gcommon.v1.organizationB\x18GetHierarchyRequestProtoP\x01Z1../../../../pkg/organization/proto;organizationpb\xa2\x02\x03GVO\xaa\x02\x17Gcommon.V1.Organization\xca\x02\x17Gcommon\\V1\\Organization\xe2\x02#Gcommon\\V1\\Organization\\GPBMetadata\xea\x02\x19Gcommon::V1::Organization\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_pkg_organization_proto_requests_get_hierarchy_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_organization_proto_requests_get_hierarchy_request_proto_goTypes = []any{
	(*GetHierarchyRequest)(nil),   // 0: gcommon.v1.organization.GetHierarchyRequest
	(*proto.RequestMetadata)(nil), // 1: gcommon.v1.common.RequestMetadata
}
var file_pkg_organization_proto_requests_get_hierarchy_request_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.organization.GetHierarchyRequest.metadata:type_name -> gcommon.v1.common.RequestMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_organization_proto_requests_get_hierarchy_request_proto_init() }
func file_pkg_organization_proto_requests_get_hierarchy_request_proto_init() {
	if File_pkg_organization_proto_requests_get_hierarchy_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_organization_proto_requests_get_hierarchy_request_proto_rawDesc), len(file_pkg_organization_proto_requests_get_hierarchy_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_organization_proto_requests_get_hierarchy_request_proto_goTypes,
		DependencyIndexes: file_pkg_organization_proto_requests_get_hierarchy_request_proto_depIdxs,
		MessageInfos:      file_pkg_organization_proto_requests_get_hierarchy_request_proto_msgTypes,
	}.Build()
	File_pkg_organization_proto_requests_get_hierarchy_request_proto = out.File
	file_pkg_organization_proto_requests_get_hierarchy_request_proto_goTypes = nil
	file_pkg_organization_proto_requests_get_hierarchy_request_proto_depIdxs = nil
}
