// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/organization/proto/requests/update_organization_settings_request.proto

//go:build !protoopaque

package organizationpb

import (
	proto "../../../../pkg/common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateOrganizationSettingsRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Request metadata for tracing and context
	Metadata *proto.RequestMetadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	// Organization identifier
	OrganizationId *string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
	// Updated settings
	Settings *OrganizationSettings `protobuf:"bytes,3,opt,name=settings" json:"settings,omitempty"`
	// Fields to update
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
	// Validate only without persisting if true
	ValidateOnly  *bool `protobuf:"varint,5,opt,name=validate_only,json=validateOnly" json:"validate_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationSettingsRequest) Reset() {
	*x = UpdateOrganizationSettingsRequest{}
	mi := &file_pkg_organization_proto_requests_update_organization_settings_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationSettingsRequest) ProtoMessage() {}

func (x *UpdateOrganizationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_organization_proto_requests_update_organization_settings_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateOrganizationSettingsRequest) GetMetadata() *proto.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateOrganizationSettingsRequest) GetOrganizationId() string {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return ""
}

func (x *UpdateOrganizationSettingsRequest) GetSettings() *OrganizationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *UpdateOrganizationSettingsRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateOrganizationSettingsRequest) GetValidateOnly() bool {
	if x != nil && x.ValidateOnly != nil {
		return *x.ValidateOnly
	}
	return false
}

func (x *UpdateOrganizationSettingsRequest) SetMetadata(v *proto.RequestMetadata) {
	x.Metadata = v
}

func (x *UpdateOrganizationSettingsRequest) SetOrganizationId(v string) {
	x.OrganizationId = &v
}

func (x *UpdateOrganizationSettingsRequest) SetSettings(v *OrganizationSettings) {
	x.Settings = v
}

func (x *UpdateOrganizationSettingsRequest) SetUpdateMask(v *fieldmaskpb.FieldMask) {
	x.UpdateMask = v
}

func (x *UpdateOrganizationSettingsRequest) SetValidateOnly(v bool) {
	x.ValidateOnly = &v
}

func (x *UpdateOrganizationSettingsRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *UpdateOrganizationSettingsRequest) HasOrganizationId() bool {
	if x == nil {
		return false
	}
	return x.OrganizationId != nil
}

func (x *UpdateOrganizationSettingsRequest) HasSettings() bool {
	if x == nil {
		return false
	}
	return x.Settings != nil
}

func (x *UpdateOrganizationSettingsRequest) HasUpdateMask() bool {
	if x == nil {
		return false
	}
	return x.UpdateMask != nil
}

func (x *UpdateOrganizationSettingsRequest) HasValidateOnly() bool {
	if x == nil {
		return false
	}
	return x.ValidateOnly != nil
}

func (x *UpdateOrganizationSettingsRequest) ClearMetadata() {
	x.Metadata = nil
}

func (x *UpdateOrganizationSettingsRequest) ClearOrganizationId() {
	x.OrganizationId = nil
}

func (x *UpdateOrganizationSettingsRequest) ClearSettings() {
	x.Settings = nil
}

func (x *UpdateOrganizationSettingsRequest) ClearUpdateMask() {
	x.UpdateMask = nil
}

func (x *UpdateOrganizationSettingsRequest) ClearValidateOnly() {
	x.ValidateOnly = nil
}

type UpdateOrganizationSettingsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Request metadata for tracing and context
	Metadata *proto.RequestMetadata
	// Organization identifier
	OrganizationId *string
	// Updated settings
	Settings *OrganizationSettings
	// Fields to update
	UpdateMask *fieldmaskpb.FieldMask
	// Validate only without persisting if true
	ValidateOnly *bool
}

func (b0 UpdateOrganizationSettingsRequest_builder) Build() *UpdateOrganizationSettingsRequest {
	m0 := &UpdateOrganizationSettingsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Metadata = b.Metadata
	x.OrganizationId = b.OrganizationId
	x.Settings = b.Settings
	x.UpdateMask = b.UpdateMask
	x.ValidateOnly = b.ValidateOnly
	return m0
}

var File_pkg_organization_proto_requests_update_organization_settings_request_proto protoreflect.FileDescriptor

const file_pkg_organization_proto_requests_update_organization_settings_request_proto_rawDesc = "" +
	"\n" +
	"Jpkg/organization/proto/requests/update_organization_settings_request.proto\x12\x17gcommon.v1.organization\x1a!google/protobuf/go_features.proto\x1a0pkg/common/proto/messages/request_metadata.proto\x1a google/protobuf/field_mask.proto\x1a;pkg/organization/proto/messages/organization_settings.proto\"\xb9\x02\n" +
	"!UpdateOrganizationSettingsRequest\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".gcommon.v1.common.RequestMetadataR\bmetadata\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12I\n" +
	"\bsettings\x18\x03 \x01(\v2-.gcommon.v1.organization.OrganizationSettingsR\bsettings\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12#\n" +
	"\rvalidate_only\x18\x05 \x01(\bR\fvalidateOnlyB\xfe\x01\n" +
	"\x1bcom.gcommon.v1.organizationB&UpdateOrganizationSettingsRequestProtoP\x01Z1../../../../pkg/organization/proto;organizationpb\xa2\x02\x03GVO\xaa\x02\x17Gcommon.V1.Organization\xca\x02\x17Gcommon\\V1\\Organization\xe2\x02#Gcommon\\V1\\Organization\\GPBMetadata\xea\x02\x19Gcommon::V1::Organization\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_pkg_organization_proto_requests_update_organization_settings_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_organization_proto_requests_update_organization_settings_request_proto_goTypes = []any{
	(*UpdateOrganizationSettingsRequest)(nil), // 0: gcommon.v1.organization.UpdateOrganizationSettingsRequest
	(*proto.RequestMetadata)(nil),             // 1: gcommon.v1.common.RequestMetadata
	(*OrganizationSettings)(nil),              // 2: gcommon.v1.organization.OrganizationSettings
	(*fieldmaskpb.FieldMask)(nil),             // 3: google.protobuf.FieldMask
}
var file_pkg_organization_proto_requests_update_organization_settings_request_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.organization.UpdateOrganizationSettingsRequest.metadata:type_name -> gcommon.v1.common.RequestMetadata
	2, // 1: gcommon.v1.organization.UpdateOrganizationSettingsRequest.settings:type_name -> gcommon.v1.organization.OrganizationSettings
	3, // 2: gcommon.v1.organization.UpdateOrganizationSettingsRequest.update_mask:type_name -> google.protobuf.FieldMask
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_organization_proto_requests_update_organization_settings_request_proto_init() }
func file_pkg_organization_proto_requests_update_organization_settings_request_proto_init() {
	if File_pkg_organization_proto_requests_update_organization_settings_request_proto != nil {
		return
	}
	file_pkg_organization_proto_messages_organization_settings_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_organization_proto_requests_update_organization_settings_request_proto_rawDesc), len(file_pkg_organization_proto_requests_update_organization_settings_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_organization_proto_requests_update_organization_settings_request_proto_goTypes,
		DependencyIndexes: file_pkg_organization_proto_requests_update_organization_settings_request_proto_depIdxs,
		MessageInfos:      file_pkg_organization_proto_requests_update_organization_settings_request_proto_msgTypes,
	}.Build()
	File_pkg_organization_proto_requests_update_organization_settings_request_proto = out.File
	file_pkg_organization_proto_requests_update_organization_settings_request_proto_goTypes = nil
	file_pkg_organization_proto_requests_update_organization_settings_request_proto_depIdxs = nil
}
