# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/config/messages/transformation_step.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gcommon/v1/config/messages/transformation_step.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gcommon.v1.config.enums import transformation_type_pb2 as gcommon_dot_v1_dot_config_dot_enums_dot_transformation__type__pb2
from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4gcommon/v1/config/messages/transformation_step.proto\x12\x11gcommon.v1.config\x1a\x31gcommon/v1/config/enums/transformation_type.proto\x1a!google/protobuf/go_features.proto\"\xc9\x02\n\x12TransformationStep\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x39\n\x04type\x18\x02 \x01(\x0e\x32%.gcommon.v1.config.TransformationTypeR\x04type\x12\x1e\n\nexpression\x18\x03 \x01(\tR\nexpression\x12U\n\nparameters\x18\x04 \x03(\x0b\x32\x35.gcommon.v1.config.TransformationStep.ParametersEntryR\nparameters\x12\x18\n\x07\x65nabled\x18\x05 \x01(\x08R\x07\x65nabled\x12\x14\n\x05order\x18\x06 \x01(\x05R\x05order\x1a=\n\x0fParametersEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\xd3\x01\n\x15\x63om.gcommon.v1.configB\x17TransformationStepProtoP\x01Z3github.com/jdfalk/gcommon/sdks/go/gcommon/v1/config\xa2\x02\x03GVC\xaa\x02\x11Gcommon.V1.Config\xca\x02\x11Gcommon\\V1\\Config\xe2\x02\x1dGcommon\\V1\\Config\\GPBMetadata\xea\x02\x13Gcommon::V1::Config\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcommon.v1.config.messages.transformation_step_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.gcommon.v1.configB\027TransformationStepProtoP\001Z3github.com/jdfalk/gcommon/sdks/go/gcommon/v1/config\242\002\003GVC\252\002\021Gcommon.V1.Config\312\002\021Gcommon\\V1\\Config\342\002\035Gcommon\\V1\\Config\\GPBMetadata\352\002\023Gcommon::V1::Config\222\003\005\322>\002\020\003'
  _globals['_TRANSFORMATIONSTEP_PARAMETERSENTRY']._loaded_options = None
  _globals['_TRANSFORMATIONSTEP_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_TRANSFORMATIONSTEP']._serialized_start=162
  _globals['_TRANSFORMATIONSTEP']._serialized_end=491
  _globals['_TRANSFORMATIONSTEP_PARAMETERSENTRY']._serialized_start=430
  _globals['_TRANSFORMATIONSTEP_PARAMETERSENTRY']._serialized_end=491
# @@protoc_insertion_point(module_scope)
