# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/config/approval_requirement.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    "",
    "gcommon/v1/config/approval_requirement.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n,gcommon/v1/config/approval_requirement.proto\x12\x11gcommon.v1.config\x1a!google/protobuf/go_features.proto\x1a\x1b\x62uf/validate/validate.proto"\x8c\x03\n\x13\x41pprovalRequirement\x12\x1a\n\x08required\x18\x01 \x01(\x08R\x08required\x12.\n\x0e\x61pproval_count\x18\x02 \x01(\x05\x42\x07\xbaH\x04\x1a\x02(\x00R\rapprovalCount\x12/\n\x0e\x61pprover_roles\x18\x03 \x03(\tB\x08\xbaH\x05\x92\x01\x02\x08\x01R\rapproverRoles\x12/\n\x0e\x61pprover_users\x18\x04 \x03(\tB\x08\xbaH\x05\x92\x01\x02\x08\x01R\rapproverUsers\x12\x1f\n\x06policy\x18\x05 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x06policy\x12#\n\x08workflow\x18\x06 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08workflow\x12\x42\n\x18\x61uto_approval_conditions\x18\x07 \x03(\tB\x08\xbaH\x05\x92\x01\x02\x08\x01R\x16\x61utoApprovalConditions\x12=\n\x16\x61pproval_timeout_hours\x18\x08 \x01(\x05\x42\x07\xbaH\x04\x1a\x02 \x00R\x14\x61pprovalTimeoutHoursB5Z+github.com/jdfalk/gcommon/sdks/go/v1/config\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gcommon.v1.config.approval_requirement_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"Z+github.com/jdfalk/gcommon/sdks/go/v1/config\222\003\005\322>\002\020\003"
    )
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "approval_count"
    ]._loaded_options = None
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "approval_count"
    ]._serialized_options = b"\272H\004\032\002(\000"
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "approver_roles"
    ]._loaded_options = None
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "approver_roles"
    ]._serialized_options = b"\272H\005\222\001\002\010\001"
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "approver_users"
    ]._loaded_options = None
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "approver_users"
    ]._serialized_options = b"\272H\005\222\001\002\010\001"
    _globals["_APPROVALREQUIREMENT"].fields_by_name["policy"]._loaded_options = None
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "policy"
    ]._serialized_options = b"\272H\004r\002\020\001"
    _globals["_APPROVALREQUIREMENT"].fields_by_name["workflow"]._loaded_options = None
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "workflow"
    ]._serialized_options = b"\272H\004r\002\020\001"
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "auto_approval_conditions"
    ]._loaded_options = None
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "auto_approval_conditions"
    ]._serialized_options = b"\272H\005\222\001\002\010\001"
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "approval_timeout_hours"
    ]._loaded_options = None
    _globals["_APPROVALREQUIREMENT"].fields_by_name[
        "approval_timeout_hours"
    ]._serialized_options = b"\272H\004\032\002 \000"
    _globals["_APPROVALREQUIREMENT"]._serialized_start = 132
    _globals["_APPROVALREQUIREMENT"]._serialized_end = 528
# @@protoc_insertion_point(module_scope)
