from gcommon.v1.common import assign_role_request_pb2 as _assign_role_request_pb2
from gcommon.v1.common import create_role_request_pb2 as _create_role_request_pb2
from gcommon.v1.common import create_role_response_pb2 as _create_role_response_pb2
from gcommon.v1.common import create_user_request_pb2 as _create_user_request_pb2
from gcommon.v1.common import create_user_response_pb2 as _create_user_response_pb2
from gcommon.v1.common import delete_role_request_pb2 as _delete_role_request_pb2
from gcommon.v1.common import delete_user_request_pb2 as _delete_user_request_pb2
from gcommon.v1.common import get_system_stats_request_pb2 as _get_system_stats_request_pb2
from gcommon.v1.common import get_system_stats_response_pb2 as _get_system_stats_response_pb2
from gcommon.v1.common import get_user_request_pb2 as _get_user_request_pb2
from gcommon.v1.common import get_user_response_pb2 as _get_user_response_pb2
from gcommon.v1.common import invalidate_user_sessions_request_pb2 as _invalidate_user_sessions_request_pb2
from gcommon.v1.common import list_roles_request_pb2 as _list_roles_request_pb2
from gcommon.v1.common import list_roles_response_pb2 as _list_roles_response_pb2
from gcommon.v1.common import list_users_request_pb2 as _list_users_request_pb2
from gcommon.v1.common import list_users_response_pb2 as _list_users_response_pb2
from gcommon.v1.common import remove_role_request_pb2 as _remove_role_request_pb2
from gcommon.v1.common import update_role_request_pb2 as _update_role_request_pb2
from gcommon.v1.common import update_role_response_pb2 as _update_role_response_pb2
from gcommon.v1.common import update_user_request_pb2 as _update_user_request_pb2
from gcommon.v1.common import update_user_response_pb2 as _update_user_response_pb2
from google.protobuf import empty_pb2 as _empty_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
