# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/common/list_roles_response.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'gcommon/v1/common/list_roles_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gcommon.v1.common import paginated_response_pb2 as gcommon_dot_v1_dot_common_dot_paginated__response__pb2
from gcommon.v1.common import role_pb2 as gcommon_dot_v1_dot_common_dot_role__pb2
from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+gcommon/v1/common/list_roles_response.proto\x12\x11gcommon.v1.common\x1a*gcommon/v1/common/paginated_response.proto\x1a\x1cgcommon/v1/common/role.proto\x1a!google/protobuf/go_features.proto\x1a\x1b\x62uf/validate/validate.proto\"\x92\x01\n\x11ListRolesResponse\x12\x37\n\x05roles\x18\x01 \x03(\x0b\x32\x17.gcommon.v1.common.RoleB\x08\xbaH\x05\x92\x01\x02\x08\x01R\x05roles\x12\x44\n\npagination\x18\x02 \x01(\x0b\x32$.gcommon.v1.common.PaginatedResponseR\npaginationB5Z+github.com/jdfalk/gcommon/sdks/go/v1/common\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcommon.v1.common.list_roles_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/jdfalk/gcommon/sdks/go/v1/common\222\003\005\322>\002\020\003'
  _globals['_LISTROLESRESPONSE'].fields_by_name['roles']._loaded_options = None
  _globals['_LISTROLESRESPONSE'].fields_by_name['roles']._serialized_options = b'\272H\005\222\001\002\010\001'
  _globals['_LISTROLESRESPONSE']._serialized_start=205
  _globals['_LISTROLESRESPONSE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
