// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: pkg/auth/proto/create_user_request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request to create a new user account.
type CreateUserRequest struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username                 *string                `protobuf:"bytes,1,opt,name=username"`
	xxx_hidden_Email                    *string                `protobuf:"bytes,2,opt,name=email"`
	xxx_hidden_Password                 *string                `protobuf:"bytes,3,opt,name=password"`
	xxx_hidden_FullName                 *string                `protobuf:"bytes,4,opt,name=full_name,json=fullName"`
	xxx_hidden_Enabled                  bool                   `protobuf:"varint,5,opt,name=enabled"`
	xxx_hidden_Roles                    []string               `protobuf:"bytes,6,rep,name=roles"`
	xxx_hidden_Metadata                 map[string]string      `protobuf:"bytes,7,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_RequireEmailVerification bool                   `protobuf:"varint,8,opt,name=require_email_verification,json=requireEmailVerification"`
	xxx_hidden_ExpiresAt                *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [1]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_pkg_auth_proto_create_user_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_auth_proto_create_user_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *CreateUserRequest) GetFullName() string {
	if x != nil {
		if x.xxx_hidden_FullName != nil {
			return *x.xxx_hidden_FullName
		}
		return ""
	}
	return ""
}

func (x *CreateUserRequest) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *CreateUserRequest) GetRoles() []string {
	if x != nil {
		return x.xxx_hidden_Roles
	}
	return nil
}

func (x *CreateUserRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *CreateUserRequest) GetRequireEmailVerification() bool {
	if x != nil {
		return x.xxx_hidden_RequireEmailVerification
	}
	return false
}

func (x *CreateUserRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *CreateUserRequest) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *CreateUserRequest) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *CreateUserRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *CreateUserRequest) SetFullName(v string) {
	x.xxx_hidden_FullName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *CreateUserRequest) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *CreateUserRequest) SetRoles(v []string) {
	x.xxx_hidden_Roles = v
}

func (x *CreateUserRequest) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *CreateUserRequest) SetRequireEmailVerification(v bool) {
	x.xxx_hidden_RequireEmailVerification = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *CreateUserRequest) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *CreateUserRequest) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateUserRequest) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateUserRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateUserRequest) HasFullName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateUserRequest) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CreateUserRequest) HasRequireEmailVerification() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *CreateUserRequest) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *CreateUserRequest) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Username = nil
}

func (x *CreateUserRequest) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Email = nil
}

func (x *CreateUserRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Password = nil
}

func (x *CreateUserRequest) ClearFullName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_FullName = nil
}

func (x *CreateUserRequest) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Enabled = false
}

func (x *CreateUserRequest) ClearRequireEmailVerification() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_RequireEmailVerification = false
}

func (x *CreateUserRequest) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

type CreateUserRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Username for the new account
	Username *string
	// Email address for the new account
	Email *string
	// Password for the new account (should be hashed)
	Password *string
	// Full name of the user
	FullName *string
	// Whether the account should be enabled immediately
	Enabled *bool
	// Initial roles to assign to the user
	Roles []string
	// Additional metadata for the user
	Metadata map[string]string
	// Whether to require email verification
	RequireEmailVerification *bool
	// Account expiration time (optional)
	ExpiresAt *timestamppb.Timestamp
}

func (b0 CreateUserRequest_builder) Build() *CreateUserRequest {
	m0 := &CreateUserRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Username = b.Username
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Email = b.Email
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Password = b.Password
	}
	if b.FullName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_FullName = b.FullName
	}
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	x.xxx_hidden_Roles = b.Roles
	x.xxx_hidden_Metadata = b.Metadata
	if b.RequireEmailVerification != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_RequireEmailVerification = *b.RequireEmailVerification
	}
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	return m0
}

var File_pkg_auth_proto_create_user_request_proto protoreflect.FileDescriptor

const file_pkg_auth_proto_create_user_request_proto_rawDesc = "" +
	"\n" +
	"(pkg/auth/proto/create_user_request.proto\x12\x0fgcommon.v1.auth\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x03\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\x12L\n" +
	"\bmetadata\x18\a \x03(\v20.gcommon.v1.auth.CreateUserRequest.MetadataEntryR\bmetadata\x12<\n" +
	"\x1arequire_email_verification\x18\b \x01(\bR\x18requireEmailVerification\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xbd\x01\n" +
	"\x13com.gcommon.v1.authB\x16CreateUserRequestProtoP\x01Z(github.com/jdfalk/gcommon/pkg/auth/proto\xa2\x02\x03GVA\xaa\x02\x0fGcommon.V1.Auth\xca\x02\x0fGcommon\\V1\\Auth\xe2\x02\x1bGcommon\\V1\\Auth\\GPBMetadata\xea\x02\x11Gcommon::V1::Auth\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_pkg_auth_proto_create_user_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_auth_proto_create_user_request_proto_goTypes = []any{
	(*CreateUserRequest)(nil),     // 0: gcommon.v1.auth.CreateUserRequest
	nil,                           // 1: gcommon.v1.auth.CreateUserRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_auth_proto_create_user_request_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.auth.CreateUserRequest.metadata:type_name -> gcommon.v1.auth.CreateUserRequest.MetadataEntry
	2, // 1: gcommon.v1.auth.CreateUserRequest.expires_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_auth_proto_create_user_request_proto_init() }
func file_pkg_auth_proto_create_user_request_proto_init() {
	if File_pkg_auth_proto_create_user_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_auth_proto_create_user_request_proto_rawDesc), len(file_pkg_auth_proto_create_user_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_auth_proto_create_user_request_proto_goTypes,
		DependencyIndexes: file_pkg_auth_proto_create_user_request_proto_depIdxs,
		MessageInfos:      file_pkg_auth_proto_create_user_request_proto_msgTypes,
	}.Build()
	File_pkg_auth_proto_create_user_request_proto = out.File
	file_pkg_auth_proto_create_user_request_proto_goTypes = nil
	file_pkg_auth_proto_create_user_request_proto_depIdxs = nil
}
