// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/auth/proto/get_session_request.proto

package proto

import (
	proto "github.com/jdfalk/gcommon/pkg/common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request to get session information.
// Used to retrieve detailed session data by session ID.
// Provides session status, metadata, and activity information.
type GetSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID to retrieve (required)
	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	// Whether to include detailed session activity
	IncludeActivity *bool `protobuf:"varint,2,opt,name=include_activity,json=includeActivity" json:"include_activity,omitempty"`
	// Request metadata for tracing and correlation
	Metadata      *proto.RequestMetadata `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_pkg_auth_proto_get_session_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_auth_proto_get_session_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_auth_proto_get_session_request_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *GetSessionRequest) GetIncludeActivity() bool {
	if x != nil && x.IncludeActivity != nil {
		return *x.IncludeActivity
	}
	return false
}

func (x *GetSessionRequest) GetMetadata() *proto.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_auth_proto_get_session_request_proto protoreflect.FileDescriptor

const file_pkg_auth_proto_get_session_request_proto_rawDesc = "" +
	"\n" +
	"(pkg/auth/proto/get_session_request.proto\x12\x0fgcommon.v1.auth\x1a'pkg/common/proto/request_metadata.proto\"\x9d\x01\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10include_activity\x18\x02 \x01(\bR\x0fincludeActivity\x12>\n" +
	"\bmetadata\x18\x03 \x01(\v2\".gcommon.v1.common.RequestMetadataR\bmetadataB\xb5\x01\n" +
	"\x13com.gcommon.v1.authB\x16GetSessionRequestProtoP\x01Z(github.com/jdfalk/gcommon/pkg/auth/proto\xa2\x02\x03GVA\xaa\x02\x0fGcommon.V1.Auth\xca\x02\x0fGcommon\\V1\\Auth\xe2\x02\x1bGcommon\\V1\\Auth\\GPBMetadata\xea\x02\x11Gcommon::V1::Authb\beditionsp\xe8\a"

var (
	file_pkg_auth_proto_get_session_request_proto_rawDescOnce sync.Once
	file_pkg_auth_proto_get_session_request_proto_rawDescData []byte
)

func file_pkg_auth_proto_get_session_request_proto_rawDescGZIP() []byte {
	file_pkg_auth_proto_get_session_request_proto_rawDescOnce.Do(func() {
		file_pkg_auth_proto_get_session_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_auth_proto_get_session_request_proto_rawDesc), len(file_pkg_auth_proto_get_session_request_proto_rawDesc)))
	})
	return file_pkg_auth_proto_get_session_request_proto_rawDescData
}

var file_pkg_auth_proto_get_session_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_auth_proto_get_session_request_proto_goTypes = []any{
	(*GetSessionRequest)(nil),     // 0: gcommon.v1.auth.GetSessionRequest
	(*proto.RequestMetadata)(nil), // 1: gcommon.v1.common.RequestMetadata
}
var file_pkg_auth_proto_get_session_request_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.auth.GetSessionRequest.metadata:type_name -> gcommon.v1.common.RequestMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_auth_proto_get_session_request_proto_init() }
func file_pkg_auth_proto_get_session_request_proto_init() {
	if File_pkg_auth_proto_get_session_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_auth_proto_get_session_request_proto_rawDesc), len(file_pkg_auth_proto_get_session_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_auth_proto_get_session_request_proto_goTypes,
		DependencyIndexes: file_pkg_auth_proto_get_session_request_proto_depIdxs,
		MessageInfos:      file_pkg_auth_proto_get_session_request_proto_msgTypes,
	}.Build()
	File_pkg_auth_proto_get_session_request_proto = out.File
	file_pkg_auth_proto_get_session_request_proto_goTypes = nil
	file_pkg_auth_proto_get_session_request_proto_depIdxs = nil
}
