// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/auth/proto/refresh_token_response.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Response to token refresh request.
// Contains new access token and potentially new refresh token.
// Follows OAuth2 token response format.
type RefreshTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New access token for API authentication
	AccessToken *string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	// New refresh token (may be the same as input)
	RefreshToken *string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	// Token type (always "Bearer")
	TokenType *string `protobuf:"bytes,3,opt,name=token_type,json=tokenType" json:"token_type,omitempty"`
	// Access token expiration time in seconds
	ExpiresIn *int32 `protobuf:"varint,4,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
	// Granted scopes for the new access token
	Scopes        []string `protobuf:"bytes,5,rep,name=scopes" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_pkg_auth_proto_refresh_token_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_auth_proto_refresh_token_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_pkg_auth_proto_refresh_token_response_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil && x.RefreshToken != nil {
		return *x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetTokenType() string {
	if x != nil && x.TokenType != nil {
		return *x.TokenType
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresIn() int32 {
	if x != nil && x.ExpiresIn != nil {
		return *x.ExpiresIn
	}
	return 0
}

func (x *RefreshTokenResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

var File_pkg_auth_proto_refresh_token_response_proto protoreflect.FileDescriptor

const file_pkg_auth_proto_refresh_token_response_proto_rawDesc = "" +
	"\n" +
	"+pkg/auth/proto/refresh_token_response.proto\x12\x0fgcommon.v1.auth\"\xb4\x01\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopesB\xb8\x01\n" +
	"\x13com.gcommon.v1.authB\x19RefreshTokenResponseProtoP\x01Z(github.com/jdfalk/gcommon/pkg/auth/proto\xa2\x02\x03GVA\xaa\x02\x0fGcommon.V1.Auth\xca\x02\x0fGcommon\\V1\\Auth\xe2\x02\x1bGcommon\\V1\\Auth\\GPBMetadata\xea\x02\x11Gcommon::V1::Authb\beditionsp\xe8\a"

var (
	file_pkg_auth_proto_refresh_token_response_proto_rawDescOnce sync.Once
	file_pkg_auth_proto_refresh_token_response_proto_rawDescData []byte
)

func file_pkg_auth_proto_refresh_token_response_proto_rawDescGZIP() []byte {
	file_pkg_auth_proto_refresh_token_response_proto_rawDescOnce.Do(func() {
		file_pkg_auth_proto_refresh_token_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_auth_proto_refresh_token_response_proto_rawDesc), len(file_pkg_auth_proto_refresh_token_response_proto_rawDesc)))
	})
	return file_pkg_auth_proto_refresh_token_response_proto_rawDescData
}

var file_pkg_auth_proto_refresh_token_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_auth_proto_refresh_token_response_proto_goTypes = []any{
	(*RefreshTokenResponse)(nil), // 0: gcommon.v1.auth.RefreshTokenResponse
}
var file_pkg_auth_proto_refresh_token_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_auth_proto_refresh_token_response_proto_init() }
func file_pkg_auth_proto_refresh_token_response_proto_init() {
	if File_pkg_auth_proto_refresh_token_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_auth_proto_refresh_token_response_proto_rawDesc), len(file_pkg_auth_proto_refresh_token_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_auth_proto_refresh_token_response_proto_goTypes,
		DependencyIndexes: file_pkg_auth_proto_refresh_token_response_proto_depIdxs,
		MessageInfos:      file_pkg_auth_proto_refresh_token_response_proto_msgTypes,
	}.Build()
	File_pkg_auth_proto_refresh_token_response_proto = out.File
	file_pkg_auth_proto_refresh_token_response_proto_goTypes = nil
	file_pkg_auth_proto_refresh_token_response_proto_depIdxs = nil
}
