// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/organization/proto/responses/get_organization_response.proto

//go:build protoopaque

package responses

import (
	messages1 "github.com/jdfalk/gcommon/pkg/common/proto/messages"
	messages "github.com/jdfalk/gcommon/pkg/organization/proto/messages"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// GetOrganizationResponse message returning organization information.
type GetOrganizationResponse struct {
	state                   protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Organization *messages.Organization         `protobuf:"bytes,1,opt,name=organization"`
	xxx_hidden_Settings     *messages.OrganizationSettings `protobuf:"bytes,2,opt,name=settings"`
	xxx_hidden_MemberCount  int32                          `protobuf:"varint,3,opt,name=member_count,json=memberCount"`
	xxx_hidden_Tenants      *[]*messages.Tenant            `protobuf:"bytes,4,rep,name=tenants"`
	xxx_hidden_Errors       *[]*messages1.Error            `protobuf:"bytes,5,rep,name=errors"`
	xxx_hidden_Success      bool                           `protobuf:"varint,6,opt,name=success"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetOrganizationResponse) Reset() {
	*x = GetOrganizationResponse{}
	mi := &file_pkg_organization_proto_responses_get_organization_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationResponse) ProtoMessage() {}

func (x *GetOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_organization_proto_responses_get_organization_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOrganizationResponse) GetOrganization() *messages.Organization {
	if x != nil {
		return x.xxx_hidden_Organization
	}
	return nil
}

func (x *GetOrganizationResponse) GetSettings() *messages.OrganizationSettings {
	if x != nil {
		return x.xxx_hidden_Settings
	}
	return nil
}

func (x *GetOrganizationResponse) GetMemberCount() int32 {
	if x != nil {
		return x.xxx_hidden_MemberCount
	}
	return 0
}

func (x *GetOrganizationResponse) GetTenants() []*messages.Tenant {
	if x != nil {
		if x.xxx_hidden_Tenants != nil {
			return *x.xxx_hidden_Tenants
		}
	}
	return nil
}

func (x *GetOrganizationResponse) GetErrors() []*messages1.Error {
	if x != nil {
		if x.xxx_hidden_Errors != nil {
			return *x.xxx_hidden_Errors
		}
	}
	return nil
}

func (x *GetOrganizationResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *GetOrganizationResponse) SetOrganization(v *messages.Organization) {
	x.xxx_hidden_Organization = v
}

func (x *GetOrganizationResponse) SetSettings(v *messages.OrganizationSettings) {
	x.xxx_hidden_Settings = v
}

func (x *GetOrganizationResponse) SetMemberCount(v int32) {
	x.xxx_hidden_MemberCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *GetOrganizationResponse) SetTenants(v []*messages.Tenant) {
	x.xxx_hidden_Tenants = &v
}

func (x *GetOrganizationResponse) SetErrors(v []*messages1.Error) {
	x.xxx_hidden_Errors = &v
}

func (x *GetOrganizationResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *GetOrganizationResponse) HasOrganization() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Organization != nil
}

func (x *GetOrganizationResponse) HasSettings() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Settings != nil
}

func (x *GetOrganizationResponse) HasMemberCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetOrganizationResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *GetOrganizationResponse) ClearOrganization() {
	x.xxx_hidden_Organization = nil
}

func (x *GetOrganizationResponse) ClearSettings() {
	x.xxx_hidden_Settings = nil
}

func (x *GetOrganizationResponse) ClearMemberCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MemberCount = 0
}

func (x *GetOrganizationResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Success = false
}

type GetOrganizationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Organization information
	Organization *messages.Organization
	// Organization settings (if requested)
	Settings *messages.OrganizationSettings
	// Number of members in organization (if requested)
	MemberCount *int32
	// List of tenants in organization (if requested)
	Tenants []*messages.Tenant
	// Any errors encountered during retrieval
	Errors []*messages1.Error
	// Success status
	Success *bool
}

func (b0 GetOrganizationResponse_builder) Build() *GetOrganizationResponse {
	m0 := &GetOrganizationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Organization = b.Organization
	x.xxx_hidden_Settings = b.Settings
	if b.MemberCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_MemberCount = *b.MemberCount
	}
	x.xxx_hidden_Tenants = &b.Tenants
	x.xxx_hidden_Errors = &b.Errors
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

var File_pkg_organization_proto_responses_get_organization_response_proto protoreflect.FileDescriptor

const file_pkg_organization_proto_responses_get_organization_response_proto_rawDesc = "" +
	"\n" +
	"@pkg/organization/proto/responses/get_organization_response.proto\x12\x17gcommon.v1.organization\x1a!google/protobuf/go_features.proto\x1a2pkg/organization/proto/messages/organization.proto\x1a;pkg/organization/proto/messages/organization_settings.proto\x1a,pkg/organization/proto/messages/tenant.proto\x1a%pkg/common/proto/messages/error.proto\"\xd9\x02\n" +
	"\x17GetOrganizationResponse\x12I\n" +
	"\forganization\x18\x01 \x01(\v2%.gcommon.v1.organization.OrganizationR\forganization\x12I\n" +
	"\bsettings\x18\x02 \x01(\v2-.gcommon.v1.organization.OrganizationSettingsR\bsettings\x12!\n" +
	"\fmember_count\x18\x03 \x01(\x05R\vmemberCount\x129\n" +
	"\atenants\x18\x04 \x03(\v2\x1f.gcommon.v1.organization.TenantR\atenants\x120\n" +
	"\x06errors\x18\x05 \x03(\v2\x18.gcommon.v1.common.ErrorR\x06errors\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccessB\xfd\x01\n" +
	"\x1bcom.gcommon.v1.organizationB\x1cGetOrganizationResponseProtoP\x01Z:github.com/jdfalk/gcommon/pkg/organization/proto/responses\xa2\x02\x03GVO\xaa\x02\x17Gcommon.V1.Organization\xca\x02\x17Gcommon\\V1\\Organization\xe2\x02#Gcommon\\V1\\Organization\\GPBMetadata\xea\x02\x19Gcommon::V1::Organization\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_pkg_organization_proto_responses_get_organization_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_organization_proto_responses_get_organization_response_proto_goTypes = []any{
	(*GetOrganizationResponse)(nil),       // 0: gcommon.v1.organization.GetOrganizationResponse
	(*messages.Organization)(nil),         // 1: gcommon.v1.organization.Organization
	(*messages.OrganizationSettings)(nil), // 2: gcommon.v1.organization.OrganizationSettings
	(*messages.Tenant)(nil),               // 3: gcommon.v1.organization.Tenant
	(*messages1.Error)(nil),               // 4: gcommon.v1.common.Error
}
var file_pkg_organization_proto_responses_get_organization_response_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.organization.GetOrganizationResponse.organization:type_name -> gcommon.v1.organization.Organization
	2, // 1: gcommon.v1.organization.GetOrganizationResponse.settings:type_name -> gcommon.v1.organization.OrganizationSettings
	3, // 2: gcommon.v1.organization.GetOrganizationResponse.tenants:type_name -> gcommon.v1.organization.Tenant
	4, // 3: gcommon.v1.organization.GetOrganizationResponse.errors:type_name -> gcommon.v1.common.Error
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_organization_proto_responses_get_organization_response_proto_init() }
func file_pkg_organization_proto_responses_get_organization_response_proto_init() {
	if File_pkg_organization_proto_responses_get_organization_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_organization_proto_responses_get_organization_response_proto_rawDesc), len(file_pkg_organization_proto_responses_get_organization_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_organization_proto_responses_get_organization_response_proto_goTypes,
		DependencyIndexes: file_pkg_organization_proto_responses_get_organization_response_proto_depIdxs,
		MessageInfos:      file_pkg_organization_proto_responses_get_organization_response_proto_msgTypes,
	}.Build()
	File_pkg_organization_proto_responses_get_organization_response_proto = out.File
	file_pkg_organization_proto_responses_get_organization_response_proto_goTypes = nil
	file_pkg_organization_proto_responses_get_organization_response_proto_depIdxs = nil
}
