// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/common/proto/enums/ack_mode.proto

//go:build !protoopaque

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Acknowledgment mode enumeration for message processing.
// Defines how message acknowledgments are handled in streaming operations,
// queue processing, and event handling across all GCommon modules.
type AckMode int32

const (
	// Default value indicating no acknowledgment mode was specified
	AckMode_ACK_MODE_UNSPECIFIED AckMode = 0
	// Manual acknowledgment - client must explicitly acknowledge messages
	AckMode_ACK_MODE_MANUAL AckMode = 1
	// Automatic acknowledgment - messages are acknowledged upon delivery
	AckMode_ACK_MODE_AUTO AckMode = 2
	// Client-side acknowledgment - acknowledgment is handled by client logic
	AckMode_ACK_MODE_CLIENT AckMode = 3
)

// Enum value maps for AckMode.
var (
	AckMode_name = map[int32]string{
		0: "ACK_MODE_UNSPECIFIED",
		1: "ACK_MODE_MANUAL",
		2: "ACK_MODE_AUTO",
		3: "ACK_MODE_CLIENT",
	}
	AckMode_value = map[string]int32{
		"ACK_MODE_UNSPECIFIED": 0,
		"ACK_MODE_MANUAL":      1,
		"ACK_MODE_AUTO":        2,
		"ACK_MODE_CLIENT":      3,
	}
)

func (x AckMode) Enum() *AckMode {
	p := new(AckMode)
	*p = x
	return p
}

func (x AckMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_common_proto_enums_ack_mode_proto_enumTypes[0].Descriptor()
}

func (AckMode) Type() protoreflect.EnumType {
	return &file_pkg_common_proto_enums_ack_mode_proto_enumTypes[0]
}

func (x AckMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_pkg_common_proto_enums_ack_mode_proto protoreflect.FileDescriptor

const file_pkg_common_proto_enums_ack_mode_proto_rawDesc = "" +
	"\n" +
	"%pkg/common/proto/enums/ack_mode.proto\x12\x11gcommon.v1.common\x1a!google/protobuf/go_features.proto*`\n" +
	"\aAckMode\x12\x18\n" +
	"\x14ACK_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACK_MODE_MANUAL\x10\x01\x12\x11\n" +
	"\rACK_MODE_AUTO\x10\x02\x12\x13\n" +
	"\x0fACK_MODE_CLIENT\x10\x03B\xc8\x01\n" +
	"\x15com.gcommon.v1.commonB\fAckModeProtoP\x01Z3github.com/jdfalk/gcommon/pkg/common/proto;commonpb\xa2\x02\x03GVC\xaa\x02\x11Gcommon.V1.Common\xca\x02\x11Gcommon\\V1\\Common\xe2\x02\x1dGcommon\\V1\\Common\\GPBMetadata\xea\x02\x13Gcommon::V1::Common\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_pkg_common_proto_enums_ack_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_common_proto_enums_ack_mode_proto_goTypes = []any{
	(AckMode)(0), // 0: gcommon.v1.common.AckMode
}
var file_pkg_common_proto_enums_ack_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_common_proto_enums_ack_mode_proto_init() }
func file_pkg_common_proto_enums_ack_mode_proto_init() {
	if File_pkg_common_proto_enums_ack_mode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_common_proto_enums_ack_mode_proto_rawDesc), len(file_pkg_common_proto_enums_ack_mode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_common_proto_enums_ack_mode_proto_goTypes,
		DependencyIndexes: file_pkg_common_proto_enums_ack_mode_proto_depIdxs,
		EnumInfos:         file_pkg_common_proto_enums_ack_mode_proto_enumTypes,
	}.Build()
	File_pkg_common_proto_enums_ack_mode_proto = out.File
	file_pkg_common_proto_enums_ack_mode_proto_goTypes = nil
	file_pkg_common_proto_enums_ack_mode_proto_depIdxs = nil
}
