from gcommon.v1.metrics.messages import get_metric_metadata_request_pb2 as _get_metric_metadata_request_pb2
from gcommon.v1.metrics.messages import get_metric_metadata_response_pb2 as _get_metric_metadata_response_pb2
from gcommon.v1.metrics.messages import get_metrics_request_pb2 as _get_metrics_request_pb2
from gcommon.v1.metrics.messages import get_metrics_response_pb2 as _get_metrics_response_pb2
from gcommon.v1.metrics.messages import get_metrics_summary_request_pb2 as _get_metrics_summary_request_pb2
from gcommon.v1.metrics.messages import get_metrics_summary_response_pb2 as _get_metrics_summary_response_pb2
from gcommon.v1.metrics.messages import metric_data_pb2 as _metric_data_pb2
from gcommon.v1.metrics.messages import query_metrics_request_pb2 as _query_metrics_request_pb2
from gcommon.v1.metrics.messages import query_metrics_response_pb2 as _query_metrics_response_pb2
from gcommon.v1.metrics.messages import record_metric_request_pb2 as _record_metric_request_pb2
from gcommon.v1.metrics.messages import record_metric_response_pb2 as _record_metric_response_pb2
from gcommon.v1.metrics.messages import record_metrics_request_pb2 as _record_metrics_request_pb2
from gcommon.v1.metrics.messages import record_metrics_response_pb2 as _record_metrics_response_pb2
from gcommon.v1.metrics.messages import register_metric_request_pb2 as _register_metric_request_pb2
from gcommon.v1.metrics.messages import register_metric_response_pb2 as _register_metric_response_pb2
from gcommon.v1.metrics.messages import stream_metrics_request_pb2 as _stream_metrics_request_pb2
from gcommon.v1.metrics.messages import unregister_metric_request_pb2 as _unregister_metric_request_pb2
from gcommon.v1.metrics.messages import unregister_metric_response_pb2 as _unregister_metric_response_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
