# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/organization/network_isolation.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gcommon/v1/organization/network_isolation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gcommon.v1.organization import cdn_config_pb2 as gcommon_dot_v1_dot_organization_dot_cdn__config__pb2
from gcommon.v1.organization import domain_config_pb2 as gcommon_dot_v1_dot_organization_dot_domain__config__pb2
from gcommon.v1.organization import load_balancer_config_pb2 as gcommon_dot_v1_dot_organization_dot_load__balancer__config__pb2
from gcommon.v1.organization import network_acl_rule_pb2 as gcommon_dot_v1_dot_organization_dot_network__acl__rule__pb2
from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/gcommon/v1/organization/network_isolation.proto\x12\x17gcommon.v1.organization\x1a(gcommon/v1/organization/cdn_config.proto\x1a+gcommon/v1/organization/domain_config.proto\x1a\x32gcommon/v1/organization/load_balancer_config.proto\x1a.gcommon/v1/organization/network_acl_rule.proto\x1a!google/protobuf/go_features.proto\x1a\x1b\x62uf/validate/validate.proto\"\xe0\x03\n\x10NetworkIsolation\x12\x1e\n\x06vpc_id\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x05vpcId\x12$\n\tsubnet_id\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08subnetId\x12\x36\n\x12security_group_ids\x18\x03 \x03(\tB\x08\xbaH\x05\x92\x01\x02\x08\x01R\x10securityGroupIds\x12N\n\tacl_rules\x18\x04 \x03(\x0b\x32\'.gcommon.v1.organization.NetworkACLRuleB\x08\xbaH\x05\x92\x01\x02\x08\x01R\x08\x61\x63lRules\x12+\n\x11\x64\x65\x64icated_network\x18\x05 \x01(\x08R\x10\x64\x65\x64icatedNetwork\x12\\\n\rload_balancer\x18\x06 \x01(\x0b\x32\x37.gcommon.v1.organization.OrganizationLoadBalancerConfigR\x0cloadBalancer\x12\x34\n\x03\x63\x64n\x18\x07 \x01(\x0b\x32\".gcommon.v1.organization.CDNConfigR\x03\x63\x64n\x12=\n\x06\x64omain\x18\x08 \x01(\x0b\x32%.gcommon.v1.organization.DomainConfigR\x06\x64omainB;Z1github.com/jdfalk/gcommon/sdks/go/v1/organization\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcommon.v1.organization.network_isolation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/jdfalk/gcommon/sdks/go/v1/organization\222\003\005\322>\002\020\003'
  _globals['_NETWORKISOLATION'].fields_by_name['vpc_id']._loaded_options = None
  _globals['_NETWORKISOLATION'].fields_by_name['vpc_id']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_NETWORKISOLATION'].fields_by_name['subnet_id']._loaded_options = None
  _globals['_NETWORKISOLATION'].fields_by_name['subnet_id']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_NETWORKISOLATION'].fields_by_name['security_group_ids']._loaded_options = None
  _globals['_NETWORKISOLATION'].fields_by_name['security_group_ids']._serialized_options = b'\272H\005\222\001\002\010\001'
  _globals['_NETWORKISOLATION'].fields_by_name['acl_rules']._loaded_options = None
  _globals['_NETWORKISOLATION'].fields_by_name['acl_rules']._serialized_options = b'\272H\005\222\001\002\010\001'
  _globals['_NETWORKISOLATION']._serialized_start=328
  _globals['_NETWORKISOLATION']._serialized_end=808
# @@protoc_insertion_point(module_scope)
