# file: templates/basic-api-service/Makefile
# version: 1.0.0
# guid: e3aee588-08cd-48aa-9183-f3b8925381a5

# Simple Makefile for building and testing the basic API service template.

.PHONY: build test run

build:
	go build ./...

test:
	go test ./...

run:
	go run ./...
