# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/queue/purge_options.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 32, 0, "", "gcommon/v1/queue/purge_options.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$gcommon/v1/queue/purge_options.proto\x12\x10gcommon.v1.queue\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x62uf/validate/validate.proto"\xd2\x03\n\x0cPurgeOptions\x12\x1b\n\tpurge_all\x18\x01 \x01(\x08R\x08purgeAll\x12\x39\n\nolder_than\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tolderThan\x12X\n\x0eheader_filters\x18\x03 \x03(\x0b\x32\x31.gcommon.v1.queue.PurgeOptions.HeaderFiltersEntryR\rheaderFilters\x12.\n\x0epriority_below\x18\x04 \x01(\x05\x42\x07\xbaH\x04\x1a\x02(\x00R\rpriorityBelow\x12.\n\x0epriority_above\x18\x05 \x01(\x05\x42\x07\xbaH\x04\x1a\x02(\x00R\rpriorityAbove\x12*\n\x0cmax_messages\x18\x06 \x01(\x03\x42\x07\xbaH\x04"\x02(\x00R\x0bmaxMessages\x12\x1f\n\x0bonly_failed\x18\x07 \x01(\x08R\nonlyFailed\x12!\n\x0conly_expired\x18\x08 \x01(\x08R\x0bonlyExpired\x1a@\n\x12HeaderFiltersEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x34Z*github.com/jdfalk/gcommon/sdks/go/v1/queue\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gcommon.v1.queue.purge_options_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"Z*github.com/jdfalk/gcommon/sdks/go/v1/queue\222\003\005\322>\002\020\003"
    )
    _globals["_PURGEOPTIONS_HEADERFILTERSENTRY"]._loaded_options = None
    _globals["_PURGEOPTIONS_HEADERFILTERSENTRY"]._serialized_options = b"8\001"
    _globals["_PURGEOPTIONS"].fields_by_name["priority_below"]._loaded_options = None
    _globals["_PURGEOPTIONS"].fields_by_name[
        "priority_below"
    ]._serialized_options = b"\272H\004\032\002(\000"
    _globals["_PURGEOPTIONS"].fields_by_name["priority_above"]._loaded_options = None
    _globals["_PURGEOPTIONS"].fields_by_name[
        "priority_above"
    ]._serialized_options = b"\272H\004\032\002(\000"
    _globals["_PURGEOPTIONS"].fields_by_name["max_messages"]._loaded_options = None
    _globals["_PURGEOPTIONS"].fields_by_name[
        "max_messages"
    ]._serialized_options = b'\272H\004"\002(\000'
    _globals["_PURGEOPTIONS"]._serialized_start = 156
    _globals["_PURGEOPTIONS"]._serialized_end = 622
    _globals["_PURGEOPTIONS_HEADERFILTERSENTRY"]._serialized_start = 558
    _globals["_PURGEOPTIONS_HEADERFILTERSENTRY"]._serialized_end = 622
# @@protoc_insertion_point(module_scope)
