from gcommon.v1.queue import get_cluster_info_request_pb2 as _get_cluster_info_request_pb2
from gcommon.v1.queue import get_cluster_info_response_pb2 as _get_cluster_info_response_pb2
from gcommon.v1.queue import get_queue_health_request_pb2 as _get_queue_health_request_pb2
from gcommon.v1.queue import get_queue_health_response_pb2 as _get_queue_health_response_pb2
from gcommon.v1.queue import get_queue_stats_request_pb2 as _get_queue_stats_request_pb2
from gcommon.v1.queue import metrics_event_pb2 as _metrics_event_pb2
from gcommon.v1.queue import queue_stats_response_pb2 as _queue_stats_response_pb2
from gcommon.v1.queue import stream_metrics_request_pb2 as _stream_metrics_request_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
