// file: metricspb/v2/set_metric_metadata_response.proto
// version: 1.0.3
// guid: 2594ce5a-5795-4689-b2f9-433919c5cc67
//
// Response after updating metric metadata.
//
edition = "2023";

package metrics.v2;

import "commonpb/v2/error.proto";
import "google/protobuf/go_features.proto";
import "metricspb/v2/metric_metadata.proto";

option features.(pb.go).api_level = API_OPAQUE;
option go_package = "github.com/falkcorp/gcommon/v2/pkg/metricspb/v2";

/**
 * SetMetricMetadataResponse returns updated metadata.
 */
message SetMetricMetadataResponse {
  // Updated metadata
  MetricMetadata metadata = 1;

  // Error information
  common.v2.Error error = 2;
}
