// file: metricspb/v2/start_scraping_request.proto
// version: 1.1.2
// guid: 3bf09215-7dbf-4f23-97b5-911aeb40f125

edition = "2023";

package metrics.v2;

import "buf/validate/validate.proto";
import "commonpb/v2/request_metadata.proto";
import "google/protobuf/go_features.proto";
import "metricspb/v2/scrape_config.proto";

option features.(pb.go).api_level = API_OPAQUE;
option go_package = "github.com/falkcorp/gcommon/v2/pkg/metricspb/v2";

message StartScrapingRequest {
  // Standard request metadata
  common.v2.RequestMetadata metadata = 1;

  // Metrics provider identifier
  string provider_id = 2 [(buf.validate.field).string.min_len = 1];

  // Scrape configuration to use
  ScrapeConfig config = 3;
}
