// file: organizationpb/v2/memory_allocation.proto
// version: 1.0.2
// guid: b8114ab9-1c29-4549-ab06-3cad6a44ccf1

edition = "2023";

package organization.v2;

import "buf/validate/validate.proto";
import "google/protobuf/go_features.proto";

option features.(pb.go).api_level = API_OPAQUE;
option go_package = "github.com/falkcorp/gcommon/v2/pkg/organizationpb/v2";

message MemoryAllocation {
  // Memory size in MB
  int64 size_mb = 1 [(buf.validate.field).int64.gte = 0];

  // Memory usage limit percentage
  int32 usage_limit_percent = 2 [
    (buf.validate.field).int32.gte = 0,
    (buf.validate.field).int32.lte = 150
  ];

  // Swap allocation in MB
  int64 swap_mb = 3 [(buf.validate.field).int64.gte = 0];
}
