// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/web/proto/get_access_logs_request.proto

package proto

import (
	proto "github.com/jdfalk/gcommon/pkg/common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// GetAccessLogsRequest message for web service operations.
// Auto-generated placeholder - implement specific fields as needed.
//
// Follows 1-1-1 pattern: one message per file.
type GetAccessLogsRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RequestMetadata *proto.RequestMetadata `protobuf:"bytes,11,opt,name=request_metadata,json=requestMetadata"`
	xxx_hidden_RequestedAt     *timestamppb.Timestamp `protobuf:"bytes,51,opt,name=requested_at,json=requestedAt"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetAccessLogsRequest) Reset() {
	*x = GetAccessLogsRequest{}
	mi := &file_pkg_web_proto_get_access_logs_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessLogsRequest) ProtoMessage() {}

func (x *GetAccessLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_web_proto_get_access_logs_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAccessLogsRequest) GetRequestMetadata() *proto.RequestMetadata {
	if x != nil {
		return x.xxx_hidden_RequestMetadata
	}
	return nil
}

func (x *GetAccessLogsRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_RequestedAt
	}
	return nil
}

func (x *GetAccessLogsRequest) SetRequestMetadata(v *proto.RequestMetadata) {
	x.xxx_hidden_RequestMetadata = v
}

func (x *GetAccessLogsRequest) SetRequestedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_RequestedAt = v
}

func (x *GetAccessLogsRequest) HasRequestMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RequestMetadata != nil
}

func (x *GetAccessLogsRequest) HasRequestedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RequestedAt != nil
}

func (x *GetAccessLogsRequest) ClearRequestMetadata() {
	x.xxx_hidden_RequestMetadata = nil
}

func (x *GetAccessLogsRequest) ClearRequestedAt() {
	x.xxx_hidden_RequestedAt = nil
}

type GetAccessLogsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// *
	// Request processing metadata including timing, request ID,
	// and other observability information.
	RequestMetadata *proto.RequestMetadata
	// *
	// Timestamp when this request was created.
	RequestedAt *timestamppb.Timestamp
}

func (b0 GetAccessLogsRequest_builder) Build() *GetAccessLogsRequest {
	m0 := &GetAccessLogsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RequestMetadata = b.RequestMetadata
	x.xxx_hidden_RequestedAt = b.RequestedAt
	return m0
}

var File_pkg_web_proto_get_access_logs_request_proto protoreflect.FileDescriptor

const file_pkg_web_proto_get_access_logs_request_proto_rawDesc = "" +
	"\n" +
	"+pkg/web/proto/get_access_logs_request.proto\x12\x0egcommon.v1.web\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a'pkg/common/proto/request_metadata.proto\"\xa4\x01\n" +
	"\x14GetAccessLogsRequest\x12M\n" +
	"\x10request_metadata\x18\v \x01(\v2\".gcommon.v1.common.RequestMetadataR\x0frequestMetadata\x12=\n" +
	"\frequested_at\x183 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAtB\xba\x01\n" +
	"\x12com.gcommon.v1.webB\x19GetAccessLogsRequestProtoP\x01Z'github.com/jdfalk/gcommon/pkg/web/proto\xa2\x02\x03GVW\xaa\x02\x0eGcommon.V1.Web\xca\x02\x0eGcommon\\V1\\Web\xe2\x02\x1aGcommon\\V1\\Web\\GPBMetadata\xea\x02\x10Gcommon::V1::Web\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_pkg_web_proto_get_access_logs_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_web_proto_get_access_logs_request_proto_goTypes = []any{
	(*GetAccessLogsRequest)(nil),  // 0: gcommon.v1.web.GetAccessLogsRequest
	(*proto.RequestMetadata)(nil), // 1: gcommon.v1.common.RequestMetadata
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_web_proto_get_access_logs_request_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.web.GetAccessLogsRequest.request_metadata:type_name -> gcommon.v1.common.RequestMetadata
	2, // 1: gcommon.v1.web.GetAccessLogsRequest.requested_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_web_proto_get_access_logs_request_proto_init() }
func file_pkg_web_proto_get_access_logs_request_proto_init() {
	if File_pkg_web_proto_get_access_logs_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_web_proto_get_access_logs_request_proto_rawDesc), len(file_pkg_web_proto_get_access_logs_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_web_proto_get_access_logs_request_proto_goTypes,
		DependencyIndexes: file_pkg_web_proto_get_access_logs_request_proto_depIdxs,
		MessageInfos:      file_pkg_web_proto_get_access_logs_request_proto_msgTypes,
	}.Build()
	File_pkg_web_proto_get_access_logs_request_proto = out.File
	file_pkg_web_proto_get_access_logs_request_proto_goTypes = nil
	file_pkg_web_proto_get_access_logs_request_proto_depIdxs = nil
}
