// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: pkg/web/proto/load_balancer_config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoadBalancerConfig message definition.
type LoadBalancerConfig struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Strategy        LoadBalanceStrategy    `protobuf:"varint,1,opt,name=strategy,enum=gcommon.v1.web.LoadBalanceStrategy"`
	xxx_hidden_Upstreams       []string               `protobuf:"bytes,2,rep,name=upstreams"`
	xxx_hidden_HealthCheckPath *string                `protobuf:"bytes,3,opt,name=health_check_path,json=healthCheckPath"`
	xxx_hidden_Timeout         *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *LoadBalancerConfig) Reset() {
	*x = LoadBalancerConfig{}
	mi := &file_pkg_web_proto_load_balancer_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerConfig) ProtoMessage() {}

func (x *LoadBalancerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_web_proto_load_balancer_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoadBalancerConfig) GetStrategy() LoadBalanceStrategy {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Strategy
		}
	}
	return LoadBalanceStrategy_LOAD_BALANCE_STRATEGY_UNSPECIFIED
}

func (x *LoadBalancerConfig) GetUpstreams() []string {
	if x != nil {
		return x.xxx_hidden_Upstreams
	}
	return nil
}

func (x *LoadBalancerConfig) GetHealthCheckPath() string {
	if x != nil {
		if x.xxx_hidden_HealthCheckPath != nil {
			return *x.xxx_hidden_HealthCheckPath
		}
		return ""
	}
	return ""
}

func (x *LoadBalancerConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Timeout
	}
	return nil
}

func (x *LoadBalancerConfig) SetStrategy(v LoadBalanceStrategy) {
	x.xxx_hidden_Strategy = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *LoadBalancerConfig) SetUpstreams(v []string) {
	x.xxx_hidden_Upstreams = v
}

func (x *LoadBalancerConfig) SetHealthCheckPath(v string) {
	x.xxx_hidden_HealthCheckPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *LoadBalancerConfig) SetTimeout(v *durationpb.Duration) {
	x.xxx_hidden_Timeout = v
}

func (x *LoadBalancerConfig) HasStrategy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoadBalancerConfig) HasHealthCheckPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *LoadBalancerConfig) HasTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timeout != nil
}

func (x *LoadBalancerConfig) ClearStrategy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Strategy = LoadBalanceStrategy_LOAD_BALANCE_STRATEGY_UNSPECIFIED
}

func (x *LoadBalancerConfig) ClearHealthCheckPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_HealthCheckPath = nil
}

func (x *LoadBalancerConfig) ClearTimeout() {
	x.xxx_hidden_Timeout = nil
}

type LoadBalancerConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Load balancing strategy
	Strategy *LoadBalanceStrategy
	// Upstream server addresses
	Upstreams []string
	// Health check path
	HealthCheckPath *string
	// Timeout for proxy requests
	Timeout *durationpb.Duration
}

func (b0 LoadBalancerConfig_builder) Build() *LoadBalancerConfig {
	m0 := &LoadBalancerConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Strategy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Strategy = *b.Strategy
	}
	x.xxx_hidden_Upstreams = b.Upstreams
	if b.HealthCheckPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_HealthCheckPath = b.HealthCheckPath
	}
	x.xxx_hidden_Timeout = b.Timeout
	return m0
}

var File_pkg_web_proto_load_balancer_config_proto protoreflect.FileDescriptor

const file_pkg_web_proto_load_balancer_config_proto_rawDesc = "" +
	"\n" +
	"(pkg/web/proto/load_balancer_config.proto\x12\x0egcommon.v1.web\x1a\x1egoogle/protobuf/duration.proto\x1a!google/protobuf/go_features.proto\x1a)pkg/web/proto/load_balance_strategy.proto\"\xd4\x01\n" +
	"\x12LoadBalancerConfig\x12?\n" +
	"\bstrategy\x18\x01 \x01(\x0e2#.gcommon.v1.web.LoadBalanceStrategyR\bstrategy\x12\x1c\n" +
	"\tupstreams\x18\x02 \x03(\tR\tupstreams\x12*\n" +
	"\x11health_check_path\x18\x03 \x01(\tR\x0fhealthCheckPath\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeoutB\xb8\x01\n" +
	"\x12com.gcommon.v1.webB\x17LoadBalancerConfigProtoP\x01Z'github.com/jdfalk/gcommon/pkg/web/proto\xa2\x02\x03GVW\xaa\x02\x0eGcommon.V1.Web\xca\x02\x0eGcommon\\V1\\Web\xe2\x02\x1aGcommon\\V1\\Web\\GPBMetadata\xea\x02\x10Gcommon::V1::Web\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_pkg_web_proto_load_balancer_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_web_proto_load_balancer_config_proto_goTypes = []any{
	(*LoadBalancerConfig)(nil),  // 0: gcommon.v1.web.LoadBalancerConfig
	(LoadBalanceStrategy)(0),    // 1: gcommon.v1.web.LoadBalanceStrategy
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_pkg_web_proto_load_balancer_config_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.web.LoadBalancerConfig.strategy:type_name -> gcommon.v1.web.LoadBalanceStrategy
	2, // 1: gcommon.v1.web.LoadBalancerConfig.timeout:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_web_proto_load_balancer_config_proto_init() }
func file_pkg_web_proto_load_balancer_config_proto_init() {
	if File_pkg_web_proto_load_balancer_config_proto != nil {
		return
	}
	file_pkg_web_proto_load_balance_strategy_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_web_proto_load_balancer_config_proto_rawDesc), len(file_pkg_web_proto_load_balancer_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_web_proto_load_balancer_config_proto_goTypes,
		DependencyIndexes: file_pkg_web_proto_load_balancer_config_proto_depIdxs,
		MessageInfos:      file_pkg_web_proto_load_balancer_config_proto_msgTypes,
	}.Build()
	File_pkg_web_proto_load_balancer_config_proto = out.File
	file_pkg_web_proto_load_balancer_config_proto_goTypes = nil
	file_pkg_web_proto_load_balancer_config_proto_depIdxs = nil
}
