// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/web/proto/route_info.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RouteInfo message definition.
type RouteInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Route configuration
	Config *RouteConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	// Type of route
	RouteType *RouteType `protobuf:"varint,2,opt,name=route_type,json=routeType,enum=gcommon.v1.web.RouteType" json:"route_type,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteInfo) Reset() {
	*x = RouteInfo{}
	mi := &file_pkg_web_proto_route_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteInfo) ProtoMessage() {}

func (x *RouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_web_proto_route_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteInfo.ProtoReflect.Descriptor instead.
func (*RouteInfo) Descriptor() ([]byte, []int) {
	return file_pkg_web_proto_route_info_proto_rawDescGZIP(), []int{0}
}

func (x *RouteInfo) GetConfig() *RouteConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RouteInfo) GetRouteType() RouteType {
	if x != nil && x.RouteType != nil {
		return *x.RouteType
	}
	return RouteType_ROUTE_TYPE_UNSPECIFIED
}

func (x *RouteInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RouteInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_pkg_web_proto_route_info_proto protoreflect.FileDescriptor

const file_pkg_web_proto_route_info_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/web/proto/route_info.proto\x12\x0egcommon.v1.web\x1a\x1fgoogle/protobuf/timestamp.proto\x1a pkg/web/proto/route_config.proto\x1a\x1epkg/web/proto/route_type.proto\"\xf0\x01\n" +
	"\tRouteInfo\x123\n" +
	"\x06config\x18\x01 \x01(\v2\x1b.gcommon.v1.web.RouteConfigR\x06config\x128\n" +
	"\n" +
	"route_type\x18\x02 \x01(\x0e2\x19.gcommon.v1.web.RouteTypeR\trouteType\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\xa7\x01\n" +
	"\x12com.gcommon.v1.webB\x0eRouteInfoProtoP\x01Z'github.com/jdfalk/gcommon/pkg/web/proto\xa2\x02\x03GVW\xaa\x02\x0eGcommon.V1.Web\xca\x02\x0eGcommon\\V1\\Web\xe2\x02\x1aGcommon\\V1\\Web\\GPBMetadata\xea\x02\x10Gcommon::V1::Webb\beditionsp\xe8\a"

var (
	file_pkg_web_proto_route_info_proto_rawDescOnce sync.Once
	file_pkg_web_proto_route_info_proto_rawDescData []byte
)

func file_pkg_web_proto_route_info_proto_rawDescGZIP() []byte {
	file_pkg_web_proto_route_info_proto_rawDescOnce.Do(func() {
		file_pkg_web_proto_route_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_web_proto_route_info_proto_rawDesc), len(file_pkg_web_proto_route_info_proto_rawDesc)))
	})
	return file_pkg_web_proto_route_info_proto_rawDescData
}

var file_pkg_web_proto_route_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_web_proto_route_info_proto_goTypes = []any{
	(*RouteInfo)(nil),             // 0: gcommon.v1.web.RouteInfo
	(*RouteConfig)(nil),           // 1: gcommon.v1.web.RouteConfig
	(RouteType)(0),                // 2: gcommon.v1.web.RouteType
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_pkg_web_proto_route_info_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.web.RouteInfo.config:type_name -> gcommon.v1.web.RouteConfig
	2, // 1: gcommon.v1.web.RouteInfo.route_type:type_name -> gcommon.v1.web.RouteType
	3, // 2: gcommon.v1.web.RouteInfo.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: gcommon.v1.web.RouteInfo.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_web_proto_route_info_proto_init() }
func file_pkg_web_proto_route_info_proto_init() {
	if File_pkg_web_proto_route_info_proto != nil {
		return
	}
	file_pkg_web_proto_route_config_proto_init()
	file_pkg_web_proto_route_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_web_proto_route_info_proto_rawDesc), len(file_pkg_web_proto_route_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_web_proto_route_info_proto_goTypes,
		DependencyIndexes: file_pkg_web_proto_route_info_proto_depIdxs,
		MessageInfos:      file_pkg_web_proto_route_info_proto_msgTypes,
	}.Build()
	File_pkg_web_proto_route_info_proto = out.File
	file_pkg_web_proto_route_info_proto_goTypes = nil
	file_pkg_web_proto_route_info_proto_depIdxs = nil
}
