# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/web/enums/middleware_type.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gcommon/v1/web/enums/middleware_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*gcommon/v1/web/enums/middleware_type.proto\x12\x0egcommon.v1.web\x1a!google/protobuf/go_features.proto*\xea\x01\n\x0eMiddlewareType\x12\x1f\n\x1bMIDDLEWARE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17MIDDLEWARE_TYPE_LOGGING\x10\x01\x12\"\n\x1eMIDDLEWARE_TYPE_AUTHENTICATION\x10\x02\x12\x1b\n\x17MIDDLEWARE_TYPE_METRICS\x10\x03\x12\x1f\n\x1bMIDDLEWARE_TYPE_COMPRESSION\x10\x04\x12\x18\n\x14MIDDLEWARE_TYPE_CORS\x10\x05\x12\x1e\n\x1aMIDDLEWARE_TYPE_RATE_LIMIT\x10\x06\x42+Z!github.com/jdfalk/gcommon/pkg/web\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcommon.v1.web.enums.middleware_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!github.com/jdfalk/gcommon/pkg/web\222\003\005\322>\002\020\003'
  _globals['_MIDDLEWARETYPE']._serialized_start=98
  _globals['_MIDDLEWARETYPE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
