// file: webpb/v2/delete_session_request.proto
// version: 1.1.2
// guid: 90ce1e00-4c38-47bf-b246-fba60817030a

edition = "2023";

package web.v2;

import "buf/validate/validate.proto";
import "google/protobuf/go_features.proto";

option features.(pb.go).api_level = API_OPAQUE;
option go_package = "github.com/falkcorp/gcommon/v2/pkg/webpb/v2";

// DeleteSessionRequest request definition.
message WebDeleteSessionRequest {
  // Identifier of the session to delete
  string session_id = 1 [(buf.validate.field).string.min_len = 1];
}
