// file: proto/gcommon/v2/web/unregister_handler_response.proto
// version: 1.0.1
// guid: 60c00ce0-2fa0-4af1-a7ab-48b4351a72cf

edition = "2023";

package web.v2;

import "buf/validate/validate.proto";
import "google/protobuf/go_features.proto";

option features.(pb.go).api_level = API_OPAQUE;
option go_package = "github.com/falkcorp/gcommon/v2/pkg/webpb/v2";

// UnregisterHandlerResponse response definition.
message UnregisterHandlerResponse {
  string placeholder = 1 [(buf.validate.field).string.min_len = 1];
}
