// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/log/proto/messages/log_entry.proto

//go:build !protoopaque

package logpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEntry represents a single structured log event
type LogEntry struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Log level
	Level *LogLevel `protobuf:"varint,1,opt,name=level,enum=gcommon.v1.log.LogLevel" json:"level,omitempty"`
	// Log message
	Message *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// Timestamp of the log event
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// Logger name
	Logger *string `protobuf:"bytes,4,opt,name=logger" json:"logger,omitempty"`
	// Thread or goroutine identifier
	Thread *string `protobuf:"bytes,5,opt,name=thread" json:"thread,omitempty"`
	// Source code location
	Source *SourceLocation `protobuf:"bytes,6,opt,name=source" json:"source,omitempty"`
	// Structured fields for context
	Fields map[string]*anypb.Any `protobuf:"bytes,7,rep,name=fields" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tags for categorization
	Tags []string `protobuf:"bytes,8,rep,name=tags" json:"tags,omitempty"`
	// Trace ID for distributed tracing
	TraceId *string `protobuf:"bytes,9,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	// Span ID for distributed tracing
	SpanId *string `protobuf:"bytes,10,opt,name=span_id,json=spanId" json:"span_id,omitempty"`
	// User ID associated with the log
	UserId *string `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// Request ID for correlation
	RequestId *string `protobuf:"bytes,12,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	// Detailed error information
	ErrorInfo     *ErrorInfo `protobuf:"bytes,13,opt,name=error_info,json=errorInfo" json:"error_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pkg_log_proto_messages_log_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_log_proto_messages_log_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLogger() string {
	if x != nil && x.Logger != nil {
		return *x.Logger
	}
	return ""
}

func (x *LogEntry) GetThread() string {
	if x != nil && x.Thread != nil {
		return *x.Thread
	}
	return ""
}

func (x *LogEntry) GetSource() *SourceLocation {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LogEntry) GetFields() map[string]*anypb.Any {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LogEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LogEntry) GetTraceId() string {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return ""
}

func (x *LogEntry) GetSpanId() string {
	if x != nil && x.SpanId != nil {
		return *x.SpanId
	}
	return ""
}

func (x *LogEntry) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *LogEntry) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *LogEntry) GetErrorInfo() *ErrorInfo {
	if x != nil {
		return x.ErrorInfo
	}
	return nil
}

func (x *LogEntry) SetLevel(v LogLevel) {
	x.Level = &v
}

func (x *LogEntry) SetMessage(v string) {
	x.Message = &v
}

func (x *LogEntry) SetTimestamp(v *timestamppb.Timestamp) {
	x.Timestamp = v
}

func (x *LogEntry) SetLogger(v string) {
	x.Logger = &v
}

func (x *LogEntry) SetThread(v string) {
	x.Thread = &v
}

func (x *LogEntry) SetSource(v *SourceLocation) {
	x.Source = v
}

func (x *LogEntry) SetFields(v map[string]*anypb.Any) {
	x.Fields = v
}

func (x *LogEntry) SetTags(v []string) {
	x.Tags = v
}

func (x *LogEntry) SetTraceId(v string) {
	x.TraceId = &v
}

func (x *LogEntry) SetSpanId(v string) {
	x.SpanId = &v
}

func (x *LogEntry) SetUserId(v string) {
	x.UserId = &v
}

func (x *LogEntry) SetRequestId(v string) {
	x.RequestId = &v
}

func (x *LogEntry) SetErrorInfo(v *ErrorInfo) {
	x.ErrorInfo = v
}

func (x *LogEntry) HasLevel() bool {
	if x == nil {
		return false
	}
	return x.Level != nil
}

func (x *LogEntry) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *LogEntry) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.Timestamp != nil
}

func (x *LogEntry) HasLogger() bool {
	if x == nil {
		return false
	}
	return x.Logger != nil
}

func (x *LogEntry) HasThread() bool {
	if x == nil {
		return false
	}
	return x.Thread != nil
}

func (x *LogEntry) HasSource() bool {
	if x == nil {
		return false
	}
	return x.Source != nil
}

func (x *LogEntry) HasTraceId() bool {
	if x == nil {
		return false
	}
	return x.TraceId != nil
}

func (x *LogEntry) HasSpanId() bool {
	if x == nil {
		return false
	}
	return x.SpanId != nil
}

func (x *LogEntry) HasUserId() bool {
	if x == nil {
		return false
	}
	return x.UserId != nil
}

func (x *LogEntry) HasRequestId() bool {
	if x == nil {
		return false
	}
	return x.RequestId != nil
}

func (x *LogEntry) HasErrorInfo() bool {
	if x == nil {
		return false
	}
	return x.ErrorInfo != nil
}

func (x *LogEntry) ClearLevel() {
	x.Level = nil
}

func (x *LogEntry) ClearMessage() {
	x.Message = nil
}

func (x *LogEntry) ClearTimestamp() {
	x.Timestamp = nil
}

func (x *LogEntry) ClearLogger() {
	x.Logger = nil
}

func (x *LogEntry) ClearThread() {
	x.Thread = nil
}

func (x *LogEntry) ClearSource() {
	x.Source = nil
}

func (x *LogEntry) ClearTraceId() {
	x.TraceId = nil
}

func (x *LogEntry) ClearSpanId() {
	x.SpanId = nil
}

func (x *LogEntry) ClearUserId() {
	x.UserId = nil
}

func (x *LogEntry) ClearRequestId() {
	x.RequestId = nil
}

func (x *LogEntry) ClearErrorInfo() {
	x.ErrorInfo = nil
}

type LogEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Log level
	Level *LogLevel
	// Log message
	Message *string
	// Timestamp of the log event
	Timestamp *timestamppb.Timestamp
	// Logger name
	Logger *string
	// Thread or goroutine identifier
	Thread *string
	// Source code location
	Source *SourceLocation
	// Structured fields for context
	Fields map[string]*anypb.Any
	// Tags for categorization
	Tags []string
	// Trace ID for distributed tracing
	TraceId *string
	// Span ID for distributed tracing
	SpanId *string
	// User ID associated with the log
	UserId *string
	// Request ID for correlation
	RequestId *string
	// Detailed error information
	ErrorInfo *ErrorInfo
}

func (b0 LogEntry_builder) Build() *LogEntry {
	m0 := &LogEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.Level = b.Level
	x.Message = b.Message
	x.Timestamp = b.Timestamp
	x.Logger = b.Logger
	x.Thread = b.Thread
	x.Source = b.Source
	x.Fields = b.Fields
	x.Tags = b.Tags
	x.TraceId = b.TraceId
	x.SpanId = b.SpanId
	x.UserId = b.UserId
	x.RequestId = b.RequestId
	x.ErrorInfo = b.ErrorInfo
	return m0
}

var File_pkg_log_proto_messages_log_entry_proto protoreflect.FileDescriptor

const file_pkg_log_proto_messages_log_entry_proto_rawDesc = "" +
	"\n" +
	"&pkg/log/proto/messages/log_entry.proto\x12\x0egcommon.v1.log\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a#pkg/log/proto/enums/log_level.proto\x1a,pkg/log/proto/messages/source_location.proto\x1a'pkg/log/proto/messages/error_info.proto\"\xbf\x04\n" +
	"\bLogEntry\x12.\n" +
	"\x05level\x18\x01 \x01(\x0e2\x18.gcommon.v1.log.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06logger\x18\x04 \x01(\tR\x06logger\x12\x16\n" +
	"\x06thread\x18\x05 \x01(\tR\x06thread\x126\n" +
	"\x06source\x18\x06 \x01(\v2\x1e.gcommon.v1.log.SourceLocationR\x06source\x12<\n" +
	"\x06fields\x18\a \x03(\v2$.gcommon.v1.log.LogEntry.FieldsEntryR\x06fields\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\n" +
	" \x01(\tR\x06spanId\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\f \x01(\tR\trequestId\x128\n" +
	"\n" +
	"error_info\x18\r \x01(\v2\x19.gcommon.v1.log.ErrorInfoR\terrorInfo\x1aO\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01B\xb4\x01\n" +
	"\x12com.gcommon.v1.logB\rLogEntryProtoP\x01Z-github.com/jdfalk/gcommon/pkg/log/proto;logpb\xa2\x02\x03GVL\xaa\x02\x0eGcommon.V1.Log\xca\x02\x0eGcommon\\V1\\Log\xe2\x02\x1aGcommon\\V1\\Log\\GPBMetadata\xea\x02\x10Gcommon::V1::Log\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_pkg_log_proto_messages_log_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_log_proto_messages_log_entry_proto_goTypes = []any{
	(*LogEntry)(nil),              // 0: gcommon.v1.log.LogEntry
	nil,                           // 1: gcommon.v1.log.LogEntry.FieldsEntry
	(LogLevel)(0),                 // 2: gcommon.v1.log.LogLevel
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*SourceLocation)(nil),        // 4: gcommon.v1.log.SourceLocation
	(*ErrorInfo)(nil),             // 5: gcommon.v1.log.ErrorInfo
	(*anypb.Any)(nil),             // 6: google.protobuf.Any
}
var file_pkg_log_proto_messages_log_entry_proto_depIdxs = []int32{
	2, // 0: gcommon.v1.log.LogEntry.level:type_name -> gcommon.v1.log.LogLevel
	3, // 1: gcommon.v1.log.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	4, // 2: gcommon.v1.log.LogEntry.source:type_name -> gcommon.v1.log.SourceLocation
	1, // 3: gcommon.v1.log.LogEntry.fields:type_name -> gcommon.v1.log.LogEntry.FieldsEntry
	5, // 4: gcommon.v1.log.LogEntry.error_info:type_name -> gcommon.v1.log.ErrorInfo
	6, // 5: gcommon.v1.log.LogEntry.FieldsEntry.value:type_name -> google.protobuf.Any
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_log_proto_messages_log_entry_proto_init() }
func file_pkg_log_proto_messages_log_entry_proto_init() {
	if File_pkg_log_proto_messages_log_entry_proto != nil {
		return
	}
	file_pkg_log_proto_enums_log_level_proto_init()
	file_pkg_log_proto_messages_source_location_proto_init()
	file_pkg_log_proto_messages_error_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_log_proto_messages_log_entry_proto_rawDesc), len(file_pkg_log_proto_messages_log_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_log_proto_messages_log_entry_proto_goTypes,
		DependencyIndexes: file_pkg_log_proto_messages_log_entry_proto_depIdxs,
		MessageInfos:      file_pkg_log_proto_messages_log_entry_proto_msgTypes,
	}.Build()
	File_pkg_log_proto_messages_log_entry_proto = out.File
	file_pkg_log_proto_messages_log_entry_proto_goTypes = nil
	file_pkg_log_proto_messages_log_entry_proto_depIdxs = nil
}
