# file: templates/event-driven-service/Makefile
# version: 1.0.0
# guid: ad5fad76-c900-4bcd-8bdc-bcc71db3d75b

.PHONY: build test run

build:
	go build ./...

test:
	go test ./...

run:
	go run ./...
