// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/notification/proto/requests/update_preferences_request.proto

//go:build protoopaque

package notificationpb

import (
	pb "../../../../pkg/common/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Update user notification subscription preferences.
type UpdatePreferencesRequest struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Preferences *SubscriptionPreferences `protobuf:"bytes,1,opt,name=preferences"`
	xxx_hidden_Metadata    *pb.RequestMetadata      `protobuf:"bytes,2,opt,name=metadata"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_pkg_notification_proto_requests_update_preferences_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_notification_proto_requests_update_preferences_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdatePreferencesRequest) GetPreferences() *SubscriptionPreferences {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Preferences) {
				protoimpl.X.UnmarshalField(x, 1)
			}
			var rv *SubscriptionPreferences
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Preferences), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *UpdatePreferencesRequest) GetMetadata() *pb.RequestMetadata {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Metadata) {
				protoimpl.X.UnmarshalField(x, 2)
			}
			var rv *pb.RequestMetadata
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Metadata), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *UpdatePreferencesRequest) SetPreferences(v *SubscriptionPreferences) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Preferences, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
	}
}

func (x *UpdatePreferencesRequest) SetMetadata(v *pb.RequestMetadata) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Metadata, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
	}
}

func (x *UpdatePreferencesRequest) HasPreferences() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdatePreferencesRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdatePreferencesRequest) ClearPreferences() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Preferences, (*SubscriptionPreferences)(nil))
}

func (x *UpdatePreferencesRequest) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Metadata, (*pb.RequestMetadata)(nil))
}

type UpdatePreferencesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Subscription preferences to apply
	Preferences *SubscriptionPreferences
	// Request metadata for auditing
	Metadata *pb.RequestMetadata
}

func (b0 UpdatePreferencesRequest_builder) Build() *UpdatePreferencesRequest {
	m0 := &UpdatePreferencesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Preferences != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Preferences = b.Preferences
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Metadata = b.Metadata
	}
	return m0
}

var File_pkg_notification_proto_requests_update_preferences_request_proto protoreflect.FileDescriptor

const file_pkg_notification_proto_requests_update_preferences_request_proto_rawDesc = "" +
	"\n" +
	"@pkg/notification/proto/requests/update_preferences_request.proto\x12\x17gcommon.v1.notification\x1a!google/protobuf/go_features.proto\x1a0pkg/common/proto/messages/request_metadata.proto\x1a>pkg/notification/proto/messages/subscription_preferences.proto\"\xb6\x01\n" +
	"\x18UpdatePreferencesRequest\x12V\n" +
	"\vpreferences\x18\x01 \x01(\v20.gcommon.v1.notification.SubscriptionPreferencesB\x02(\x01R\vpreferences\x12B\n" +
	"\bmetadata\x18\x02 \x01(\v2\".gcommon.v1.common.RequestMetadataB\x02(\x01R\bmetadataB\xf2\x01\n" +
	"\x1bcom.gcommon.v1.notificationB\x1dUpdatePreferencesRequestProtoP\x01Z.../../../../pkg/notification/pb;notificationpb\xa2\x02\x03GVN\xaa\x02\x17Gcommon.V1.Notification\xca\x02\x17Gcommon\\V1\\Notification\xe2\x02#Gcommon\\V1\\Notification\\GPBMetadata\xea\x02\x19Gcommon::V1::Notification\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_pkg_notification_proto_requests_update_preferences_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_notification_proto_requests_update_preferences_request_proto_goTypes = []any{
	(*UpdatePreferencesRequest)(nil), // 0: gcommon.v1.notification.UpdatePreferencesRequest
	(*SubscriptionPreferences)(nil),  // 1: gcommon.v1.notification.SubscriptionPreferences
	(*pb.RequestMetadata)(nil),       // 2: gcommon.v1.common.RequestMetadata
}
var file_pkg_notification_proto_requests_update_preferences_request_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.notification.UpdatePreferencesRequest.preferences:type_name -> gcommon.v1.notification.SubscriptionPreferences
	2, // 1: gcommon.v1.notification.UpdatePreferencesRequest.metadata:type_name -> gcommon.v1.common.RequestMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_notification_proto_requests_update_preferences_request_proto_init() }
func file_pkg_notification_proto_requests_update_preferences_request_proto_init() {
	if File_pkg_notification_proto_requests_update_preferences_request_proto != nil {
		return
	}
	file_pkg_notification_proto_messages_subscription_preferences_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_notification_proto_requests_update_preferences_request_proto_rawDesc), len(file_pkg_notification_proto_requests_update_preferences_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_notification_proto_requests_update_preferences_request_proto_goTypes,
		DependencyIndexes: file_pkg_notification_proto_requests_update_preferences_request_proto_depIdxs,
		MessageInfos:      file_pkg_notification_proto_requests_update_preferences_request_proto_msgTypes,
	}.Build()
	File_pkg_notification_proto_requests_update_preferences_request_proto = out.File
	file_pkg_notification_proto_requests_update_preferences_request_proto_goTypes = nil
	file_pkg_notification_proto_requests_update_preferences_request_proto_depIdxs = nil
}
