from gcommon.v1.media.messages import analyze_media_request_pb2 as _analyze_media_request_pb2
from gcommon.v1.media.messages import analyze_media_response_pb2 as _analyze_media_response_pb2
from gcommon.v1.media.messages import extract_audio_request_pb2 as _extract_audio_request_pb2
from gcommon.v1.media.messages import extract_audio_response_pb2 as _extract_audio_response_pb2
from gcommon.v1.media.messages import extract_subtitles_request_pb2 as _extract_subtitles_request_pb2
from gcommon.v1.media.messages import extract_subtitles_response_pb2 as _extract_subtitles_response_pb2
from gcommon.v1.media.messages import get_processing_status_request_pb2 as _get_processing_status_request_pb2
from gcommon.v1.media.messages import get_processing_status_response_pb2 as _get_processing_status_response_pb2
from gcommon.v1.media.messages import transcode_media_request_pb2 as _transcode_media_request_pb2
from gcommon.v1.media.messages import transcode_media_response_pb2 as _transcode_media_response_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
