from gcommon.v1.media.messages import adjust_subtitle_timing_request_pb2 as _adjust_subtitle_timing_request_pb2
from gcommon.v1.media.messages import adjust_subtitle_timing_response_pb2 as _adjust_subtitle_timing_response_pb2
from gcommon.v1.media.messages import convert_subtitle_format_request_pb2 as _convert_subtitle_format_request_pb2
from gcommon.v1.media.messages import convert_subtitle_format_response_pb2 as _convert_subtitle_format_response_pb2
from gcommon.v1.media.messages import merge_subtitles_request_pb2 as _merge_subtitles_request_pb2
from gcommon.v1.media.messages import merge_subtitles_response_pb2 as _merge_subtitles_response_pb2
from gcommon.v1.media.messages import sync_subtitles_request_pb2 as _sync_subtitles_request_pb2
from gcommon.v1.media.messages import sync_subtitles_response_pb2 as _sync_subtitles_response_pb2
from gcommon.v1.media.messages import validate_subtitles_request_pb2 as _validate_subtitles_request_pb2
from gcommon.v1.media.messages import validate_subtitles_response_pb2 as _validate_subtitles_response_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
