// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gcommon/v1/config/messages/compliance_reporting.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComplianceReporting struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled        bool                   `protobuf:"varint,1,opt,name=enabled"`
	xxx_hidden_FrequencyHours int32                  `protobuf:"varint,2,opt,name=frequency_hours,json=frequencyHours"`
	xxx_hidden_Recipients     []string               `protobuf:"bytes,3,rep,name=recipients"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ComplianceReporting) Reset() {
	*x = ComplianceReporting{}
	mi := &file_gcommon_v1_config_messages_compliance_reporting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceReporting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceReporting) ProtoMessage() {}

func (x *ComplianceReporting) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_config_messages_compliance_reporting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComplianceReporting) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *ComplianceReporting) GetFrequencyHours() int32 {
	if x != nil {
		return x.xxx_hidden_FrequencyHours
	}
	return 0
}

func (x *ComplianceReporting) GetRecipients() []string {
	if x != nil {
		return x.xxx_hidden_Recipients
	}
	return nil
}

func (x *ComplianceReporting) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ComplianceReporting) SetFrequencyHours(v int32) {
	x.xxx_hidden_FrequencyHours = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ComplianceReporting) SetRecipients(v []string) {
	x.xxx_hidden_Recipients = v
}

func (x *ComplianceReporting) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ComplianceReporting) HasFrequencyHours() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ComplianceReporting) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Enabled = false
}

func (x *ComplianceReporting) ClearFrequencyHours() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_FrequencyHours = 0
}

type ComplianceReporting_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Reporting enabled status
	Enabled *bool
	// Report frequency in hours
	FrequencyHours *int32
	// Report recipients
	Recipients []string
}

func (b0 ComplianceReporting_builder) Build() *ComplianceReporting {
	m0 := &ComplianceReporting{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.FrequencyHours != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_FrequencyHours = *b.FrequencyHours
	}
	x.xxx_hidden_Recipients = b.Recipients
	return m0
}

var File_gcommon_v1_config_messages_compliance_reporting_proto protoreflect.FileDescriptor

const file_gcommon_v1_config_messages_compliance_reporting_proto_rawDesc = "" +
	"\n" +
	"5gcommon/v1/config/messages/compliance_reporting.proto\x12\x11gcommon.v1.config\x1a!google/protobuf/go_features.proto\"x\n" +
	"\x13ComplianceReporting\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12'\n" +
	"\x0ffrequency_hours\x18\x02 \x01(\x05R\x0efrequencyHours\x12\x1e\n" +
	"\n" +
	"recipients\x18\x03 \x03(\tR\n" +
	"recipientsB.Z$github.com/jdfalk/gcommon/pkg/config\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_config_messages_compliance_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gcommon_v1_config_messages_compliance_reporting_proto_goTypes = []any{
	(*ComplianceReporting)(nil), // 0: gcommon.v1.config.ComplianceReporting
}
var file_gcommon_v1_config_messages_compliance_reporting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gcommon_v1_config_messages_compliance_reporting_proto_init() }
func file_gcommon_v1_config_messages_compliance_reporting_proto_init() {
	if File_gcommon_v1_config_messages_compliance_reporting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_config_messages_compliance_reporting_proto_rawDesc), len(file_gcommon_v1_config_messages_compliance_reporting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_config_messages_compliance_reporting_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_config_messages_compliance_reporting_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_config_messages_compliance_reporting_proto_msgTypes,
	}.Build()
	File_gcommon_v1_config_messages_compliance_reporting_proto = out.File
	file_gcommon_v1_config_messages_compliance_reporting_proto_goTypes = nil
	file_gcommon_v1_config_messages_compliance_reporting_proto_depIdxs = nil
}
