// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gcommon/v1/config/messages/inheritance_transformation.proto

package messages

import (
	enums "github.com/jdfalk/gcommon/sdks/go/gcommon/v1/config/enums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InheritanceTransformation struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Type        enums.TransformationType `protobuf:"varint,1,opt,name=type,enum=gcommon.v1.config.TransformationType"`
	xxx_hidden_Expression  *string                  `protobuf:"bytes,2,opt,name=expression"`
	xxx_hidden_Parameters  map[string]string        `protobuf:"bytes,3,rep,name=parameters" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Metadata    map[string]string        `protobuf:"bytes,4,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InheritanceTransformation) Reset() {
	*x = InheritanceTransformation{}
	mi := &file_gcommon_v1_config_messages_inheritance_transformation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InheritanceTransformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InheritanceTransformation) ProtoMessage() {}

func (x *InheritanceTransformation) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_config_messages_inheritance_transformation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InheritanceTransformation) GetType() enums.TransformationType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return enums.TransformationType(0)
}

func (x *InheritanceTransformation) GetExpression() string {
	if x != nil {
		if x.xxx_hidden_Expression != nil {
			return *x.xxx_hidden_Expression
		}
		return ""
	}
	return ""
}

func (x *InheritanceTransformation) GetParameters() map[string]string {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return nil
}

func (x *InheritanceTransformation) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *InheritanceTransformation) SetType(v enums.TransformationType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *InheritanceTransformation) SetExpression(v string) {
	x.xxx_hidden_Expression = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *InheritanceTransformation) SetParameters(v map[string]string) {
	x.xxx_hidden_Parameters = v
}

func (x *InheritanceTransformation) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *InheritanceTransformation) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InheritanceTransformation) HasExpression() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InheritanceTransformation) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = enums.TransformationType_TRANSFORMATION_TYPE_UNSPECIFIED
}

func (x *InheritanceTransformation) ClearExpression() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Expression = nil
}

type InheritanceTransformation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Transformation type
	Type *enums.TransformationType
	// Transformation expression
	Expression *string
	// Transformation parameters
	Parameters map[string]string
	// Transformation metadata
	Metadata map[string]string
}

func (b0 InheritanceTransformation_builder) Build() *InheritanceTransformation {
	m0 := &InheritanceTransformation{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Expression != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Expression = b.Expression
	}
	x.xxx_hidden_Parameters = b.Parameters
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

var File_gcommon_v1_config_messages_inheritance_transformation_proto protoreflect.FileDescriptor

const file_gcommon_v1_config_messages_inheritance_transformation_proto_rawDesc = "" +
	"\n" +
	";gcommon/v1/config/messages/inheritance_transformation.proto\x12\x11gcommon.v1.config\x1a1gcommon/v1/config/enums/transformation_type.proto\x1a!google/protobuf/go_features.proto\"\xa8\x03\n" +
	"\x19InheritanceTransformation\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.gcommon.v1.config.TransformationTypeR\x04type\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x12\\\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2<.gcommon.v1.config.InheritanceTransformation.ParametersEntryR\n" +
	"parameters\x12V\n" +
	"\bmetadata\x18\x04 \x03(\v2:.gcommon.v1.config.InheritanceTransformation.MetadataEntryR\bmetadata\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xe3\x01\n" +
	"\x15com.gcommon.v1.configB\x1eInheritanceTransformationProtoP\x01Z<github.com/jdfalk/gcommon/sdks/go/gcommon/v1/config/messages\xa2\x02\x03GVC\xaa\x02\x11Gcommon.V1.Config\xca\x02\x11Gcommon\\V1\\Config\xe2\x02\x1dGcommon\\V1\\Config\\GPBMetadata\xea\x02\x13Gcommon::V1::Config\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_config_messages_inheritance_transformation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gcommon_v1_config_messages_inheritance_transformation_proto_goTypes = []any{
	(*InheritanceTransformation)(nil), // 0: gcommon.v1.config.InheritanceTransformation
	nil,                               // 1: gcommon.v1.config.InheritanceTransformation.ParametersEntry
	nil,                               // 2: gcommon.v1.config.InheritanceTransformation.MetadataEntry
	(enums.TransformationType)(0),     // 3: gcommon.v1.config.TransformationType
}
var file_gcommon_v1_config_messages_inheritance_transformation_proto_depIdxs = []int32{
	3, // 0: gcommon.v1.config.InheritanceTransformation.type:type_name -> gcommon.v1.config.TransformationType
	1, // 1: gcommon.v1.config.InheritanceTransformation.parameters:type_name -> gcommon.v1.config.InheritanceTransformation.ParametersEntry
	2, // 2: gcommon.v1.config.InheritanceTransformation.metadata:type_name -> gcommon.v1.config.InheritanceTransformation.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gcommon_v1_config_messages_inheritance_transformation_proto_init() }
func file_gcommon_v1_config_messages_inheritance_transformation_proto_init() {
	if File_gcommon_v1_config_messages_inheritance_transformation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_config_messages_inheritance_transformation_proto_rawDesc), len(file_gcommon_v1_config_messages_inheritance_transformation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_config_messages_inheritance_transformation_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_config_messages_inheritance_transformation_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_config_messages_inheritance_transformation_proto_msgTypes,
	}.Build()
	File_gcommon_v1_config_messages_inheritance_transformation_proto = out.File
	file_gcommon_v1_config_messages_inheritance_transformation_proto_goTypes = nil
	file_gcommon_v1_config_messages_inheritance_transformation_proto_depIdxs = nil
}
