# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcommon/v1/organization/messages/add_member_request.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gcommon/v1/organization/messages/add_member_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gcommon.v1.common.messages import request_metadata_pb2 as gcommon_dot_v1_dot_common_dot_messages_dot_request__metadata__pb2
from gcommon.v1.organization.messages import organization_member_pb2 as gcommon_dot_v1_dot_organization_dot_messages_dot_organization__member__pb2
from google.protobuf import go_features_pb2 as google_dot_protobuf_dot_go__features__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9gcommon/v1/organization/messages/add_member_request.proto\x12\x17gcommon.v1.organization\x1a\x31gcommon/v1/common/messages/request_metadata.proto\x1a:gcommon/v1/organization/messages/organization_member.proto\x1a!google/protobuf/go_features.proto\"\xe1\x01\n\x10\x41\x64\x64MemberRequest\x12>\n\x08metadata\x18\x01 \x01(\x0b\x32\".gcommon.v1.common.RequestMetadataR\x08metadata\x12\'\n\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x43\n\x06member\x18\x03 \x01(\x0b\x32+.gcommon.v1.organization.OrganizationMemberR\x06member\x12\x1f\n\x0bsend_invite\x18\x04 \x01(\x08R\nsendInviteB\x19Z\x0fv1/organization\x92\x03\x05\xd2>\x02\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcommon.v1.organization.messages.add_member_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017v1/organization\222\003\005\322>\002\020\003'
  _globals['_ADDMEMBERREQUEST']._serialized_start=233
  _globals['_ADDMEMBERREQUEST']._serialized_end=458
# @@protoc_insertion_point(module_scope)
