// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gcommon/v1/metrics/label_definition.proto

package metrics

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LabelDefinition struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name              *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Description       *string                `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Required          bool                   `protobuf:"varint,3,opt,name=required"`
	xxx_hidden_AllowedValues     []string               `protobuf:"bytes,4,rep,name=allowed_values,json=allowedValues"`
	xxx_hidden_ValidationPattern *string                `protobuf:"bytes,5,opt,name=validation_pattern,json=validationPattern"`
	xxx_hidden_DefaultValue      *string                `protobuf:"bytes,6,opt,name=default_value,json=defaultValue"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *LabelDefinition) Reset() {
	*x = LabelDefinition{}
	mi := &file_gcommon_v1_metrics_label_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelDefinition) ProtoMessage() {}

func (x *LabelDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_metrics_label_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LabelDefinition) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *LabelDefinition) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *LabelDefinition) GetRequired() bool {
	if x != nil {
		return x.xxx_hidden_Required
	}
	return false
}

func (x *LabelDefinition) GetAllowedValues() []string {
	if x != nil {
		return x.xxx_hidden_AllowedValues
	}
	return nil
}

func (x *LabelDefinition) GetValidationPattern() string {
	if x != nil {
		if x.xxx_hidden_ValidationPattern != nil {
			return *x.xxx_hidden_ValidationPattern
		}
		return ""
	}
	return ""
}

func (x *LabelDefinition) GetDefaultValue() string {
	if x != nil {
		if x.xxx_hidden_DefaultValue != nil {
			return *x.xxx_hidden_DefaultValue
		}
		return ""
	}
	return ""
}

func (x *LabelDefinition) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *LabelDefinition) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *LabelDefinition) SetRequired(v bool) {
	x.xxx_hidden_Required = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *LabelDefinition) SetAllowedValues(v []string) {
	x.xxx_hidden_AllowedValues = v
}

func (x *LabelDefinition) SetValidationPattern(v string) {
	x.xxx_hidden_ValidationPattern = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *LabelDefinition) SetDefaultValue(v string) {
	x.xxx_hidden_DefaultValue = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *LabelDefinition) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LabelDefinition) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LabelDefinition) HasRequired() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *LabelDefinition) HasValidationPattern() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *LabelDefinition) HasDefaultValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *LabelDefinition) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *LabelDefinition) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *LabelDefinition) ClearRequired() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Required = false
}

func (x *LabelDefinition) ClearValidationPattern() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ValidationPattern = nil
}

func (x *LabelDefinition) ClearDefaultValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_DefaultValue = nil
}

type LabelDefinition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the label
	Name *string
	// Description of what this label represents
	Description *string
	// Whether this label is required
	Required *bool
	// Allowed values for this label (empty = any value allowed)
	AllowedValues []string
	// Pattern for validating label values (regex)
	ValidationPattern *string
	// Default value if not specified
	DefaultValue *string
}

func (b0 LabelDefinition_builder) Build() *LabelDefinition {
	m0 := &LabelDefinition{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Description = b.Description
	}
	if b.Required != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Required = *b.Required
	}
	x.xxx_hidden_AllowedValues = b.AllowedValues
	if b.ValidationPattern != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_ValidationPattern = b.ValidationPattern
	}
	if b.DefaultValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_DefaultValue = b.DefaultValue
	}
	return m0
}

var File_gcommon_v1_metrics_label_definition_proto protoreflect.FileDescriptor

const file_gcommon_v1_metrics_label_definition_proto_rawDesc = "" +
	"\n" +
	")gcommon/v1/metrics/label_definition.proto\x12\x12gcommon.v1.metrics\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xf3\x01\n" +
	"\x0fLabelDefinition\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x04name\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12%\n" +
	"\x0eallowed_values\x18\x04 \x03(\tR\rallowedValues\x12-\n" +
	"\x12validation_pattern\x18\x05 \x01(\tR\x11validationPattern\x12#\n" +
	"\rdefault_value\x18\x06 \x01(\tR\fdefaultValueB6Z,github.com/jdfalk/gcommon/sdks/go/v1/metrics\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_metrics_label_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gcommon_v1_metrics_label_definition_proto_goTypes = []any{
	(*LabelDefinition)(nil), // 0: gcommon.v1.metrics.LabelDefinition
}
var file_gcommon_v1_metrics_label_definition_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gcommon_v1_metrics_label_definition_proto_init() }
func file_gcommon_v1_metrics_label_definition_proto_init() {
	if File_gcommon_v1_metrics_label_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_metrics_label_definition_proto_rawDesc), len(file_gcommon_v1_metrics_label_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_metrics_label_definition_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_metrics_label_definition_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_metrics_label_definition_proto_msgTypes,
	}.Build()
	File_gcommon_v1_metrics_label_definition_proto = out.File
	file_gcommon_v1_metrics_label_definition_proto_goTypes = nil
	file_gcommon_v1_metrics_label_definition_proto_depIdxs = nil
}
