# file: deploy/helm/gcommon-app/templates/monitoring.yaml
# version: 1.0.0
# guid: 9e237279-8b48-4100-bc5e-30a0d8439df7

{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gcommon-app.fullname" . }}
  labels:
    {{- include "gcommon-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gcommon-app.selectorLabels" . | nindent 8 }}
  endpoints:
    - port: http
      interval: {{ .Values.monitoring.prometheus.scrapeInterval }}
{{- end }}
