# file: deploy/helm/gcommon-app/templates/networkpolicy.yaml
# version: 1.0.0
# guid: c1234567-89ab-4cde-f012-3456789abcde

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gcommon-app.fullname" . }}-policy
  labels:
    {{- include "gcommon-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "gcommon-app.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "gcommon-app.name" . }}
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 9090
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app: db
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app: cache
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 10.1.0.0/16
      ports:
        - protocol: TCP
          port: 9200
        - protocol: TCP
          port: 9300
    - to:
        - ipBlock:
            cidr: 10.2.0.0/16
      ports:
        - protocol: TCP
          port: 27017
        - protocol: TCP
          port: 27018
    - to:
        - ipBlock:
            cidr: 10.3.0.0/16
      ports:
        - protocol: TCP
          port: 11211
        - protocol: TCP
          port: 11212
    - to:
        - podSelector:
            matchLabels:
              app: tracing
      ports:
        - protocol: TCP
          port: 14250
        - protocol: TCP
          port: 16686
    - to:
        - podSelector:
            matchLabels:
              app: metrics
      ports:
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 9091
    - to:
        - ipBlock:
            cidr: 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 25
        - protocol: TCP
          port: 587
    - to:
        - namespaceSelector:
            matchLabels:
              name: logging
      ports:
        - protocol: TCP
          port: 24224
        - protocol: TCP
          port: 24220
    - to:
        - podSelector:
            matchLabels:
              app: telemetry
      ports:
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 55681
    - to:
        - ipBlock:
            cidr: 10.4.0.0/16
      ports:
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 8082
    - to:
        - ipBlock:
            cidr: 10.5.0.0/16
      ports:
        - protocol: TCP
          port: 1883
        - protocol: TCP
          port: 8883
    - to:
        - ipBlock:
            cidr: 10.6.0.0/16
      ports:
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 3307
    - to:
        - ipBlock:
            cidr: 10.7.0.0/16
      ports:
        - protocol: TCP
          port: 5000
        - protocol: TCP
          port: 5001
    - to:
        - ipBlock:
            cidr: 10.8.0.0/16
      ports:
        - protocol: TCP
          port: 8083
        - protocol: TCP
          port: 8084
    - to:
        - ipBlock:
            cidr: 10.9.0.0/16
      ports:
        - protocol: TCP
          port: 10250
        - protocol: TCP
          port: 10255
    - to:
        - podSelector:
            matchLabels:
              app: messaging
      ports:
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 15672
    - to:
        - podSelector:
            matchLabels:
              app: analytics
      ports:
        - protocol: TCP
          port: 8088
        - protocol: TCP
          port: 8090
    - to:
        - ipBlock:
            cidr: 10.10.0.0/16
      ports:
        - protocol: TCP
          port: 7000
        - protocol: TCP
          port: 7001
    - to:
        - ipBlock:
            cidr: 10.11.0.0/16
      ports:
        - protocol: TCP
          port: 7100
        - protocol: TCP
          port: 7101
    - to:
        - ipBlock:
            cidr: 10.12.0.0/16
      ports:
        - protocol: TCP
          port: 7200
        - protocol: TCP
          port: 7201
    - to:
        - ipBlock:
            cidr: 10.13.0.0/16
      ports:
        - protocol: TCP
          port: 7300
        - protocol: TCP
          port: 7301
    - to:
        - ipBlock:
            cidr: 10.14.0.0/16
      ports:
        - protocol: TCP
          port: 7400
        - protocol: TCP
          port: 7401
    - to:
        - ipBlock:
            cidr: 10.15.0.0/16
      ports:
        - protocol: TCP
          port: 7500
        - protocol: TCP
          port: 7501
    - to:
        - ipBlock:
            cidr: 10.16.0.0/16
      ports:
        - protocol: TCP
          port: 7600
        - protocol: TCP
          port: 7601
    - to:
        - ipBlock:
            cidr: 10.17.0.0/16
      ports:
        - protocol: TCP
          port: 7700
        - protocol: TCP
          port: 7701
    - to:
        - ipBlock:
            cidr: 10.18.0.0/16
      ports:
        - protocol: TCP
          port: 7800
        - protocol: TCP
          port: 7801
    - to:
        - ipBlock:
            cidr: 10.19.0.0/16
      ports:
        - protocol: TCP
          port: 7900
        - protocol: TCP
          port: 7901
    - to:
        - ipBlock:
            cidr: 10.20.0.0/16
      ports:
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 8001
    - to:
        - ipBlock:
            cidr: 10.21.0.0/16
      ports:
        - protocol: TCP
          port: 8100
        - protocol: TCP
          port: 8101
    - to:
        - ipBlock:
            cidr: 10.22.0.0/16
      ports:
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 8201

