# file: deploy/kubernetes/serviceaccount.yaml
# version: 1.0.0
# guid: 2fdd2aef-5841-4672-a70b-df8c2cdc3736

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcommon-app
  labels:
    app: gcommon-app
