# file: templates/event-driven-service/deploy/service.yaml
# version: 1.0.0
# guid: 1986b92b-7063-46c4-8502-17ce6cef6b92

apiVersion: v1
kind: Service
metadata:
  name: event-driven-service
spec:
  selector:
    app: event-driven-service
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
  type: ClusterIP
