# file: deploy/automation/argocd-app.yaml
# version: 1.0.0
# guid: 9dcc7e6d-aa01-4543-80c9-0ea53520d69d

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcommon-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jdfalk/gcommon
    path: deploy/helm/gcommon-app
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gcommon
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
