# file: deploy/automation/canary.yaml
# version: 1.0.0
# guid: a446d96e-6519-469c-9a6c-1a8e780f07aa

apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: gcommon-app
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gcommon-app
  service:
    port: 80
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: request-success-rate
        threshold: 99
        interval: 1m
      - name: request-duration
        threshold: 500
        interval: 1m
