# file: deploy/automation/fluxcd-app.yaml
# version: 1.1.0
# guid: 73a3ef15-94e0-4e95-baa2-e15debf3a2f5

# FluxCD GitOps configuration for gcommon applications.
# Defines source repositories and automated deployment kustomizations.

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gcommon-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/example/gcommon-app
  ref:
    branch: main
  secretRef:
    name: flux-git-deploy
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gcommon-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./deploy/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: gcommon-app
  targetNamespace: gcommon
  timeout: 2m
  wait: true
  postBuild:
    substitute:
      IMAGE: ghcr.io/jdfalk/gcommon-app:latest
      REPLICA_COUNT: "3"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: gcommon-app
  namespace: flux-system
spec:
  image: ghcr.io/jdfalk/gcommon-app
  interval: 5m

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: gcommon-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gcommon-app
  policy:
    semver:
      range: 1.x

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: gcommon-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: gcommon-app
  interval: 1m
  update:
    strategy: Setters
    path: ./deploy/kubernetes
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcd@example.com
        name: fluxcd-bot
      messageTemplate: "chore: update image to {{range .Updated.Images}}{{.}}{{end}}"
    push:
      branch: main

---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: deployments
  address: ${{ secrets.SLACK_WEBHOOK }}

---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: gcommon-alerts
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: gcommon-app

---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: gcommon-app
  namespace: gcommon
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gcommon-app
  service:
    port: 8080
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 30s
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 30s

---
# Example for multi-cluster deployment using Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gcommon-app-eu
  namespace: flux-system
spec:
  interval: 5m
  path: ./deploy/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: gcommon-app
  targetNamespace: gcommon
  timeout: 2m
  kubeConfig:
    secretRef:
      name: gcommon-eu-kubeconfig

---
# Rollback strategy documentation
# In case of failure, the previous Git commit can be restored by running:
#   flux rollback kustomization gcommon-app --to-revision=<commit>
