// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gcommon/v1/common/organization_compliance_settings.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationComplianceSettings struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GdprEnabled         bool                   `protobuf:"varint,1,opt,name=gdpr_enabled,json=gdprEnabled"`
	xxx_hidden_DataRetentionDays   int32                  `protobuf:"varint,2,opt,name=data_retention_days,json=dataRetentionDays"`
	xxx_hidden_DataExportEnabled   bool                   `protobuf:"varint,3,opt,name=data_export_enabled,json=dataExportEnabled"`
	xxx_hidden_DataDeletionEnabled bool                   `protobuf:"varint,4,opt,name=data_deletion_enabled,json=dataDeletionEnabled"`
	xxx_hidden_Certifications      []string               `protobuf:"bytes,5,rep,name=certifications"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *OrganizationComplianceSettings) Reset() {
	*x = OrganizationComplianceSettings{}
	mi := &file_gcommon_v1_common_organization_compliance_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationComplianceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationComplianceSettings) ProtoMessage() {}

func (x *OrganizationComplianceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_common_organization_compliance_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OrganizationComplianceSettings) GetGdprEnabled() bool {
	if x != nil {
		return x.xxx_hidden_GdprEnabled
	}
	return false
}

func (x *OrganizationComplianceSettings) GetDataRetentionDays() int32 {
	if x != nil {
		return x.xxx_hidden_DataRetentionDays
	}
	return 0
}

func (x *OrganizationComplianceSettings) GetDataExportEnabled() bool {
	if x != nil {
		return x.xxx_hidden_DataExportEnabled
	}
	return false
}

func (x *OrganizationComplianceSettings) GetDataDeletionEnabled() bool {
	if x != nil {
		return x.xxx_hidden_DataDeletionEnabled
	}
	return false
}

func (x *OrganizationComplianceSettings) GetCertifications() []string {
	if x != nil {
		return x.xxx_hidden_Certifications
	}
	return nil
}

func (x *OrganizationComplianceSettings) SetGdprEnabled(v bool) {
	x.xxx_hidden_GdprEnabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *OrganizationComplianceSettings) SetDataRetentionDays(v int32) {
	x.xxx_hidden_DataRetentionDays = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *OrganizationComplianceSettings) SetDataExportEnabled(v bool) {
	x.xxx_hidden_DataExportEnabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *OrganizationComplianceSettings) SetDataDeletionEnabled(v bool) {
	x.xxx_hidden_DataDeletionEnabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *OrganizationComplianceSettings) SetCertifications(v []string) {
	x.xxx_hidden_Certifications = v
}

func (x *OrganizationComplianceSettings) HasGdprEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OrganizationComplianceSettings) HasDataRetentionDays() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OrganizationComplianceSettings) HasDataExportEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OrganizationComplianceSettings) HasDataDeletionEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *OrganizationComplianceSettings) ClearGdprEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_GdprEnabled = false
}

func (x *OrganizationComplianceSettings) ClearDataRetentionDays() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DataRetentionDays = 0
}

func (x *OrganizationComplianceSettings) ClearDataExportEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_DataExportEnabled = false
}

func (x *OrganizationComplianceSettings) ClearDataDeletionEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_DataDeletionEnabled = false
}

type OrganizationComplianceSettings_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// GDPR compliance enabled
	GdprEnabled *bool
	// Data retention period in days
	DataRetentionDays *int32
	// Whether data export is allowed
	DataExportEnabled *bool
	// Whether data deletion is allowed
	DataDeletionEnabled *bool
	// Compliance certifications
	Certifications []string
}

func (b0 OrganizationComplianceSettings_builder) Build() *OrganizationComplianceSettings {
	m0 := &OrganizationComplianceSettings{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GdprEnabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_GdprEnabled = *b.GdprEnabled
	}
	if b.DataRetentionDays != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_DataRetentionDays = *b.DataRetentionDays
	}
	if b.DataExportEnabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_DataExportEnabled = *b.DataExportEnabled
	}
	if b.DataDeletionEnabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_DataDeletionEnabled = *b.DataDeletionEnabled
	}
	x.xxx_hidden_Certifications = b.Certifications
	return m0
}

var File_gcommon_v1_common_organization_compliance_settings_proto protoreflect.FileDescriptor

const file_gcommon_v1_common_organization_compliance_settings_proto_rawDesc = "" +
	"\n" +
	"8gcommon/v1/common/organization_compliance_settings.proto\x12\x11gcommon.v1.common\x1a!google/protobuf/go_features.proto\"\xff\x01\n" +
	"\x1eOrganizationComplianceSettings\x12!\n" +
	"\fgdpr_enabled\x18\x01 \x01(\bR\vgdprEnabled\x12.\n" +
	"\x13data_retention_days\x18\x02 \x01(\x05R\x11dataRetentionDays\x12.\n" +
	"\x13data_export_enabled\x18\x03 \x01(\bR\x11dataExportEnabled\x122\n" +
	"\x15data_deletion_enabled\x18\x04 \x01(\bR\x13dataDeletionEnabled\x12&\n" +
	"\x0ecertifications\x18\x05 \x03(\tR\x0ecertificationsB4Z*github.com/jdfalk/gcommon/sdk/go/v1/common\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_common_organization_compliance_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gcommon_v1_common_organization_compliance_settings_proto_goTypes = []any{
	(*OrganizationComplianceSettings)(nil), // 0: gcommon.v1.common.OrganizationComplianceSettings
}
var file_gcommon_v1_common_organization_compliance_settings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gcommon_v1_common_organization_compliance_settings_proto_init() }
func file_gcommon_v1_common_organization_compliance_settings_proto_init() {
	if File_gcommon_v1_common_organization_compliance_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_common_organization_compliance_settings_proto_rawDesc), len(file_gcommon_v1_common_organization_compliance_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_common_organization_compliance_settings_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_common_organization_compliance_settings_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_common_organization_compliance_settings_proto_msgTypes,
	}.Build()
	File_gcommon_v1_common_organization_compliance_settings_proto = out.File
	file_gcommon_v1_common_organization_compliance_settings_proto_goTypes = nil
	file_gcommon_v1_common_organization_compliance_settings_proto_depIdxs = nil
}
