// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: gcommon/v1/common/mfa_config.proto

package common

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Multi-factor authentication configuration settings.
type MfaConfig struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled      bool                   `protobuf:"varint,1,opt,name=enabled"`
	xxx_hidden_Methods      []string               `protobuf:"bytes,2,rep,name=methods"`
	xxx_hidden_TotpPeriod   int32                  `protobuf:"varint,3,opt,name=totp_period,json=totpPeriod"`
	xxx_hidden_TotpDigits   int32                  `protobuf:"varint,4,opt,name=totp_digits,json=totpDigits"`
	xxx_hidden_SmsEnabled   bool                   `protobuf:"varint,5,opt,name=sms_enabled,json=smsEnabled"`
	xxx_hidden_EmailEnabled bool                   `protobuf:"varint,6,opt,name=email_enabled,json=emailEnabled"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MfaConfig) Reset() {
	*x = MfaConfig{}
	mi := &file_gcommon_v1_common_mfa_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaConfig) ProtoMessage() {}

func (x *MfaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_common_mfa_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MfaConfig) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *MfaConfig) GetMethods() []string {
	if x != nil {
		return x.xxx_hidden_Methods
	}
	return nil
}

func (x *MfaConfig) GetTotpPeriod() int32 {
	if x != nil {
		return x.xxx_hidden_TotpPeriod
	}
	return 0
}

func (x *MfaConfig) GetTotpDigits() int32 {
	if x != nil {
		return x.xxx_hidden_TotpDigits
	}
	return 0
}

func (x *MfaConfig) GetSmsEnabled() bool {
	if x != nil {
		return x.xxx_hidden_SmsEnabled
	}
	return false
}

func (x *MfaConfig) GetEmailEnabled() bool {
	if x != nil {
		return x.xxx_hidden_EmailEnabled
	}
	return false
}

func (x *MfaConfig) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *MfaConfig) SetMethods(v []string) {
	x.xxx_hidden_Methods = v
}

func (x *MfaConfig) SetTotpPeriod(v int32) {
	x.xxx_hidden_TotpPeriod = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *MfaConfig) SetTotpDigits(v int32) {
	x.xxx_hidden_TotpDigits = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *MfaConfig) SetSmsEnabled(v bool) {
	x.xxx_hidden_SmsEnabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *MfaConfig) SetEmailEnabled(v bool) {
	x.xxx_hidden_EmailEnabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *MfaConfig) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MfaConfig) HasTotpPeriod() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MfaConfig) HasTotpDigits() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *MfaConfig) HasSmsEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *MfaConfig) HasEmailEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *MfaConfig) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Enabled = false
}

func (x *MfaConfig) ClearTotpPeriod() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_TotpPeriod = 0
}

func (x *MfaConfig) ClearTotpDigits() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TotpDigits = 0
}

func (x *MfaConfig) ClearSmsEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_SmsEnabled = false
}

func (x *MfaConfig) ClearEmailEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_EmailEnabled = false
}

type MfaConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether MFA is enabled.
	Enabled *bool
	// Supported MFA methods (e.g., "totp", "sms", "email").
	Methods []string
	// Time-based one-time password period in seconds.
	TotpPeriod *int32
	// Number of digits for TOTP codes.
	TotpDigits *int32
	// Whether SMS delivery is enabled.
	SmsEnabled *bool
	// Whether email delivery is enabled.
	EmailEnabled *bool
}

func (b0 MfaConfig_builder) Build() *MfaConfig {
	m0 := &MfaConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	x.xxx_hidden_Methods = b.Methods
	if b.TotpPeriod != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_TotpPeriod = *b.TotpPeriod
	}
	if b.TotpDigits != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_TotpDigits = *b.TotpDigits
	}
	if b.SmsEnabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_SmsEnabled = *b.SmsEnabled
	}
	if b.EmailEnabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_EmailEnabled = *b.EmailEnabled
	}
	return m0
}

var File_gcommon_v1_common_mfa_config_proto protoreflect.FileDescriptor

const file_gcommon_v1_common_mfa_config_proto_rawDesc = "" +
	"\n" +
	"\"gcommon/v1/common/mfa_config.proto\x12\x11gcommon.v1.common\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xe3\x01\n" +
	"\tMfaConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\"\n" +
	"\amethods\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\amethods\x12(\n" +
	"\vtotp_period\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\n" +
	"totpPeriod\x12(\n" +
	"\vtotp_digits\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\n" +
	"totpDigits\x12\x1f\n" +
	"\vsms_enabled\x18\x05 \x01(\bR\n" +
	"smsEnabled\x12#\n" +
	"\remail_enabled\x18\x06 \x01(\bR\femailEnabledB5Z+github.com/jdfalk/gcommon/sdks/go/v1/common\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_common_mfa_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gcommon_v1_common_mfa_config_proto_goTypes = []any{
	(*MfaConfig)(nil), // 0: gcommon.v1.common.MfaConfig
}
var file_gcommon_v1_common_mfa_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gcommon_v1_common_mfa_config_proto_init() }
func file_gcommon_v1_common_mfa_config_proto_init() {
	if File_gcommon_v1_common_mfa_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_common_mfa_config_proto_rawDesc), len(file_gcommon_v1_common_mfa_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_common_mfa_config_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_common_mfa_config_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_common_mfa_config_proto_msgTypes,
	}.Build()
	File_gcommon_v1_common_mfa_config_proto = out.File
	file_gcommon_v1_common_mfa_config_proto_goTypes = nil
	file_gcommon_v1_common_mfa_config_proto_depIdxs = nil
}
