// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gcommon/v1/common/update_session_response.proto

package common

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Response for session update operations.
// Contains the updated session information.
type AuthUpdateSessionResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success      bool                   `protobuf:"varint,1,opt,name=success"`
	xxx_hidden_Session      *SessionInfo           `protobuf:"bytes,2,opt,name=session"`
	xxx_hidden_ErrorMessage *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage"`
	xxx_hidden_Metadata     *ResponseMetadata      `protobuf:"bytes,4,opt,name=metadata"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthUpdateSessionResponse) Reset() {
	*x = AuthUpdateSessionResponse{}
	mi := &file_gcommon_v1_common_update_session_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUpdateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUpdateSessionResponse) ProtoMessage() {}

func (x *AuthUpdateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_common_update_session_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthUpdateSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *AuthUpdateSessionResponse) GetSession() *SessionInfo {
	if x != nil {
		return x.xxx_hidden_Session
	}
	return nil
}

func (x *AuthUpdateSessionResponse) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *AuthUpdateSessionResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *AuthUpdateSessionResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *AuthUpdateSessionResponse) SetSession(v *SessionInfo) {
	x.xxx_hidden_Session = v
}

func (x *AuthUpdateSessionResponse) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *AuthUpdateSessionResponse) SetMetadata(v *ResponseMetadata) {
	x.xxx_hidden_Metadata = v
}

func (x *AuthUpdateSessionResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthUpdateSessionResponse) HasSession() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Session != nil
}

func (x *AuthUpdateSessionResponse) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuthUpdateSessionResponse) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *AuthUpdateSessionResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

func (x *AuthUpdateSessionResponse) ClearSession() {
	x.xxx_hidden_Session = nil
}

func (x *AuthUpdateSessionResponse) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ErrorMessage = nil
}

func (x *AuthUpdateSessionResponse) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

type AuthUpdateSessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether the update was successful
	Success *bool
	// Updated session information
	Session *SessionInfo
	// Error message if update failed
	ErrorMessage *string
	// Response metadata
	Metadata *ResponseMetadata
}

func (b0 AuthUpdateSessionResponse_builder) Build() *AuthUpdateSessionResponse {
	m0 := &AuthUpdateSessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Success = *b.Success
	}
	x.xxx_hidden_Session = b.Session
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

var File_gcommon_v1_common_update_session_response_proto protoreflect.FileDescriptor

const file_gcommon_v1_common_update_session_response_proto_rawDesc = "" +
	"\n" +
	"/gcommon/v1/common/update_session_response.proto\x12\x11gcommon.v1.common\x1a)gcommon/v1/common/response_metadata.proto\x1a$gcommon/v1/common/session_info.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xde\x01\n" +
	"\x19AuthUpdateSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\asession\x18\x02 \x01(\v2\x1e.gcommon.v1.common.SessionInfoR\asession\x12,\n" +
	"\rerror_message\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\ferrorMessage\x12?\n" +
	"\bmetadata\x18\x04 \x01(\v2#.gcommon.v1.common.ResponseMetadataR\bmetadataB5Z+github.com/jdfalk/gcommon/sdks/go/v1/common\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_common_update_session_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gcommon_v1_common_update_session_response_proto_goTypes = []any{
	(*AuthUpdateSessionResponse)(nil), // 0: gcommon.v1.common.AuthUpdateSessionResponse
	(*SessionInfo)(nil),               // 1: gcommon.v1.common.SessionInfo
	(*ResponseMetadata)(nil),          // 2: gcommon.v1.common.ResponseMetadata
}
var file_gcommon_v1_common_update_session_response_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.common.AuthUpdateSessionResponse.session:type_name -> gcommon.v1.common.SessionInfo
	2, // 1: gcommon.v1.common.AuthUpdateSessionResponse.metadata:type_name -> gcommon.v1.common.ResponseMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gcommon_v1_common_update_session_response_proto_init() }
func file_gcommon_v1_common_update_session_response_proto_init() {
	if File_gcommon_v1_common_update_session_response_proto != nil {
		return
	}
	file_gcommon_v1_common_response_metadata_proto_init()
	file_gcommon_v1_common_session_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_common_update_session_response_proto_rawDesc), len(file_gcommon_v1_common_update_session_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_common_update_session_response_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_common_update_session_response_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_common_update_session_response_proto_msgTypes,
	}.Build()
	File_gcommon_v1_common_update_session_response_proto = out.File
	file_gcommon_v1_common_update_session_response_proto_goTypes = nil
	file_gcommon_v1_common_update_session_response_proto_depIdxs = nil
}
