from gcommon.v1.common.messages import authenticate_request_pb2 as _authenticate_request_pb2
from gcommon.v1.common.messages import authenticate_response_pb2 as _authenticate_response_pb2
from gcommon.v1.common.messages import change_password_request_pb2 as _change_password_request_pb2
from gcommon.v1.common.messages import change_password_response_pb2 as _change_password_response_pb2
from gcommon.v1.common.messages import complete_password_reset_request_pb2 as _complete_password_reset_request_pb2
from gcommon.v1.common.messages import complete_password_reset_response_pb2 as _complete_password_reset_response_pb2
from gcommon.v1.common.messages import get_user_info_request_pb2 as _get_user_info_request_pb2
from gcommon.v1.common.messages import get_user_info_response_pb2 as _get_user_info_response_pb2
from gcommon.v1.common.messages import initiate_password_reset_request_pb2 as _initiate_password_reset_request_pb2
from gcommon.v1.common.messages import initiate_password_reset_response_pb2 as _initiate_password_reset_response_pb2
from gcommon.v1.common.messages import refresh_token_request_pb2 as _refresh_token_request_pb2
from gcommon.v1.common.messages import refresh_token_response_pb2 as _refresh_token_response_pb2
from gcommon.v1.common.messages import revoke_token_request_pb2 as _revoke_token_request_pb2
from gcommon.v1.common.messages import revoke_token_response_pb2 as _revoke_token_response_pb2
from gcommon.v1.common.messages import validate_token_request_pb2 as _validate_token_request_pb2
from gcommon.v1.common.messages import validate_token_response_pb2 as _validate_token_response_pb2
from gcommon.v1.common.messages import verify_credentials_request_pb2 as _verify_credentials_request_pb2
from gcommon.v1.common.messages import verify_credentials_response_pb2 as _verify_credentials_response_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
