from gcommon.v1.common.messages import configure_alerting_request_pb2 as _configure_alerting_request_pb2
from gcommon.v1.common.messages import configure_alerting_response_pb2 as _configure_alerting_response_pb2
from gcommon.v1.common.messages import disable_check_request_pb2 as _disable_check_request_pb2
from gcommon.v1.common.messages import disable_check_response_pb2 as _disable_check_response_pb2
from gcommon.v1.common.messages import enable_check_request_pb2 as _enable_check_request_pb2
from gcommon.v1.common.messages import enable_check_response_pb2 as _enable_check_response_pb2
from gcommon.v1.common.messages import reset_health_stats_request_pb2 as _reset_health_stats_request_pb2
from gcommon.v1.common.messages import reset_health_stats_response_pb2 as _reset_health_stats_response_pb2
from gcommon.v1.common.messages import run_check_request_pb2 as _run_check_request_pb2
from gcommon.v1.common.messages import run_check_response_pb2 as _run_check_response_pb2
from gcommon.v1.common.messages import set_health_request_pb2 as _set_health_request_pb2
from gcommon.v1.common.messages import set_health_response_pb2 as _set_health_response_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
