from gcommon.v1.common.messages import create_session_request_pb2 as _create_session_request_pb2
from gcommon.v1.common.messages import create_session_response_pb2 as _create_session_response_pb2
from gcommon.v1.common.messages import delete_session_request_pb2 as _delete_session_request_pb2
from gcommon.v1.common.messages import delete_session_response_pb2 as _delete_session_response_pb2
from gcommon.v1.common.messages import get_session_request_pb2 as _get_session_request_pb2
from gcommon.v1.common.messages import get_session_response_pb2 as _get_session_response_pb2
from gcommon.v1.common.messages import list_sessions_request_pb2 as _list_sessions_request_pb2
from gcommon.v1.common.messages import list_sessions_response_pb2 as _list_sessions_response_pb2
from gcommon.v1.common.messages import list_user_sessions_request_pb2 as _list_user_sessions_request_pb2
from gcommon.v1.common.messages import list_user_sessions_response_pb2 as _list_user_sessions_response_pb2
from gcommon.v1.common.messages import terminate_session_request_pb2 as _terminate_session_request_pb2
from gcommon.v1.common.messages import terminate_session_response_pb2 as _terminate_session_response_pb2
from gcommon.v1.common.messages import update_session_request_pb2 as _update_session_request_pb2
from gcommon.v1.common.messages import update_session_response_pb2 as _update_session_response_pb2
from gcommon.v1.common.messages import validate_session_request_pb2 as _validate_session_request_pb2
from gcommon.v1.common.messages import validate_session_response_pb2 as _validate_session_response_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
