from gcommon.v1.config.messages import delete_config_request_pb2 as _delete_config_request_pb2
from gcommon.v1.config.messages import get_config_request_pb2 as _get_config_request_pb2
from gcommon.v1.config.messages import get_config_response_pb2 as _get_config_response_pb2
from gcommon.v1.config.messages import get_multiple_config_request_pb2 as _get_multiple_config_request_pb2
from gcommon.v1.config.messages import get_multiple_config_response_pb2 as _get_multiple_config_response_pb2
from gcommon.v1.config.messages import get_schema_request_pb2 as _get_schema_request_pb2
from gcommon.v1.config.messages import get_schema_response_pb2 as _get_schema_response_pb2
from gcommon.v1.config.messages import list_config_request_pb2 as _list_config_request_pb2
from gcommon.v1.config.messages import list_config_response_pb2 as _list_config_response_pb2
from gcommon.v1.config.messages import set_config_request_pb2 as _set_config_request_pb2
from gcommon.v1.config.messages import set_config_response_pb2 as _set_config_response_pb2
from gcommon.v1.config.messages import set_multiple_config_request_pb2 as _set_multiple_config_request_pb2
from gcommon.v1.config.messages import set_multiple_config_response_pb2 as _set_multiple_config_response_pb2
from gcommon.v1.config.messages import validate_config_request_pb2 as _validate_config_request_pb2
from gcommon.v1.config.messages import validate_config_response_pb2 as _validate_config_response_pb2
from gcommon.v1.config.messages import watch_config_request_pb2 as _watch_config_request_pb2
from gcommon.v1.config.messages import watch_config_response_pb2 as _watch_config_response_pb2
from google.protobuf import empty_pb2 as _empty_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
