from gcommon.v1.config.messages import backup_config_request_pb2 as _backup_config_request_pb2
from gcommon.v1.config.messages import config_backup_pb2 as _config_backup_pb2
from gcommon.v1.config.messages import config_snapshot_pb2 as _config_snapshot_pb2
from gcommon.v1.config.messages import export_config_request_pb2 as _export_config_request_pb2
from gcommon.v1.config.messages import get_config_history_request_pb2 as _get_config_history_request_pb2
from gcommon.v1.config.messages import get_config_history_response_pb2 as _get_config_history_response_pb2
from gcommon.v1.config.messages import get_config_stats_request_pb2 as _get_config_stats_request_pb2
from gcommon.v1.config.messages import get_config_stats_response_pb2 as _get_config_stats_response_pb2
from gcommon.v1.config.messages import health_check_request_pb2 as _health_check_request_pb2
from gcommon.v1.config.messages import health_check_response_pb2 as _health_check_response_pb2
from gcommon.v1.config.messages import import_config_request_pb2 as _import_config_request_pb2
from gcommon.v1.config.messages import reload_config_request_pb2 as _reload_config_request_pb2
from gcommon.v1.config.messages import restore_config_request_pb2 as _restore_config_request_pb2
from gcommon.v1.config.messages import rollback_config_request_pb2 as _rollback_config_request_pb2
from gcommon.v1.config.messages import set_config_schema_request_pb2 as _set_config_schema_request_pb2
from gcommon.v1.config.messages import unwatch_config_request_pb2 as _unwatch_config_request_pb2
from google.protobuf import empty_pb2 as _empty_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
