// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: gcommon/v1/organization/update_tenant_quota_response.proto

package organization

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/jdfalk/gcommon/sdks/go/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateTenantQuotaResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Errors      *[]*common.Error       `protobuf:"bytes,1,rep,name=errors"`
	xxx_hidden_Success     bool                   `protobuf:"varint,2,opt,name=success"`
	xxx_hidden_Quota       *TenantQuota           `protobuf:"bytes,3,opt,name=quota"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateTenantQuotaResponse) Reset() {
	*x = UpdateTenantQuotaResponse{}
	mi := &file_gcommon_v1_organization_update_tenant_quota_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantQuotaResponse) ProtoMessage() {}

func (x *UpdateTenantQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_organization_update_tenant_quota_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateTenantQuotaResponse) GetErrors() []*common.Error {
	if x != nil {
		if x.xxx_hidden_Errors != nil {
			return *x.xxx_hidden_Errors
		}
	}
	return nil
}

func (x *UpdateTenantQuotaResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *UpdateTenantQuotaResponse) GetQuota() *TenantQuota {
	if x != nil {
		return x.xxx_hidden_Quota
	}
	return nil
}

func (x *UpdateTenantQuotaResponse) SetErrors(v []*common.Error) {
	x.xxx_hidden_Errors = &v
}

func (x *UpdateTenantQuotaResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *UpdateTenantQuotaResponse) SetQuota(v *TenantQuota) {
	x.xxx_hidden_Quota = v
}

func (x *UpdateTenantQuotaResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateTenantQuotaResponse) HasQuota() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Quota != nil
}

func (x *UpdateTenantQuotaResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Success = false
}

func (x *UpdateTenantQuotaResponse) ClearQuota() {
	x.xxx_hidden_Quota = nil
}

type UpdateTenantQuotaResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Any errors encountered
	Errors []*common.Error
	// Success status
	Success *bool
	// Updated quota configuration
	Quota *TenantQuota
}

func (b0 UpdateTenantQuotaResponse_builder) Build() *UpdateTenantQuotaResponse {
	m0 := &UpdateTenantQuotaResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Errors = &b.Errors
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Success = *b.Success
	}
	x.xxx_hidden_Quota = b.Quota
	return m0
}

var File_gcommon_v1_organization_update_tenant_quota_response_proto protoreflect.FileDescriptor

const file_gcommon_v1_organization_update_tenant_quota_response_proto_rawDesc = "" +
	"\n" +
	":gcommon/v1/organization/update_tenant_quota_response.proto\x12\x17gcommon.v1.organization\x1a\x1dgcommon/v1/common/error.proto\x1a*gcommon/v1/organization/tenant_quota.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xad\x01\n" +
	"\x19UpdateTenantQuotaResponse\x12:\n" +
	"\x06errors\x18\x01 \x03(\v2\x18.gcommon.v1.common.ErrorB\b\xbaH\x05\x92\x01\x02\b\x01R\x06errors\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12:\n" +
	"\x05quota\x18\x03 \x01(\v2$.gcommon.v1.organization.TenantQuotaR\x05quotaB;Z1github.com/jdfalk/gcommon/sdks/go/v1/organization\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_organization_update_tenant_quota_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gcommon_v1_organization_update_tenant_quota_response_proto_goTypes = []any{
	(*UpdateTenantQuotaResponse)(nil), // 0: gcommon.v1.organization.UpdateTenantQuotaResponse
	(*common.Error)(nil),              // 1: gcommon.v1.common.Error
	(*TenantQuota)(nil),               // 2: gcommon.v1.organization.TenantQuota
}
var file_gcommon_v1_organization_update_tenant_quota_response_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.organization.UpdateTenantQuotaResponse.errors:type_name -> gcommon.v1.common.Error
	2, // 1: gcommon.v1.organization.UpdateTenantQuotaResponse.quota:type_name -> gcommon.v1.organization.TenantQuota
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gcommon_v1_organization_update_tenant_quota_response_proto_init() }
func file_gcommon_v1_organization_update_tenant_quota_response_proto_init() {
	if File_gcommon_v1_organization_update_tenant_quota_response_proto != nil {
		return
	}
	file_gcommon_v1_organization_tenant_quota_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_organization_update_tenant_quota_response_proto_rawDesc), len(file_gcommon_v1_organization_update_tenant_quota_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_organization_update_tenant_quota_response_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_organization_update_tenant_quota_response_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_organization_update_tenant_quota_response_proto_msgTypes,
	}.Build()
	File_gcommon_v1_organization_update_tenant_quota_response_proto = out.File
	file_gcommon_v1_organization_update_tenant_quota_response_proto_goTypes = nil
	file_gcommon_v1_organization_update_tenant_quota_response_proto_depIdxs = nil
}
