// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gcommon/v1/queue/messages/connection_details.proto

package queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnectionDetails contains information for establishing message delivery connections
type ConnectionDetails struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeliveryEndpoint    *string                `protobuf:"bytes,1,opt,name=delivery_endpoint,json=deliveryEndpoint"`
	xxx_hidden_AuthToken           *string                `protobuf:"bytes,2,opt,name=auth_token,json=authToken"`
	xxx_hidden_HeartbeatIntervalMs int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs"`
	xxx_hidden_KeepAliveTimeoutMs  int32                  `protobuf:"varint,4,opt,name=keep_alive_timeout_ms,json=keepAliveTimeoutMs"`
	xxx_hidden_SslEnabled          bool                   `protobuf:"varint,5,opt,name=ssl_enabled,json=sslEnabled"`
	xxx_hidden_ConnectionMetadata  map[string]string      `protobuf:"bytes,6,rep,name=connection_metadata,json=connectionMetadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ConnectionDetails) Reset() {
	*x = ConnectionDetails{}
	mi := &file_gcommon_v1_queue_messages_connection_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionDetails) ProtoMessage() {}

func (x *ConnectionDetails) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_queue_messages_connection_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionDetails) GetDeliveryEndpoint() string {
	if x != nil {
		if x.xxx_hidden_DeliveryEndpoint != nil {
			return *x.xxx_hidden_DeliveryEndpoint
		}
		return ""
	}
	return ""
}

func (x *ConnectionDetails) GetAuthToken() string {
	if x != nil {
		if x.xxx_hidden_AuthToken != nil {
			return *x.xxx_hidden_AuthToken
		}
		return ""
	}
	return ""
}

func (x *ConnectionDetails) GetHeartbeatIntervalMs() int32 {
	if x != nil {
		return x.xxx_hidden_HeartbeatIntervalMs
	}
	return 0
}

func (x *ConnectionDetails) GetKeepAliveTimeoutMs() int32 {
	if x != nil {
		return x.xxx_hidden_KeepAliveTimeoutMs
	}
	return 0
}

func (x *ConnectionDetails) GetSslEnabled() bool {
	if x != nil {
		return x.xxx_hidden_SslEnabled
	}
	return false
}

func (x *ConnectionDetails) GetConnectionMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_ConnectionMetadata
	}
	return nil
}

func (x *ConnectionDetails) SetDeliveryEndpoint(v string) {
	x.xxx_hidden_DeliveryEndpoint = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *ConnectionDetails) SetAuthToken(v string) {
	x.xxx_hidden_AuthToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *ConnectionDetails) SetHeartbeatIntervalMs(v int32) {
	x.xxx_hidden_HeartbeatIntervalMs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *ConnectionDetails) SetKeepAliveTimeoutMs(v int32) {
	x.xxx_hidden_KeepAliveTimeoutMs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *ConnectionDetails) SetSslEnabled(v bool) {
	x.xxx_hidden_SslEnabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *ConnectionDetails) SetConnectionMetadata(v map[string]string) {
	x.xxx_hidden_ConnectionMetadata = v
}

func (x *ConnectionDetails) HasDeliveryEndpoint() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConnectionDetails) HasAuthToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConnectionDetails) HasHeartbeatIntervalMs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ConnectionDetails) HasKeepAliveTimeoutMs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ConnectionDetails) HasSslEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ConnectionDetails) ClearDeliveryEndpoint() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DeliveryEndpoint = nil
}

func (x *ConnectionDetails) ClearAuthToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AuthToken = nil
}

func (x *ConnectionDetails) ClearHeartbeatIntervalMs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_HeartbeatIntervalMs = 0
}

func (x *ConnectionDetails) ClearKeepAliveTimeoutMs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_KeepAliveTimeoutMs = 0
}

func (x *ConnectionDetails) ClearSslEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_SslEnabled = false
}

type ConnectionDetails_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Delivery endpoint (for push mode)
	DeliveryEndpoint *string
	// Authentication token for delivery
	AuthToken *string
	// Heartbeat interval (milliseconds)
	HeartbeatIntervalMs *int32
	// Keep-alive timeout (milliseconds)
	KeepAliveTimeoutMs *int32
	// SSL/TLS configuration
	SslEnabled *bool
	// Connection metadata
	ConnectionMetadata map[string]string
}

func (b0 ConnectionDetails_builder) Build() *ConnectionDetails {
	m0 := &ConnectionDetails{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DeliveryEndpoint != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_DeliveryEndpoint = b.DeliveryEndpoint
	}
	if b.AuthToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_AuthToken = b.AuthToken
	}
	if b.HeartbeatIntervalMs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_HeartbeatIntervalMs = *b.HeartbeatIntervalMs
	}
	if b.KeepAliveTimeoutMs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_KeepAliveTimeoutMs = *b.KeepAliveTimeoutMs
	}
	if b.SslEnabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_SslEnabled = *b.SslEnabled
	}
	x.xxx_hidden_ConnectionMetadata = b.ConnectionMetadata
	return m0
}

var File_gcommon_v1_queue_messages_connection_details_proto protoreflect.FileDescriptor

const file_gcommon_v1_queue_messages_connection_details_proto_rawDesc = "" +
	"\n" +
	"2gcommon/v1/queue/messages/connection_details.proto\x12\x10gcommon.v1.queue\x1a!google/protobuf/go_features.proto\"\x9c\x03\n" +
	"\x11ConnectionDetails\x12+\n" +
	"\x11delivery_endpoint\x18\x01 \x01(\tR\x10deliveryEndpoint\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x122\n" +
	"\x15heartbeat_interval_ms\x18\x03 \x01(\x05R\x13heartbeatIntervalMs\x121\n" +
	"\x15keep_alive_timeout_ms\x18\x04 \x01(\x05R\x12keepAliveTimeoutMs\x12\x1f\n" +
	"\vssl_enabled\x18\x05 \x01(\bR\n" +
	"sslEnabled\x12l\n" +
	"\x13connection_metadata\x18\x06 \x03(\v2;.gcommon.v1.queue.ConnectionDetails.ConnectionMetadataEntryR\x12connectionMetadata\x1aE\n" +
	"\x17ConnectionMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xcc\x01\n" +
	"\x14com.gcommon.v1.queueB\x16ConnectionDetailsProtoP\x01Z2github.com/jdfalk/gcommon/sdks/go/gcommon/v1/queue\xa2\x02\x03GVQ\xaa\x02\x10Gcommon.V1.Queue\xca\x02\x10Gcommon\\V1\\Queue\xe2\x02\x1cGcommon\\V1\\Queue\\GPBMetadata\xea\x02\x12Gcommon::V1::Queue\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_queue_messages_connection_details_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gcommon_v1_queue_messages_connection_details_proto_goTypes = []any{
	(*ConnectionDetails)(nil), // 0: gcommon.v1.queue.ConnectionDetails
	nil,                       // 1: gcommon.v1.queue.ConnectionDetails.ConnectionMetadataEntry
}
var file_gcommon_v1_queue_messages_connection_details_proto_depIdxs = []int32{
	1, // 0: gcommon.v1.queue.ConnectionDetails.connection_metadata:type_name -> gcommon.v1.queue.ConnectionDetails.ConnectionMetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gcommon_v1_queue_messages_connection_details_proto_init() }
func file_gcommon_v1_queue_messages_connection_details_proto_init() {
	if File_gcommon_v1_queue_messages_connection_details_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_queue_messages_connection_details_proto_rawDesc), len(file_gcommon_v1_queue_messages_connection_details_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_queue_messages_connection_details_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_queue_messages_connection_details_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_queue_messages_connection_details_proto_msgTypes,
	}.Build()
	File_gcommon_v1_queue_messages_connection_details_proto = out.File
	file_gcommon_v1_queue_messages_connection_details_proto_goTypes = nil
	file_gcommon_v1_queue_messages_connection_details_proto_depIdxs = nil
}
