// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gcommon/v1/queue/messages/size_bucket.proto

package queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SizeBucket struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MinSizeBytes int64                  `protobuf:"varint,1,opt,name=min_size_bytes,json=minSizeBytes"`
	xxx_hidden_MaxSizeBytes int64                  `protobuf:"varint,2,opt,name=max_size_bytes,json=maxSizeBytes"`
	xxx_hidden_MessageCount int64                  `protobuf:"varint,3,opt,name=message_count,json=messageCount"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SizeBucket) Reset() {
	*x = SizeBucket{}
	mi := &file_gcommon_v1_queue_messages_size_bucket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeBucket) ProtoMessage() {}

func (x *SizeBucket) ProtoReflect() protoreflect.Message {
	mi := &file_gcommon_v1_queue_messages_size_bucket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SizeBucket) GetMinSizeBytes() int64 {
	if x != nil {
		return x.xxx_hidden_MinSizeBytes
	}
	return 0
}

func (x *SizeBucket) GetMaxSizeBytes() int64 {
	if x != nil {
		return x.xxx_hidden_MaxSizeBytes
	}
	return 0
}

func (x *SizeBucket) GetMessageCount() int64 {
	if x != nil {
		return x.xxx_hidden_MessageCount
	}
	return 0
}

func (x *SizeBucket) SetMinSizeBytes(v int64) {
	x.xxx_hidden_MinSizeBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SizeBucket) SetMaxSizeBytes(v int64) {
	x.xxx_hidden_MaxSizeBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SizeBucket) SetMessageCount(v int64) {
	x.xxx_hidden_MessageCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *SizeBucket) HasMinSizeBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SizeBucket) HasMaxSizeBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SizeBucket) HasMessageCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SizeBucket) ClearMinSizeBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MinSizeBytes = 0
}

func (x *SizeBucket) ClearMaxSizeBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MaxSizeBytes = 0
}

func (x *SizeBucket) ClearMessageCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MessageCount = 0
}

type SizeBucket_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MinSizeBytes *int64
	MaxSizeBytes *int64
	MessageCount *int64
}

func (b0 SizeBucket_builder) Build() *SizeBucket {
	m0 := &SizeBucket{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MinSizeBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_MinSizeBytes = *b.MinSizeBytes
	}
	if b.MaxSizeBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_MaxSizeBytes = *b.MaxSizeBytes
	}
	if b.MessageCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_MessageCount = *b.MessageCount
	}
	return m0
}

var File_gcommon_v1_queue_messages_size_bucket_proto protoreflect.FileDescriptor

const file_gcommon_v1_queue_messages_size_bucket_proto_rawDesc = "" +
	"\n" +
	"+gcommon/v1/queue/messages/size_bucket.proto\x12\x10gcommon.v1.queue\x1a!google/protobuf/go_features.proto\"}\n" +
	"\n" +
	"SizeBucket\x12$\n" +
	"\x0emin_size_bytes\x18\x01 \x01(\x03R\fminSizeBytes\x12$\n" +
	"\x0emax_size_bytes\x18\x02 \x01(\x03R\fmaxSizeBytes\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x03R\fmessageCountB\xc5\x01\n" +
	"\x14com.gcommon.v1.queueB\x0fSizeBucketProtoP\x01Z2github.com/jdfalk/gcommon/sdks/go/gcommon/v1/queue\xa2\x02\x03GVQ\xaa\x02\x10Gcommon.V1.Queue\xca\x02\x10Gcommon\\V1\\Queue\xe2\x02\x1cGcommon\\V1\\Queue\\GPBMetadata\xea\x02\x12Gcommon::V1::Queue\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gcommon_v1_queue_messages_size_bucket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gcommon_v1_queue_messages_size_bucket_proto_goTypes = []any{
	(*SizeBucket)(nil), // 0: gcommon.v1.queue.SizeBucket
}
var file_gcommon_v1_queue_messages_size_bucket_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gcommon_v1_queue_messages_size_bucket_proto_init() }
func file_gcommon_v1_queue_messages_size_bucket_proto_init() {
	if File_gcommon_v1_queue_messages_size_bucket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcommon_v1_queue_messages_size_bucket_proto_rawDesc), len(file_gcommon_v1_queue_messages_size_bucket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcommon_v1_queue_messages_size_bucket_proto_goTypes,
		DependencyIndexes: file_gcommon_v1_queue_messages_size_bucket_proto_depIdxs,
		MessageInfos:      file_gcommon_v1_queue_messages_size_bucket_proto_msgTypes,
	}.Build()
	File_gcommon_v1_queue_messages_size_bucket_proto = out.File
	file_gcommon_v1_queue_messages_size_bucket_proto_goTypes = nil
	file_gcommon_v1_queue_messages_size_bucket_proto_depIdxs = nil
}
