# file: .github/workflows/ci.yml
# version: 2.0.0
# guid: 7f1b2c3d-4f5a-6b7c-8d9e-0a1b2c3d4e5f

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write  # Required for auto-committing fixes from super-linter
  statuses: write  # Required for status updates
  pull-requests: write
  actions: read
  checks: write
  security-events: write
  id-token: write
  # Additional permissions for dependency submission
  repository-projects: write
  packages: write
  attestations: write

jobs:
  universal-ci:
    uses: jdfalk/ghcommon/.github/workflows/reusable-ci.yml@main
    with:
      python-version: "3.12"
      node-version: "22"
      go-version: "1.22"
      run-lint: true
      run-test: true
      run-build: false
      enable-dependency-submission: true
      enable-backend-frontend: false
    secrets: inherit
