# file: .github/workflows/ci.yml
# version: 2.0.0
# guid: 7f1b2c3d-4f5a-6b7c-8d9e-0a1b2c3d4e5f

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  universal-ci:
    uses: jdfalk/ghcommon/.github/workflows/reusable-ci.yml@main
    with:
      python-version: "3.12"
      node-version: "22"
      go-version: "1.22"
      run-lint: true
      run-test: true
      run-build: false
      enable-backend-frontend: false
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
