# file: .github/workflows/deploy.yml
# version: 1.0.0
# guid: 4416f373-2a10-4053-bf39-ef7e8efe9742

name: Deploy GCommon App

on:
  push:
    branches: [ main ]
    paths:
      - 'deploy/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Docker image
        run: |
          docker build -f deploy/docker/Dockerfile -t ghcr.io/jdfalk/gcommon-app:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ghcr.io/jdfalk/gcommon-app:latest

  deploy:
    name: Deploy to Kubernetes
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: echo "$KUBECONFIG_DATA" | base64 -d > $HOME/.kube/config
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Deploy via Helm
        uses: azure/setup-helm@v4

      - name: Helm upgrade
        run: |
          helm upgrade --install gcommon-app deploy/helm/gcommon-app \
            --namespace gcommon --create-namespace
