# file: .github/workflows/docs.yml
# version: 1.0.0
# guid: 8c27de72-d478-4a55-aaa0-39dd5cb6c4b7

name: Documentation

on:
  push:
    branches: [main]
    paths:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install docs dependencies
        run: npm install --ignore-scripts

      - name: Generate documentation
        run: |
          echo "Building documentation"
          mkdir -p build/docs
          cp -r docs/* build/docs/

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: build/docs

  lint-docs:
    name: Lint documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md'

  completeness-check:
    name: Check documentation completeness
    runs-on: ubuntu-latest
    needs: [build-docs, lint-docs]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify essential docs
        run: |
          files="README.md CHANGELOG.md TODO.md"
          missing=0
          for f in $files; do
            if [ ! -f "$f" ]; then
              echo "$f is missing" >&2
              missing=1
            fi
          done
          exit $missing

  deploy-docs:
    name: Deploy documentation
    runs-on: ubuntu-latest
    needs: [completeness-check]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download documentation
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: build/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs

  notify:
    name: Notify documentation status
    runs-on: ubuntu-latest
    needs: [deploy-docs]
    if: always()
    steps:
      - name: Post GitHub comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Documentation workflow completed with status ${{ needs.deploy-docs.result }}.'
            })
      - name: Send Slack notification
        if: env.SLACK_WEBHOOK != ''
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": "Documentation workflow ${{ needs.deploy-docs.result }} for ${{ github.repository }}"
            }
