# file: .github/workflows/fix-merge-conflicts.yml
# version: 1.0.0
# guid: f84c2a5d-6e1f-4b72-9c4e-7d5b8e2f1a94

name: Fix Merge Conflicts

on:
  schedule:
    - cron: "0 6 * * *" # Run daily at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  models: read

jobs:
  ai-rebase:
    uses: jdfalk/ghcommon/.github/workflows/reusable-ai-rebase.yml@main
    with:
      base-branch: "main"
      model: "openai/gpt-4o"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
