# file: .github/workflows/pr-labeler.yml
# version: 1.0.0
# guid: d4e5f6a7-b8c9-40d1-e2f3-a4b5c6d7e8f9

name: Pull Request Labeler

# Automatically label pull requests based on changed files and branch names
# Uses the reusable labeler workflow from ghcommon repository

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  labeler:
    uses: jdfalk/ghcommon/.github/workflows/reusable-labeler.yml@main
    with:
      configuration-path: ".github/labeler.yml"
      sync-labels: true
      dot: true
