# file: .github/workflows/protobuf-validation.yml
# version: 1.0.0
# guid: d9715abb-f269-4b59-9b39-8d45af3a7c9b

name: Protobuf Validation

on:
  push:
    branches: [main]
    paths:
      - "pkg/**/*.proto"
      - ".github/workflows/protobuf-validation.yml"
      - "scripts/validate-protos.sh"
      - "buf.yaml"
  pull_request:
    branches: [main]
    paths:
      - "pkg/**/*.proto"
      - "scripts/validate-protos.sh"
      - ".github/workflows/protobuf-validation.yml"
      - "buf.yaml"

jobs:
  validate-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run protobuf validation
        run: make proto-compile
