# file: .github/workflows/unified-automation.yml
# version: 2.1.0
# guid: 8b7c6d5e-4f3a-2b1c-0d1e-2f3a4b5c6d7e

name: Unified Issue & Docs Automation

on:
  push:
    branches: [main, master]
    paths:
      - '.github/issue-updates/**'
      - '.github/doc-updates/**'
      - 'issue_updates.json'
  workflow_dispatch:
    inputs:
      operation:
        description: "Which operation(s) to run (all, issues, docs, label, lint, rebase, pr, merge, sync, ci, test, build, release, security, codeql, stale, cleanup, custom)"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - issues
          - docs
          - label
          - lint
          - rebase
          - pr
          - merge
          - sync
          - ci
          - test
          - build
          - release
          - security
          - codeql
          - stale
          - cleanup
          - custom
      dry_run:
        description: "Run in dry-run mode (no changes)"
        required: false
        type: boolean
        default: false
      continue_on_error:
        description: "Continue on error (run all jobs even if one fails)"
        required: false
        type: boolean
        default: true
      python_version:
        description: "Python version to use for scripts"
        required: false
        default: "3.11"
      extra_args:
        description: "Extra arguments for advanced workflows (comma-separated)"
        required: false
        type: string
        default: ""

jobs:
  orchestrate:
    uses: jdfalk/ghcommon/.github/workflows/reusable-unified-automation.yml@main
    with:
      operation: ${{ github.event.inputs.operation || 'all' }}
    secrets:
      github-token: ${{ secrets.JF_CI_GH_PAT || secrets.GITHUB_TOKEN }}
