# file: .github/workflows/unified-automation.yml
# version: 2.3.1
# guid: 8b7c6d5e-4f3a-2b1c-0d1e-2f3a4b5c6d7e

name: Unified Issue & Docs Automation

permissions:
  contents: write # For creating commits and PRs
  issues: write # For creating and updating issues
  pull-requests: write # For creating PRs
  security-events: write # For security scanning and writing results
  repository-projects: write # For adding items to projects
  actions: write # For workflow access
  checks: write # For workflow status
  statuses: write # For commit status updates
  packages: read # For package access (required by super-linter)
  id-token: write # For attestation and artifact uploads (required by super-linter)
  models: read # For AI model access (required by ai-rebase)

on:
  push:
    branches: [main, master]
    paths:
      - ".github/issue-updates/**"
      - ".github/doc-updates/**"
      - "issue_updates.json"
  workflow_dispatch:
    inputs:
      operation:
        description: "Which operation(s) to run (all, issues, docs, label, lint, rebase)"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - issues
          - docs
          - label
          - intelligent-labeling
          - lint
          - rebase

jobs:
  orchestrate:
    uses: jdfalk/ghcommon/.github/workflows/reusable-unified-automation.yml@main
    with:
      operation: ${{ github.event.inputs.operation || 'all' }}
    secrets: inherit
