from gcommon.v1.database.messages import configure_policy_request_pb2 as _configure_policy_request_pb2
from gcommon.v1.database.messages import configure_policy_response_pb2 as _configure_policy_response_pb2
from gcommon.v1.database.messages import create_namespace_request_pb2 as _create_namespace_request_pb2
from gcommon.v1.database.messages import create_namespace_response_pb2 as _create_namespace_response_pb2
from gcommon.v1.database.messages import delete_namespace_request_pb2 as _delete_namespace_request_pb2
from gcommon.v1.database.messages import get_namespace_stats_request_pb2 as _get_namespace_stats_request_pb2
from gcommon.v1.database.messages import get_namespace_stats_response_pb2 as _get_namespace_stats_response_pb2
from gcommon.v1.database.messages import list_namespaces_request_pb2 as _list_namespaces_request_pb2
from gcommon.v1.database.messages import list_namespaces_response_pb2 as _list_namespaces_response_pb2
from google.protobuf import empty_pb2 as _empty_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
