from gcommon.v1.database.messages import clear_request_pb2 as _clear_request_pb2
from gcommon.v1.database.messages import clear_response_pb2 as _clear_response_pb2
from gcommon.v1.database.messages import decrement_request_pb2 as _decrement_request_pb2
from gcommon.v1.database.messages import decrement_response_pb2 as _decrement_response_pb2
from gcommon.v1.database.messages import delete_multiple_request_pb2 as _delete_multiple_request_pb2
from gcommon.v1.database.messages import delete_multiple_response_pb2 as _delete_multiple_response_pb2
from gcommon.v1.database.messages import delete_request_pb2 as _delete_request_pb2
from gcommon.v1.database.messages import delete_response_pb2 as _delete_response_pb2
from gcommon.v1.database.messages import exists_request_pb2 as _exists_request_pb2
from gcommon.v1.database.messages import exists_response_pb2 as _exists_response_pb2
from gcommon.v1.database.messages import flush_request_pb2 as _flush_request_pb2
from gcommon.v1.database.messages import flush_response_pb2 as _flush_response_pb2
from gcommon.v1.database.messages import get_multiple_request_pb2 as _get_multiple_request_pb2
from gcommon.v1.database.messages import get_multiple_response_pb2 as _get_multiple_response_pb2
from gcommon.v1.database.messages import get_request_pb2 as _get_request_pb2
from gcommon.v1.database.messages import get_response_pb2 as _get_response_pb2
from gcommon.v1.database.messages import get_stats_request_pb2 as _get_stats_request_pb2
from gcommon.v1.database.messages import get_stats_response_pb2 as _get_stats_response_pb2
from gcommon.v1.database.messages import increment_request_pb2 as _increment_request_pb2
from gcommon.v1.database.messages import increment_response_pb2 as _increment_response_pb2
from gcommon.v1.database.messages import keys_request_pb2 as _keys_request_pb2
from gcommon.v1.database.messages import keys_response_pb2 as _keys_response_pb2
from gcommon.v1.database.messages import set_multiple_request_pb2 as _set_multiple_request_pb2
from gcommon.v1.database.messages import set_multiple_response_pb2 as _set_multiple_response_pb2
from gcommon.v1.database.messages import set_request_pb2 as _set_request_pb2
from gcommon.v1.database.messages import set_response_pb2 as _set_response_pb2
from gcommon.v1.database.messages import touch_expiration_request_pb2 as _touch_expiration_request_pb2
from gcommon.v1.database.messages import touch_expiration_response_pb2 as _touch_expiration_response_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
