from gcommon.v1.database.messages import create_database_request_pb2 as _create_database_request_pb2
from gcommon.v1.database.messages import create_database_response_pb2 as _create_database_response_pb2
from gcommon.v1.database.messages import create_schema_request_pb2 as _create_schema_request_pb2
from gcommon.v1.database.messages import create_schema_response_pb2 as _create_schema_response_pb2
from gcommon.v1.database.messages import drop_database_request_pb2 as _drop_database_request_pb2
from gcommon.v1.database.messages import drop_schema_request_pb2 as _drop_schema_request_pb2
from gcommon.v1.database.messages import get_database_info_request_pb2 as _get_database_info_request_pb2
from gcommon.v1.database.messages import get_database_info_response_pb2 as _get_database_info_response_pb2
from gcommon.v1.database.messages import list_databases_request_pb2 as _list_databases_request_pb2
from gcommon.v1.database.messages import list_databases_response_pb2 as _list_databases_response_pb2
from gcommon.v1.database.messages import list_schemas_request_pb2 as _list_schemas_request_pb2
from gcommon.v1.database.messages import list_schemas_response_pb2 as _list_schemas_response_pb2
from google.protobuf import empty_pb2 as _empty_pb2
from google.protobuf import go_features_pb2 as _go_features_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
